/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */

#ifndef INCexpdonecodesh
#define INCexpdonecodesh

/* Acq -> Vnmr Experiment Done Codes, identical to ACQ_SUN.h defines */
#define EXP_NULL_CASE 0
#define EXP_FID_CMPLT 11
#define EXP_FIDZERO_CMPLT 60
#define BS_CMPLT      12
#define SOFT_ERROR    13
#define WARNING_MSG   14
#define HARD_ERROR    15
#define EXP_ABORTED   16
#define SETUP_CMPLT   17
#define STOP_CMPLT    18
#define FIX_ACQSTAT   19
#define SYSTEM_READY  90	/* new for inova */
 
/* found in hostAcqStructs.h, however not used in nirvana, so define it here */
#ifndef EXP_HALTED
#define EXP_HALTED	(7)
#endif


/* internal console  Errors, phandler cases as is DoneCodes */
#define LOST_CONN	(20)
#define ALLOC_ERROR	(30)
#define WATCHDOG	(40)
#define INTERACTIVE_ABORT (50)	/* lock display for fid shim abort, used internally in console only */

/*  Pseudo Done Codes:  EXP_COMPLETE, EXP_STARTED.  These values
    are not returned by Console; rather they are generated by expproc.
*/
 
#define EXP_COMPLETE  101
#define EXP_STARTED   102
 


#endif
