/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
/* 
 */
/* this file was generated using 'rpcgen -M -s tcp acqinfo.x -o acqinfo_svc.c'
   -M make the routines thread safe. ZZ
   the acqinfo.x was obatin from the 'stat' category acqinfo.x

   Modification from the rpcgen generated output will be noted.

   Author:  Grege Brissey 9/29/04

 */


#ifndef __INTERIX    /* not used in SFU, svc functions not supported, just ifdef out the entire file */



/* ---  additions to rpcgen generated output --- */
#define _POSIX_PTHREAD_SEMANTICS
/* --------------------------------------------- */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>
#include <sys/types.h>
#ifdef NEVER_TLI_END_FOR_US
#include <netconfig.h>
#endif
#include <sys/resource.h> /* rlimit */
#include <syslog.h>

#ifndef LINUX
#include <rpc/rpc.h>
#include <rpc/types.h>
#endif

#include "acqinfo.h"

/* ---  additions to rpcgen generated output --- */
#include <pthread.h>

pthread_t svc_thread_id;

void start_svc_thread()
{
  int status;
  void *acqinfo_svc(void*);

  status = pthread_create(&svc_thread_id, NULL, acqinfo_svc, NULL);

  if (status != 0)
    perror("unable to create thread for rpc svc:\n");

  status = pthread_detach(svc_thread_id);
  if (status != 0)
    perror("unable to detach thread for rpc svc:\n");
}

/* --------------------------------------------- */
#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120
static int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */
pthread_mutex_t _svcstate_lock = PTHREAD_MUTEX_INITIALIZER;	/* lock for _rpcsvcstate, _rpcsvccount */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

#ifdef NEVER_TLI_END_FOR_US
/*ARGSUSED*/
static void *
closedown(arg)
	void *arg;
{
	/*CONSTCOND*/
	while (1) {
		(void) sleep(_RPCSVC_CLOSEDOWN/2);

		if (pthread_mutex_trylock(&_svcstate_lock) != 0)
			continue;

		if (_rpcsvcstate == _IDLE && _rpcsvccount == 0) {
			int size;
			int i, openfd = 0;

			size = svc_max_pollfd;
			for (i = 0; i < size && openfd < 2; i++)
				if (svc_pollfd[i].fd >= 0)
					openfd++;
			if (openfd <= 1)
				/* exit(0); */
				pthread_exit(NULL);
		} else
			_rpcsvcstate = _IDLE;

		pthread_mutex_unlock(&_svcstate_lock);
	}
}
#endif

#ifndef LINUX
static void
acqinfoprog_2(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		int acqinfo_get_2_arg;
		int acqpid_ping_2_arg;
		ft3ddata ft3d_start_2_arg;
	} argument;
	union {
		acqdata acqinfo_get_2_res;
		int acqpid_ping_2_res;
		int ft3d_start_2_res;
	} result;
	bool_t retval;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	bool_t (*local)();

	pthread_mutex_lock(&_svcstate_lock);
	_rpcsvccount++;
	pthread_mutex_unlock(&_svcstate_lock);
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, xdr_void,
			(char *)NULL);
		pthread_mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		pthread_mutex_unlock(&_svcstate_lock);
		return;

	case ACQINFO_GET:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_acqdata;
		local = (bool_t (*)()) acqinfo_get_2_svc;
		break;

	case ACQPID_PING:
		_xdr_argument = xdr_int;
		_xdr_result = xdr_int;
		local = (bool_t (*)()) acqpid_ping_2_svc;
		break;

	case FT3D_START:
		_xdr_argument = xdr_ft3ddata;
		_xdr_result = xdr_int;
		local = (bool_t (*)()) ft3d_start_2_svc;
		break;

	default:
		svcerr_noproc(transp);
		pthread_mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		pthread_mutex_unlock(&_svcstate_lock);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		pthread_mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		pthread_mutex_unlock(&_svcstate_lock);
		return;
	}
	retval = (bool_t) (*local)(&argument, &result, rqstp);
	if (_xdr_result && retval > 0 && !svc_sendreply(transp, _xdr_result, (char *)&result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		pthread_exit(NULL);
		/* exit(1); */
	}
	if (_xdr_result != NULL) {
		if (!acqinfoprog_2_freeresult(transp, _xdr_result, (caddr_t) &result))
			_msgout("unable to free results");

	}
	pthread_mutex_lock(&_svcstate_lock);
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	pthread_mutex_unlock(&_svcstate_lock);
	return;
}
#endif

/* rpcgen - was main(), changed to acqinfo_svc() */
void *acqinfo_svc(void *arg)
{
	pid_t pid;
	int i;

	(void) sigset(SIGPIPE, SIG_IGN);

	/*
	 * If stdin looks like a TLI endpoint, we assume
	 * that we were started by a port monitor. If
	 * t_getstate fails with TBADF, this is not a
	 * TLI endpoint.
	 */
#ifdef NEVER_TLI_END_FOR_US
	if (t_getstate(0) != -1 || t_errno != TBADF) {
		char *netid;
		struct netconfig *nconf = NULL;
		SVCXPRT *transp;
		int pmclose;

		_rpcpmstart = 1;
		openlog("acqinfo", LOG_PID, LOG_DAEMON);

                syslog(1,"TLI endpoint\n");
		if ((netid = getenv("NLSPROVIDER")) == NULL) {
		/* started from inetd */
			pmclose = 1;
		} else {
			if ((nconf = getnetconfigent(netid)) == NULL)
				_msgout("cannot get transport info");

			pmclose = (t_getstate(0) != T_DATAXFER);
		}
		if ((transp = svc_tli_create(0, nconf, NULL, 0, 0)) == NULL) {
			_msgout("cannot create server handle");
			pthread_exit(NULL);
			/* exit(1); */
		}
		if (nconf)
			freenetconfigent(nconf);
		if (!svc_reg(transp, ACQINFOPROG, ACQINFOVERS, acqinfoprog_2, 0)) {
			_msgout("unable to register (ACQINFOPROG, ACQINFOVERS).");
			pthread_exit(NULL);
			/* exit(1); */
		}
		if (pmclose) {
			if (thr_create(NULL, 0, closedown, NULL,
					0, NULL) != 0) {
				_msgout("cannot create closedown thread");
				pthread_exit(NULL);
				/* exit(1); */
			}
		}
		svc_run();
		pthread_exit(NULL);
		/* exit(1); */
		/* NOTREACHED */
	}	
       else 
#endif
#ifdef NEVER_TLI_END_FOR_US
        {
#ifndef RPC_SVC_FG
#pragma weak closefrom
		extern void closefrom();
		int size;
		struct rlimit rl;
                syslog(1,"NOT TLI endpoint, forking\n");
		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			pthread_exit(NULL);
			/* exit(1); */
		}
		if (pid)
			pthread_exit(NULL);
			/* exit(0); */
		if (closefrom != NULL)
			closefrom(0);
		else {
			rl.rlim_max = 0;
			getrlimit(RLIMIT_NOFILE, &rl);
			if ((size = rl.rlim_max) == 0)
				pthread_exit(NULL);
				/* exit(1); */
			for (i = 0; i < size; i++)
				(void) close(i);
		}
		i = open("/dev/null", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		setsid();
		openlog("acqinfo", LOG_PID, LOG_DAEMON);
#endif
	}
#endif
#ifndef LINUX
	if (!svc_create(acqinfoprog_2, ACQINFOPROG, ACQINFOVERS, "tcp"))
        {
		_msgout("unable to create (ACQINFOPROG, ACQINFOVERS) for tcp.");
		pthread_exit(NULL);
		/* exit(1); */
	}
#endif

	svc_run();
	_msgout("svc_run returned");
	pthread_exit(NULL);
	/* exit(1); */
	/* NOTREACHED */
}


#endif
