/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
/*
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PlotFile */

#ifndef _Included_PlotFile
#define _Included_PlotFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PlotFile
 * Method:    list_templates
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PlotFile_list_1templates
  (JNIEnv *, jclass, jint);

/*
 * Class:     PlotFile
 * Method:    remove_templates
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PlotFile_remove_1templates
  (JNIEnv *, jclass, jstring);

/*
 * Class:     PlotFile
 * Method:    access_templates
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_PlotFile_access_1templates
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
