all:; -(scons)

build-local:; -(scons)

#Build-remote:; Build Remote
# ssh kerickso@10.190.213.106 'cd /data/kasey/git-repo/software/ && scons -j4'

clean:; -(scons -c)

diff-global:; -(git diff)

diff-local:; -(git diff .)

Gitk:; -(gitk --since="2 weeks ago")

Pull:; -(git pull)

Push:; -(git push)

Resolve-conflicts:; -(git mergetool -t kdiff3)

Status:; -(git status)

