#

import os
import sys
sys.path.append(os.path.join(os.getcwd(), os.pardir, os.pardir, 'scripts'))
import myShutil # for better copytree()

# get current working directory
cwd = os.getcwd()

dest = os.path.join(cwd,os.pardir,os.pardir,os.pardir,'options','standard','P11')
# Alternate path for non-option installation
# dest = os.path.join(cwd,os.pardir,os.pardir,os.pardir,'vnmr','p11')
if not os.path.exists(dest) :
    os.makedirs(dest)

for i in os.listdir(cwd):
   if ((i != "SConstruct") and (i != "walkup") and (not i.startswith('.')) ):
      myShutil.copytree(i,dest,symlinks = False)
