//@copy-c-declaration /*
//@copy-c-declaration *
//@copy-c-declaration * Varian,Inc. All Rights Reserved.
//@copy-c-declaration * This software contains proprietary and confidential
//@copy-c-declaration * information of Varian, Inc. and its contributors.
//@copy-c-declaration * Use, disclosure and reproduction is prohibited without
//@copy-c-declaration * prior consent.
//@copy-c-declaration */
//@copy-c-declaration /*
//@copy-c-declaration *  Author: Greg Brissey  11/05/2007
//@copy-c-declaration */

//@copy-c-declaration #include "NDDS_Obj.h"


const string CONSOLE_CONF_STRUCT_VERSION = 1;
const string CNTLR_PUB_CONF_TOPIC_FORMAT_STR = "master/h/conconf";
const string HOST_SUB_CONF_TOPIC_FORMAT_STR = "master/h/conconf";

const long CONSOLE_CONF_MAX_STR_LEN = 64;

struct Console_Conf {
        long structVersion;   /* version of this structure */
        long ConsoleTypeFlag; /* VNMRS, 400MR,  */
        long SystemRevId;
        string <CONSOLE_CONF_MAX_STR_LEN> VxWorksVersion;
        string <CONSOLE_CONF_MAX_STR_LEN> RtiNddsVersion;
        string <CONSOLE_CONF_MAX_STR_LEN> PsgInterpVersion;
        string <CONSOLE_CONF_MAX_STR_LEN> CompileDate;
        string <CONSOLE_CONF_MAX_STR_LEN> ddrmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> gradientmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> lockmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> mastermd5;
        string <CONSOLE_CONF_MAX_STR_LEN> nvlibmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> nvScriptmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> pfgmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> lpfgmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> rfmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> vxWorksKernelmd5;
        string <CONSOLE_CONF_MAX_STR_LEN> fpgaLoadStr;
};

//@copy-c-declaration #ifdef __cplusplus
//@copy-c-declaration     extern "C" {
//@copy-c-declaration #endif
//@copy-c-declaration 
//@copy-c-declaration extern void getConsole_ConfInfo(NDDS_OBJ *pObj);
//@copy-c-declaration 
//@copy-c-declaration #ifdef __cplusplus
//@copy-c-declaration }
//@copy-c-declaration #endif

