/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
/*
 *
 */ 
/*
 *    This ddr.h file is auto generated via Tau's CVS make base on the
 *    DDR FPGA verilog source
 *    It's place in our SCCS for consistency with our software
 */

#ifndef DDR_H
#define DDR_H
#ifndef get_field
  #define get_field(fpga,field) \
    ((*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))>> \
    fpga##_##field##_pos) & (((fpga##_##field##_width<32) ? (1<<fpga##_##field##_width):0)-1))
#endif
#ifndef set_field
  #define set_field(fpga,field,value) \
    ((*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))) = \
    (*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))) & \
    ~((((fpga##_##field##_width<32)?(1<<fpga##_##field##_width):0)-1)<<fpga##_##field##_pos) | \
    ((value&(((fpga##_##field##_width<32)?(1<<fpga##_##field##_width):0)-1))<<fpga##_##field##_pos))
#endif
#define DDR_CHECKSUM 61213
#define DDR_ID 0x0
#define DDR_LED 0x4
#define DDR_BoardAddress 0x8
#define DDR_InterfaceType 0xc
#define DDR_Failure 0x10
#define DDR_DMARequest 0x14
#define DDR_SCLKClockControl 0x18
#define DDR_SCLKClockStatus 0x1c
#define DDR_FIFOControl 0x20
#define DDR_FIFOStatus 0x24
#define DDR_InstructionFIFOHighThreshold 0x28
#define DDR_InstructionFIFOLowThreshold 0x2c
#define DDR_InstructionFIFOCount 0x30
#define DDR_DataFIFOCount 0x34
#define DDR_ClearCumulativeDuration 0x38
#define DDR_CumulativeDurationLow 0x3c
#define DDR_CumulativeDurationHigh 0x40
#define DDR_J1COutput 0x44
#define DDR_J1CEnable 0x48
#define DDR_J1CInput 0x4c
#define DDR_J2COutput 0x50
#define DDR_J2CEnable 0x54
#define DDR_J2CInput 0x58
#define DDR_InstructionFifoCountTotal 0x5c
#define DDR_ClearInstructionFifoCountTotal 0x60
#define DDR_InvalidOpcode 0x64
#define DDR_SoftwareOutputs 0x68
#define DDR_FIFOGatesOutputPolarity 0x6c
#define DDR_GPInterrupt 0x70
#define DDR_InterruptStatus_0 0x74
#define DDR_InterruptEnable_0 0x78
#define DDR_InterruptClear_0 0x7c
#define DDR_InterruptStatus_1 0x80
#define DDR_InterruptEnable_1 0x84
#define DDR_InterruptClear_1 0x88
#define DDR_InterruptStatus_2 0x8c
#define DDR_InterruptEnable_2 0x90
#define DDR_InterruptClear_2 0x94
#define DDR_InterruptStatus_3 0x98
#define DDR_InterruptEnable_3 0x9c
#define DDR_InterruptClear_3 0xa0
#define DDR_InterruptStatus_4 0xa4
#define DDR_InterruptEnable_4 0xa8
#define DDR_InterruptClear_4 0xac
#define DDR_InterruptStatus_5 0xb0
#define DDR_InterruptEnable_5 0xb4
#define DDR_InterruptClear_5 0xb8
#define DDR_SoftwareGates 0xbc
#define DDR_SoftwareGain 0xc0
#define DDR_SoftwareAUX 0xc4
#define DDR_SoftwareAUXReset 0xc8
#define DDR_SoftwareAUXStrobe 0xcc
#define DDR_FIFOOutputSelect 0xd0
#define DDR_FIFOGates 0xd4
#define DDR_FIFOGain 0xd8
#define DDR_FIFOAUX 0xdc
#define DDR_AUXRead 0xe0
#define DDR_Duration 0xe4
#define DDR_Gates 0xe8
#define DDR_Gain 0xec
#define DDR_FIFOInstructionWrite 0xf0
#define DDR_C67Reset 0xf4
#define DDR_C67Configuration 0xf8
#define DDR_HPIBaseAddress0 0xfc
#define DDR_HPIBaseAddress1 0x100
#define DDR_HPIBaseAddress2 0x104
#define DDR_HPIAutoIncrement 0x108
#define DDR_HPIControlAccess 0x10c
#define DDR_HPITiming 0x110
#define DDR_HPITimeout 0x114
#define DDR_HPIBusy 0x118
#define DDR_EMIFEnable 0x11c
#define DDR_EMIFState 0x120
#define DDR_EMIFClockControl 0x124
#define DDR_EMIFClockStatus 0x128
#define DDR_EBCTimeout 0x12c
#define DDR_ADCArmFIFO 0x130
#define DDR_ADCFifoControl 0x134
#define DDR_ADCFifoDelay 0x138
#define DDR_ADCCount 0x13c
#define DDR_ADCReadPointer 0x140
#define DDR_DitherControl 0x144
#define DDR_AD6634Reset 0x148
#define DDR_AD6634SyncPhase 0x14c
#define DDR_LogicAnalyzerConfig 0x150
#define DDR_LogicAnalyzerStatus 0x154
#define DDR_LogicAnalyzerChecksum 0x158
#define DDR_LogicAnalyzerAddress 0x15c
#define DDR_LogicAnalyzerSampleData 0x160
#define DDR_ScratchRAM 0x2000
#define DDR_ID_addr 0x0
#define DDR_ID_pos 0
#define DDR_ID_width 4
#define DDR_revision_addr 0x0
#define DDR_revision_pos 4
#define DDR_revision_width 4
#define DDR_checksum_addr 0x0
#define DDR_checksum_pos 8
#define DDR_checksum_width 16
#define DDR_led_addr 0x4
#define DDR_led_pos 0
#define DDR_led_width 6
#define DDR_bd_addr_addr 0x8
#define DDR_bd_addr_pos 0
#define DDR_bd_addr_width 5
#define DDR_type_addr_addr 0xc
#define DDR_type_addr_pos 0
#define DDR_type_addr_width 3
#define DDR_sw_failure_addr 0x10
#define DDR_sw_failure_pos 0
#define DDR_sw_failure_width 1
#define DDR_sw_warning_addr 0x10
#define DDR_sw_warning_pos 1
#define DDR_sw_warning_width 1
#define DDR_dma_request_addr 0x14
#define DDR_dma_request_pos 0
#define DDR_dma_request_width 1
#define DDR_sclk_rst_addr 0x18
#define DDR_sclk_rst_pos 0
#define DDR_sclk_rst_width 1
#define DDR_sclk_psincdec_addr 0x18
#define DDR_sclk_psincdec_pos 1
#define DDR_sclk_psincdec_width 1
#define DDR_sclk_psen_addr 0x18
#define DDR_sclk_psen_pos 2
#define DDR_sclk_psen_width 1
#define DDR_sclk_psclk_addr 0x18
#define DDR_sclk_psclk_pos 3
#define DDR_sclk_psclk_width 1
#define DDR_sclk_locked_addr 0x1c
#define DDR_sclk_locked_pos 0
#define DDR_sclk_locked_width 1
#define DDR_sclk_psdone_addr 0x1c
#define DDR_sclk_psdone_pos 1
#define DDR_sclk_psdone_width 1
#define DDR_sclk_status_addr 0x1c
#define DDR_sclk_status_pos 2
#define DDR_sclk_status_width 3
#define DDR_fifo_start_addr 0x20
#define DDR_fifo_start_pos 0
#define DDR_fifo_start_width 1
#define DDR_fifo_sync_start_addr 0x20
#define DDR_fifo_sync_start_pos 1
#define DDR_fifo_sync_start_width 1
#define DDR_fifo_reset_addr 0x20
#define DDR_fifo_reset_pos 2
#define DDR_fifo_reset_width 1
#define DDR_fifo_active_addr 0x24
#define DDR_fifo_active_pos 0
#define DDR_fifo_active_width 1
#define DDR_instruction_fifo_high_threshold_addr 0x28
#define DDR_instruction_fifo_high_threshold_pos 0
#define DDR_instruction_fifo_high_threshold_width 10
#define DDR_instruction_fifo_low_threshold_addr 0x2c
#define DDR_instruction_fifo_low_threshold_pos 0
#define DDR_instruction_fifo_low_threshold_width 10
#define DDR_instruction_fifo_count_addr 0x30
#define DDR_instruction_fifo_count_pos 0
#define DDR_instruction_fifo_count_width 10
#define DDR_data_fifo_count_addr 0x34
#define DDR_data_fifo_count_pos 0
#define DDR_data_fifo_count_width 9
#define DDR_clear_cumulative_duration_addr 0x38
#define DDR_clear_cumulative_duration_pos 0
#define DDR_clear_cumulative_duration_width 1
#define DDR_cumulative_duration_low_addr 0x3c
#define DDR_cumulative_duration_low_pos 0
#define DDR_cumulative_duration_low_width 32
#define DDR_cumulative_duration_high_addr 0x40
#define DDR_cumulative_duration_high_pos 0
#define DDR_cumulative_duration_high_width 32
#define DDR_J1_C_out_addr 0x44
#define DDR_J1_C_out_pos 0
#define DDR_J1_C_out_width 32
#define DDR_J1_C_en_addr 0x48
#define DDR_J1_C_en_pos 0
#define DDR_J1_C_en_width 32
#define DDR_J1_C_addr 0x4c
#define DDR_J1_C_pos 0
#define DDR_J1_C_width 32
#define DDR_J2_C_out_addr 0x50
#define DDR_J2_C_out_pos 0
#define DDR_J2_C_out_width 32
#define DDR_J2_C_en_addr 0x54
#define DDR_J2_C_en_pos 0
#define DDR_J2_C_en_width 32
#define DDR_J2_C_addr 0x58
#define DDR_J2_C_pos 0
#define DDR_J2_C_width 32
#define DDR_instr_fifo_count_total_addr 0x5c
#define DDR_instr_fifo_count_total_pos 0
#define DDR_instr_fifo_count_total_width 32
#define DDR_clear_instr_fifo_count_total_addr 0x60
#define DDR_clear_instr_fifo_count_total_pos 0
#define DDR_clear_instr_fifo_count_total_width 1
#define DDR_invalid_opcode_addr 0x64
#define DDR_invalid_opcode_pos 0
#define DDR_invalid_opcode_width 16
#define DDR_acquire_addr 0x68
#define DDR_acquire_pos 0
#define DDR_acquire_width 1
#define DDR_overload_addr 0x68
#define DDR_overload_pos 1
#define DDR_overload_width 1
#define DDR_sw_control_gpoutputs_addr 0x68
#define DDR_sw_control_gpoutputs_pos 2
#define DDR_sw_control_gpoutputs_width 4
#define DDR_fifo_gates_output_polarity_addr 0x6c
#define DDR_fifo_gates_output_polarity_pos 0
#define DDR_fifo_gates_output_polarity_width 12
#define DDR_gp_int_addr 0x70
#define DDR_gp_int_pos 0
#define DDR_gp_int_width 8
#define DDR_fifo_overflow_status_0_addr 0x74
#define DDR_fifo_overflow_status_0_pos 0
#define DDR_fifo_overflow_status_0_width 1
#define DDR_fifo_underflow_status_0_addr 0x74
#define DDR_fifo_underflow_status_0_pos 1
#define DDR_fifo_underflow_status_0_width 1
#define DDR_fifo_finished_status_0_addr 0x74
#define DDR_fifo_finished_status_0_pos 2
#define DDR_fifo_finished_status_0_width 1
#define DDR_fifo_started_status_0_addr 0x74
#define DDR_fifo_started_status_0_pos 3
#define DDR_fifo_started_status_0_width 1
#define DDR_sw_int_status_0_addr 0x74
#define DDR_sw_int_status_0_pos 4
#define DDR_sw_int_status_0_width 4
#define DDR_fail_int_status_0_addr 0x74
#define DDR_fail_int_status_0_pos 8
#define DDR_fail_int_status_0_width 1
#define DDR_warn_int_status_0_addr 0x74
#define DDR_warn_int_status_0_pos 9
#define DDR_warn_int_status_0_width 1
#define DDR_data_fifo_almost_empty_status_0_addr 0x74
#define DDR_data_fifo_almost_empty_status_0_pos 10
#define DDR_data_fifo_almost_empty_status_0_width 1
#define DDR_instr_fifo_almost_full_status_0_addr 0x74
#define DDR_instr_fifo_almost_full_status_0_pos 11
#define DDR_instr_fifo_almost_full_status_0_width 1
#define DDR_invalid_opcode_int_status_0_addr 0x74
#define DDR_invalid_opcode_int_status_0_pos 12
#define DDR_invalid_opcode_int_status_0_width 1
#define DDR_host_int_status_0_addr 0x74
#define DDR_host_int_status_0_pos 13
#define DDR_host_int_status_0_width 1
#define DDR_adc_overflow_int_status_0_addr 0x74
#define DDR_adc_overflow_int_status_0_pos 14
#define DDR_adc_overflow_int_status_0_width 1
#define DDR_adc_underflow_int_status_0_addr 0x74
#define DDR_adc_underflow_int_status_0_pos 15
#define DDR_adc_underflow_int_status_0_width 1
#define DDR_adc_threshold_int_status_0_addr 0x74
#define DDR_adc_threshold_int_status_0_pos 16
#define DDR_adc_threshold_int_status_0_width 1
#define DDR_AD6634_OVF_int_status_0_addr 0x74
#define DDR_AD6634_OVF_int_status_0_pos 17
#define DDR_AD6634_OVF_int_status_0_width 1
#define DDR_sync_int_status_0_addr 0x74
#define DDR_sync_int_status_0_pos 18
#define DDR_sync_int_status_0_width 4
#define DDR_gp_int_status_0_addr 0x74
#define DDR_gp_int_status_0_pos 22
#define DDR_gp_int_status_0_width 8
#define DDR_fifo_overflow_enable_0_addr 0x78
#define DDR_fifo_overflow_enable_0_pos 0
#define DDR_fifo_overflow_enable_0_width 1
#define DDR_fifo_underflow_enable_0_addr 0x78
#define DDR_fifo_underflow_enable_0_pos 1
#define DDR_fifo_underflow_enable_0_width 1
#define DDR_fifo_finished_enable_0_addr 0x78
#define DDR_fifo_finished_enable_0_pos 2
#define DDR_fifo_finished_enable_0_width 1
#define DDR_fifo_started_enable_0_addr 0x78
#define DDR_fifo_started_enable_0_pos 3
#define DDR_fifo_started_enable_0_width 1
#define DDR_sw_int_enable_0_addr 0x78
#define DDR_sw_int_enable_0_pos 4
#define DDR_sw_int_enable_0_width 4
#define DDR_fail_int_enable_0_addr 0x78
#define DDR_fail_int_enable_0_pos 8
#define DDR_fail_int_enable_0_width 1
#define DDR_warn_int_enable_0_addr 0x78
#define DDR_warn_int_enable_0_pos 9
#define DDR_warn_int_enable_0_width 1
#define DDR_data_fifo_almost_empty_enable_0_addr 0x78
#define DDR_data_fifo_almost_empty_enable_0_pos 10
#define DDR_data_fifo_almost_empty_enable_0_width 1
#define DDR_instr_fifo_almost_full_enable_0_addr 0x78
#define DDR_instr_fifo_almost_full_enable_0_pos 11
#define DDR_instr_fifo_almost_full_enable_0_width 1
#define DDR_invalid_opcode_int_enable_0_addr 0x78
#define DDR_invalid_opcode_int_enable_0_pos 12
#define DDR_invalid_opcode_int_enable_0_width 1
#define DDR_host_int_enable_0_addr 0x78
#define DDR_host_int_enable_0_pos 13
#define DDR_host_int_enable_0_width 1
#define DDR_adc_overflow_int_enable_0_addr 0x78
#define DDR_adc_overflow_int_enable_0_pos 14
#define DDR_adc_overflow_int_enable_0_width 1
#define DDR_adc_underflow_int_enable_0_addr 0x78
#define DDR_adc_underflow_int_enable_0_pos 15
#define DDR_adc_underflow_int_enable_0_width 1
#define DDR_adc_threshold_int_enable_0_addr 0x78
#define DDR_adc_threshold_int_enable_0_pos 16
#define DDR_adc_threshold_int_enable_0_width 1
#define DDR_AD6634_OVF_int_enable_0_addr 0x78
#define DDR_AD6634_OVF_int_enable_0_pos 17
#define DDR_AD6634_OVF_int_enable_0_width 1
#define DDR_sync_int_enable_0_addr 0x78
#define DDR_sync_int_enable_0_pos 18
#define DDR_sync_int_enable_0_width 4
#define DDR_gp_int_enable_0_addr 0x78
#define DDR_gp_int_enable_0_pos 22
#define DDR_gp_int_enable_0_width 8
#define DDR_fifo_overflow_clear_0_addr 0x7c
#define DDR_fifo_overflow_clear_0_pos 0
#define DDR_fifo_overflow_clear_0_width 1
#define DDR_fifo_underflow_clear_0_addr 0x7c
#define DDR_fifo_underflow_clear_0_pos 1
#define DDR_fifo_underflow_clear_0_width 1
#define DDR_fifo_finished_clear_0_addr 0x7c
#define DDR_fifo_finished_clear_0_pos 2
#define DDR_fifo_finished_clear_0_width 1
#define DDR_fifo_started_clear_0_addr 0x7c
#define DDR_fifo_started_clear_0_pos 3
#define DDR_fifo_started_clear_0_width 1
#define DDR_sw_int_clear_0_addr 0x7c
#define DDR_sw_int_clear_0_pos 4
#define DDR_sw_int_clear_0_width 4
#define DDR_fail_int_clear_0_addr 0x7c
#define DDR_fail_int_clear_0_pos 8
#define DDR_fail_int_clear_0_width 1
#define DDR_warn_int_clear_0_addr 0x7c
#define DDR_warn_int_clear_0_pos 9
#define DDR_warn_int_clear_0_width 1
#define DDR_data_fifo_almost_empty_clear_0_addr 0x7c
#define DDR_data_fifo_almost_empty_clear_0_pos 10
#define DDR_data_fifo_almost_empty_clear_0_width 1
#define DDR_instr_fifo_almost_full_clear_0_addr 0x7c
#define DDR_instr_fifo_almost_full_clear_0_pos 11
#define DDR_instr_fifo_almost_full_clear_0_width 1
#define DDR_invalid_opcode_int_clear_0_addr 0x7c
#define DDR_invalid_opcode_int_clear_0_pos 12
#define DDR_invalid_opcode_int_clear_0_width 1
#define DDR_host_int_clear_0_addr 0x7c
#define DDR_host_int_clear_0_pos 13
#define DDR_host_int_clear_0_width 1
#define DDR_adc_overflow_int_clear_0_addr 0x7c
#define DDR_adc_overflow_int_clear_0_pos 14
#define DDR_adc_overflow_int_clear_0_width 1
#define DDR_adc_underflow_int_clear_0_addr 0x7c
#define DDR_adc_underflow_int_clear_0_pos 15
#define DDR_adc_underflow_int_clear_0_width 1
#define DDR_adc_threshold_int_clear_0_addr 0x7c
#define DDR_adc_threshold_int_clear_0_pos 16
#define DDR_adc_threshold_int_clear_0_width 1
#define DDR_AD6634_OVF_int_clear_0_addr 0x7c
#define DDR_AD6634_OVF_int_clear_0_pos 17
#define DDR_AD6634_OVF_int_clear_0_width 1
#define DDR_sync_int_clear_0_addr 0x7c
#define DDR_sync_int_clear_0_pos 18
#define DDR_sync_int_clear_0_width 4
#define DDR_gp_int_clear_0_addr 0x7c
#define DDR_gp_int_clear_0_pos 22
#define DDR_gp_int_clear_0_width 8
#define DDR_fifo_overflow_status_1_addr 0x80
#define DDR_fifo_overflow_status_1_pos 0
#define DDR_fifo_overflow_status_1_width 1
#define DDR_fifo_underflow_status_1_addr 0x80
#define DDR_fifo_underflow_status_1_pos 1
#define DDR_fifo_underflow_status_1_width 1
#define DDR_fifo_finished_status_1_addr 0x80
#define DDR_fifo_finished_status_1_pos 2
#define DDR_fifo_finished_status_1_width 1
#define DDR_fifo_started_status_1_addr 0x80
#define DDR_fifo_started_status_1_pos 3
#define DDR_fifo_started_status_1_width 1
#define DDR_sw_int_status_1_addr 0x80
#define DDR_sw_int_status_1_pos 4
#define DDR_sw_int_status_1_width 4
#define DDR_fail_int_status_1_addr 0x80
#define DDR_fail_int_status_1_pos 8
#define DDR_fail_int_status_1_width 1
#define DDR_warn_int_status_1_addr 0x80
#define DDR_warn_int_status_1_pos 9
#define DDR_warn_int_status_1_width 1
#define DDR_data_fifo_almost_empty_status_1_addr 0x80
#define DDR_data_fifo_almost_empty_status_1_pos 10
#define DDR_data_fifo_almost_empty_status_1_width 1
#define DDR_instr_fifo_almost_full_status_1_addr 0x80
#define DDR_instr_fifo_almost_full_status_1_pos 11
#define DDR_instr_fifo_almost_full_status_1_width 1
#define DDR_invalid_opcode_int_status_1_addr 0x80
#define DDR_invalid_opcode_int_status_1_pos 12
#define DDR_invalid_opcode_int_status_1_width 1
#define DDR_host_int_status_1_addr 0x80
#define DDR_host_int_status_1_pos 13
#define DDR_host_int_status_1_width 1
#define DDR_adc_overflow_int_status_1_addr 0x80
#define DDR_adc_overflow_int_status_1_pos 14
#define DDR_adc_overflow_int_status_1_width 1
#define DDR_adc_underflow_int_status_1_addr 0x80
#define DDR_adc_underflow_int_status_1_pos 15
#define DDR_adc_underflow_int_status_1_width 1
#define DDR_adc_threshold_int_status_1_addr 0x80
#define DDR_adc_threshold_int_status_1_pos 16
#define DDR_adc_threshold_int_status_1_width 1
#define DDR_AD6634_OVF_int_status_1_addr 0x80
#define DDR_AD6634_OVF_int_status_1_pos 17
#define DDR_AD6634_OVF_int_status_1_width 1
#define DDR_sync_int_status_1_addr 0x80
#define DDR_sync_int_status_1_pos 18
#define DDR_sync_int_status_1_width 4
#define DDR_gp_int_status_1_addr 0x80
#define DDR_gp_int_status_1_pos 22
#define DDR_gp_int_status_1_width 8
#define DDR_fifo_overflow_enable_1_addr 0x84
#define DDR_fifo_overflow_enable_1_pos 0
#define DDR_fifo_overflow_enable_1_width 1
#define DDR_fifo_underflow_enable_1_addr 0x84
#define DDR_fifo_underflow_enable_1_pos 1
#define DDR_fifo_underflow_enable_1_width 1
#define DDR_fifo_finished_enable_1_addr 0x84
#define DDR_fifo_finished_enable_1_pos 2
#define DDR_fifo_finished_enable_1_width 1
#define DDR_fifo_started_enable_1_addr 0x84
#define DDR_fifo_started_enable_1_pos 3
#define DDR_fifo_started_enable_1_width 1
#define DDR_sw_int_enable_1_addr 0x84
#define DDR_sw_int_enable_1_pos 4
#define DDR_sw_int_enable_1_width 4
#define DDR_fail_int_enable_1_addr 0x84
#define DDR_fail_int_enable_1_pos 8
#define DDR_fail_int_enable_1_width 1
#define DDR_warn_int_enable_1_addr 0x84
#define DDR_warn_int_enable_1_pos 9
#define DDR_warn_int_enable_1_width 1
#define DDR_data_fifo_almost_empty_enable_1_addr 0x84
#define DDR_data_fifo_almost_empty_enable_1_pos 10
#define DDR_data_fifo_almost_empty_enable_1_width 1
#define DDR_instr_fifo_almost_full_enable_1_addr 0x84
#define DDR_instr_fifo_almost_full_enable_1_pos 11
#define DDR_instr_fifo_almost_full_enable_1_width 1
#define DDR_invalid_opcode_int_enable_1_addr 0x84
#define DDR_invalid_opcode_int_enable_1_pos 12
#define DDR_invalid_opcode_int_enable_1_width 1
#define DDR_host_int_enable_1_addr 0x84
#define DDR_host_int_enable_1_pos 13
#define DDR_host_int_enable_1_width 1
#define DDR_adc_overflow_int_enable_1_addr 0x84
#define DDR_adc_overflow_int_enable_1_pos 14
#define DDR_adc_overflow_int_enable_1_width 1
#define DDR_adc_underflow_int_enable_1_addr 0x84
#define DDR_adc_underflow_int_enable_1_pos 15
#define DDR_adc_underflow_int_enable_1_width 1
#define DDR_adc_threshold_int_enable_1_addr 0x84
#define DDR_adc_threshold_int_enable_1_pos 16
#define DDR_adc_threshold_int_enable_1_width 1
#define DDR_AD6634_OVF_int_enable_1_addr 0x84
#define DDR_AD6634_OVF_int_enable_1_pos 17
#define DDR_AD6634_OVF_int_enable_1_width 1
#define DDR_sync_int_enable_1_addr 0x84
#define DDR_sync_int_enable_1_pos 18
#define DDR_sync_int_enable_1_width 4
#define DDR_gp_int_enable_1_addr 0x84
#define DDR_gp_int_enable_1_pos 22
#define DDR_gp_int_enable_1_width 8
#define DDR_fifo_overflow_clear_1_addr 0x88
#define DDR_fifo_overflow_clear_1_pos 0
#define DDR_fifo_overflow_clear_1_width 1
#define DDR_fifo_underflow_clear_1_addr 0x88
#define DDR_fifo_underflow_clear_1_pos 1
#define DDR_fifo_underflow_clear_1_width 1
#define DDR_fifo_finished_clear_1_addr 0x88
#define DDR_fifo_finished_clear_1_pos 2
#define DDR_fifo_finished_clear_1_width 1
#define DDR_fifo_started_clear_1_addr 0x88
#define DDR_fifo_started_clear_1_pos 3
#define DDR_fifo_started_clear_1_width 1
#define DDR_sw_int_clear_1_addr 0x88
#define DDR_sw_int_clear_1_pos 4
#define DDR_sw_int_clear_1_width 4
#define DDR_fail_int_clear_1_addr 0x88
#define DDR_fail_int_clear_1_pos 8
#define DDR_fail_int_clear_1_width 1
#define DDR_warn_int_clear_1_addr 0x88
#define DDR_warn_int_clear_1_pos 9
#define DDR_warn_int_clear_1_width 1
#define DDR_data_fifo_almost_empty_clear_1_addr 0x88
#define DDR_data_fifo_almost_empty_clear_1_pos 10
#define DDR_data_fifo_almost_empty_clear_1_width 1
#define DDR_instr_fifo_almost_full_clear_1_addr 0x88
#define DDR_instr_fifo_almost_full_clear_1_pos 11
#define DDR_instr_fifo_almost_full_clear_1_width 1
#define DDR_invalid_opcode_int_clear_1_addr 0x88
#define DDR_invalid_opcode_int_clear_1_pos 12
#define DDR_invalid_opcode_int_clear_1_width 1
#define DDR_host_int_clear_1_addr 0x88
#define DDR_host_int_clear_1_pos 13
#define DDR_host_int_clear_1_width 1
#define DDR_adc_overflow_int_clear_1_addr 0x88
#define DDR_adc_overflow_int_clear_1_pos 14
#define DDR_adc_overflow_int_clear_1_width 1
#define DDR_adc_underflow_int_clear_1_addr 0x88
#define DDR_adc_underflow_int_clear_1_pos 15
#define DDR_adc_underflow_int_clear_1_width 1
#define DDR_adc_threshold_int_clear_1_addr 0x88
#define DDR_adc_threshold_int_clear_1_pos 16
#define DDR_adc_threshold_int_clear_1_width 1
#define DDR_AD6634_OVF_int_clear_1_addr 0x88
#define DDR_AD6634_OVF_int_clear_1_pos 17
#define DDR_AD6634_OVF_int_clear_1_width 1
#define DDR_sync_int_clear_1_addr 0x88
#define DDR_sync_int_clear_1_pos 18
#define DDR_sync_int_clear_1_width 4
#define DDR_gp_int_clear_1_addr 0x88
#define DDR_gp_int_clear_1_pos 22
#define DDR_gp_int_clear_1_width 8
#define DDR_fifo_overflow_status_2_addr 0x8c
#define DDR_fifo_overflow_status_2_pos 0
#define DDR_fifo_overflow_status_2_width 1
#define DDR_fifo_underflow_status_2_addr 0x8c
#define DDR_fifo_underflow_status_2_pos 1
#define DDR_fifo_underflow_status_2_width 1
#define DDR_fifo_finished_status_2_addr 0x8c
#define DDR_fifo_finished_status_2_pos 2
#define DDR_fifo_finished_status_2_width 1
#define DDR_fifo_started_status_2_addr 0x8c
#define DDR_fifo_started_status_2_pos 3
#define DDR_fifo_started_status_2_width 1
#define DDR_sw_int_status_2_addr 0x8c
#define DDR_sw_int_status_2_pos 4
#define DDR_sw_int_status_2_width 4
#define DDR_fail_int_status_2_addr 0x8c
#define DDR_fail_int_status_2_pos 8
#define DDR_fail_int_status_2_width 1
#define DDR_warn_int_status_2_addr 0x8c
#define DDR_warn_int_status_2_pos 9
#define DDR_warn_int_status_2_width 1
#define DDR_data_fifo_almost_empty_status_2_addr 0x8c
#define DDR_data_fifo_almost_empty_status_2_pos 10
#define DDR_data_fifo_almost_empty_status_2_width 1
#define DDR_instr_fifo_almost_full_status_2_addr 0x8c
#define DDR_instr_fifo_almost_full_status_2_pos 11
#define DDR_instr_fifo_almost_full_status_2_width 1
#define DDR_invalid_opcode_int_status_2_addr 0x8c
#define DDR_invalid_opcode_int_status_2_pos 12
#define DDR_invalid_opcode_int_status_2_width 1
#define DDR_host_int_status_2_addr 0x8c
#define DDR_host_int_status_2_pos 13
#define DDR_host_int_status_2_width 1
#define DDR_adc_overflow_int_status_2_addr 0x8c
#define DDR_adc_overflow_int_status_2_pos 14
#define DDR_adc_overflow_int_status_2_width 1
#define DDR_adc_underflow_int_status_2_addr 0x8c
#define DDR_adc_underflow_int_status_2_pos 15
#define DDR_adc_underflow_int_status_2_width 1
#define DDR_adc_threshold_int_status_2_addr 0x8c
#define DDR_adc_threshold_int_status_2_pos 16
#define DDR_adc_threshold_int_status_2_width 1
#define DDR_AD6634_OVF_int_status_2_addr 0x8c
#define DDR_AD6634_OVF_int_status_2_pos 17
#define DDR_AD6634_OVF_int_status_2_width 1
#define DDR_sync_int_status_2_addr 0x8c
#define DDR_sync_int_status_2_pos 18
#define DDR_sync_int_status_2_width 4
#define DDR_gp_int_status_2_addr 0x8c
#define DDR_gp_int_status_2_pos 22
#define DDR_gp_int_status_2_width 8
#define DDR_fifo_overflow_enable_2_addr 0x90
#define DDR_fifo_overflow_enable_2_pos 0
#define DDR_fifo_overflow_enable_2_width 1
#define DDR_fifo_underflow_enable_2_addr 0x90
#define DDR_fifo_underflow_enable_2_pos 1
#define DDR_fifo_underflow_enable_2_width 1
#define DDR_fifo_finished_enable_2_addr 0x90
#define DDR_fifo_finished_enable_2_pos 2
#define DDR_fifo_finished_enable_2_width 1
#define DDR_fifo_started_enable_2_addr 0x90
#define DDR_fifo_started_enable_2_pos 3
#define DDR_fifo_started_enable_2_width 1
#define DDR_sw_int_enable_2_addr 0x90
#define DDR_sw_int_enable_2_pos 4
#define DDR_sw_int_enable_2_width 4
#define DDR_fail_int_enable_2_addr 0x90
#define DDR_fail_int_enable_2_pos 8
#define DDR_fail_int_enable_2_width 1
#define DDR_warn_int_enable_2_addr 0x90
#define DDR_warn_int_enable_2_pos 9
#define DDR_warn_int_enable_2_width 1
#define DDR_data_fifo_almost_empty_enable_2_addr 0x90
#define DDR_data_fifo_almost_empty_enable_2_pos 10
#define DDR_data_fifo_almost_empty_enable_2_width 1
#define DDR_instr_fifo_almost_full_enable_2_addr 0x90
#define DDR_instr_fifo_almost_full_enable_2_pos 11
#define DDR_instr_fifo_almost_full_enable_2_width 1
#define DDR_invalid_opcode_int_enable_2_addr 0x90
#define DDR_invalid_opcode_int_enable_2_pos 12
#define DDR_invalid_opcode_int_enable_2_width 1
#define DDR_host_int_enable_2_addr 0x90
#define DDR_host_int_enable_2_pos 13
#define DDR_host_int_enable_2_width 1
#define DDR_adc_overflow_int_enable_2_addr 0x90
#define DDR_adc_overflow_int_enable_2_pos 14
#define DDR_adc_overflow_int_enable_2_width 1
#define DDR_adc_underflow_int_enable_2_addr 0x90
#define DDR_adc_underflow_int_enable_2_pos 15
#define DDR_adc_underflow_int_enable_2_width 1
#define DDR_adc_threshold_int_enable_2_addr 0x90
#define DDR_adc_threshold_int_enable_2_pos 16
#define DDR_adc_threshold_int_enable_2_width 1
#define DDR_AD6634_OVF_int_enable_2_addr 0x90
#define DDR_AD6634_OVF_int_enable_2_pos 17
#define DDR_AD6634_OVF_int_enable_2_width 1
#define DDR_sync_int_enable_2_addr 0x90
#define DDR_sync_int_enable_2_pos 18
#define DDR_sync_int_enable_2_width 4
#define DDR_gp_int_enable_2_addr 0x90
#define DDR_gp_int_enable_2_pos 22
#define DDR_gp_int_enable_2_width 8
#define DDR_fifo_overflow_clear_2_addr 0x94
#define DDR_fifo_overflow_clear_2_pos 0
#define DDR_fifo_overflow_clear_2_width 1
#define DDR_fifo_underflow_clear_2_addr 0x94
#define DDR_fifo_underflow_clear_2_pos 1
#define DDR_fifo_underflow_clear_2_width 1
#define DDR_fifo_finished_clear_2_addr 0x94
#define DDR_fifo_finished_clear_2_pos 2
#define DDR_fifo_finished_clear_2_width 1
#define DDR_fifo_started_clear_2_addr 0x94
#define DDR_fifo_started_clear_2_pos 3
#define DDR_fifo_started_clear_2_width 1
#define DDR_sw_int_clear_2_addr 0x94
#define DDR_sw_int_clear_2_pos 4
#define DDR_sw_int_clear_2_width 4
#define DDR_fail_int_clear_2_addr 0x94
#define DDR_fail_int_clear_2_pos 8
#define DDR_fail_int_clear_2_width 1
#define DDR_warn_int_clear_2_addr 0x94
#define DDR_warn_int_clear_2_pos 9
#define DDR_warn_int_clear_2_width 1
#define DDR_data_fifo_almost_empty_clear_2_addr 0x94
#define DDR_data_fifo_almost_empty_clear_2_pos 10
#define DDR_data_fifo_almost_empty_clear_2_width 1
#define DDR_instr_fifo_almost_full_clear_2_addr 0x94
#define DDR_instr_fifo_almost_full_clear_2_pos 11
#define DDR_instr_fifo_almost_full_clear_2_width 1
#define DDR_invalid_opcode_int_clear_2_addr 0x94
#define DDR_invalid_opcode_int_clear_2_pos 12
#define DDR_invalid_opcode_int_clear_2_width 1
#define DDR_host_int_clear_2_addr 0x94
#define DDR_host_int_clear_2_pos 13
#define DDR_host_int_clear_2_width 1
#define DDR_adc_overflow_int_clear_2_addr 0x94
#define DDR_adc_overflow_int_clear_2_pos 14
#define DDR_adc_overflow_int_clear_2_width 1
#define DDR_adc_underflow_int_clear_2_addr 0x94
#define DDR_adc_underflow_int_clear_2_pos 15
#define DDR_adc_underflow_int_clear_2_width 1
#define DDR_adc_threshold_int_clear_2_addr 0x94
#define DDR_adc_threshold_int_clear_2_pos 16
#define DDR_adc_threshold_int_clear_2_width 1
#define DDR_AD6634_OVF_int_clear_2_addr 0x94
#define DDR_AD6634_OVF_int_clear_2_pos 17
#define DDR_AD6634_OVF_int_clear_2_width 1
#define DDR_sync_int_clear_2_addr 0x94
#define DDR_sync_int_clear_2_pos 18
#define DDR_sync_int_clear_2_width 4
#define DDR_gp_int_clear_2_addr 0x94
#define DDR_gp_int_clear_2_pos 22
#define DDR_gp_int_clear_2_width 8
#define DDR_fifo_overflow_status_3_addr 0x98
#define DDR_fifo_overflow_status_3_pos 0
#define DDR_fifo_overflow_status_3_width 1
#define DDR_fifo_underflow_status_3_addr 0x98
#define DDR_fifo_underflow_status_3_pos 1
#define DDR_fifo_underflow_status_3_width 1
#define DDR_fifo_finished_status_3_addr 0x98
#define DDR_fifo_finished_status_3_pos 2
#define DDR_fifo_finished_status_3_width 1
#define DDR_fifo_started_status_3_addr 0x98
#define DDR_fifo_started_status_3_pos 3
#define DDR_fifo_started_status_3_width 1
#define DDR_sw_int_status_3_addr 0x98
#define DDR_sw_int_status_3_pos 4
#define DDR_sw_int_status_3_width 4
#define DDR_fail_int_status_3_addr 0x98
#define DDR_fail_int_status_3_pos 8
#define DDR_fail_int_status_3_width 1
#define DDR_warn_int_status_3_addr 0x98
#define DDR_warn_int_status_3_pos 9
#define DDR_warn_int_status_3_width 1
#define DDR_data_fifo_almost_empty_status_3_addr 0x98
#define DDR_data_fifo_almost_empty_status_3_pos 10
#define DDR_data_fifo_almost_empty_status_3_width 1
#define DDR_instr_fifo_almost_full_status_3_addr 0x98
#define DDR_instr_fifo_almost_full_status_3_pos 11
#define DDR_instr_fifo_almost_full_status_3_width 1
#define DDR_invalid_opcode_int_status_3_addr 0x98
#define DDR_invalid_opcode_int_status_3_pos 12
#define DDR_invalid_opcode_int_status_3_width 1
#define DDR_host_int_status_3_addr 0x98
#define DDR_host_int_status_3_pos 13
#define DDR_host_int_status_3_width 1
#define DDR_adc_overflow_int_status_3_addr 0x98
#define DDR_adc_overflow_int_status_3_pos 14
#define DDR_adc_overflow_int_status_3_width 1
#define DDR_adc_underflow_int_status_3_addr 0x98
#define DDR_adc_underflow_int_status_3_pos 15
#define DDR_adc_underflow_int_status_3_width 1
#define DDR_adc_threshold_int_status_3_addr 0x98
#define DDR_adc_threshold_int_status_3_pos 16
#define DDR_adc_threshold_int_status_3_width 1
#define DDR_AD6634_OVF_int_status_3_addr 0x98
#define DDR_AD6634_OVF_int_status_3_pos 17
#define DDR_AD6634_OVF_int_status_3_width 1
#define DDR_sync_int_status_3_addr 0x98
#define DDR_sync_int_status_3_pos 18
#define DDR_sync_int_status_3_width 4
#define DDR_gp_int_status_3_addr 0x98
#define DDR_gp_int_status_3_pos 22
#define DDR_gp_int_status_3_width 8
#define DDR_fifo_overflow_enable_3_addr 0x9c
#define DDR_fifo_overflow_enable_3_pos 0
#define DDR_fifo_overflow_enable_3_width 1
#define DDR_fifo_underflow_enable_3_addr 0x9c
#define DDR_fifo_underflow_enable_3_pos 1
#define DDR_fifo_underflow_enable_3_width 1
#define DDR_fifo_finished_enable_3_addr 0x9c
#define DDR_fifo_finished_enable_3_pos 2
#define DDR_fifo_finished_enable_3_width 1
#define DDR_fifo_started_enable_3_addr 0x9c
#define DDR_fifo_started_enable_3_pos 3
#define DDR_fifo_started_enable_3_width 1
#define DDR_sw_int_enable_3_addr 0x9c
#define DDR_sw_int_enable_3_pos 4
#define DDR_sw_int_enable_3_width 4
#define DDR_fail_int_enable_3_addr 0x9c
#define DDR_fail_int_enable_3_pos 8
#define DDR_fail_int_enable_3_width 1
#define DDR_warn_int_enable_3_addr 0x9c
#define DDR_warn_int_enable_3_pos 9
#define DDR_warn_int_enable_3_width 1
#define DDR_data_fifo_almost_empty_enable_3_addr 0x9c
#define DDR_data_fifo_almost_empty_enable_3_pos 10
#define DDR_data_fifo_almost_empty_enable_3_width 1
#define DDR_instr_fifo_almost_full_enable_3_addr 0x9c
#define DDR_instr_fifo_almost_full_enable_3_pos 11
#define DDR_instr_fifo_almost_full_enable_3_width 1
#define DDR_invalid_opcode_int_enable_3_addr 0x9c
#define DDR_invalid_opcode_int_enable_3_pos 12
#define DDR_invalid_opcode_int_enable_3_width 1
#define DDR_host_int_enable_3_addr 0x9c
#define DDR_host_int_enable_3_pos 13
#define DDR_host_int_enable_3_width 1
#define DDR_adc_overflow_int_enable_3_addr 0x9c
#define DDR_adc_overflow_int_enable_3_pos 14
#define DDR_adc_overflow_int_enable_3_width 1
#define DDR_adc_underflow_int_enable_3_addr 0x9c
#define DDR_adc_underflow_int_enable_3_pos 15
#define DDR_adc_underflow_int_enable_3_width 1
#define DDR_adc_threshold_int_enable_3_addr 0x9c
#define DDR_adc_threshold_int_enable_3_pos 16
#define DDR_adc_threshold_int_enable_3_width 1
#define DDR_AD6634_OVF_int_enable_3_addr 0x9c
#define DDR_AD6634_OVF_int_enable_3_pos 17
#define DDR_AD6634_OVF_int_enable_3_width 1
#define DDR_sync_int_enable_3_addr 0x9c
#define DDR_sync_int_enable_3_pos 18
#define DDR_sync_int_enable_3_width 4
#define DDR_gp_int_enable_3_addr 0x9c
#define DDR_gp_int_enable_3_pos 22
#define DDR_gp_int_enable_3_width 8
#define DDR_fifo_overflow_clear_3_addr 0xa0
#define DDR_fifo_overflow_clear_3_pos 0
#define DDR_fifo_overflow_clear_3_width 1
#define DDR_fifo_underflow_clear_3_addr 0xa0
#define DDR_fifo_underflow_clear_3_pos 1
#define DDR_fifo_underflow_clear_3_width 1
#define DDR_fifo_finished_clear_3_addr 0xa0
#define DDR_fifo_finished_clear_3_pos 2
#define DDR_fifo_finished_clear_3_width 1
#define DDR_fifo_started_clear_3_addr 0xa0
#define DDR_fifo_started_clear_3_pos 3
#define DDR_fifo_started_clear_3_width 1
#define DDR_sw_int_clear_3_addr 0xa0
#define DDR_sw_int_clear_3_pos 4
#define DDR_sw_int_clear_3_width 4
#define DDR_fail_int_clear_3_addr 0xa0
#define DDR_fail_int_clear_3_pos 8
#define DDR_fail_int_clear_3_width 1
#define DDR_warn_int_clear_3_addr 0xa0
#define DDR_warn_int_clear_3_pos 9
#define DDR_warn_int_clear_3_width 1
#define DDR_data_fifo_almost_empty_clear_3_addr 0xa0
#define DDR_data_fifo_almost_empty_clear_3_pos 10
#define DDR_data_fifo_almost_empty_clear_3_width 1
#define DDR_instr_fifo_almost_full_clear_3_addr 0xa0
#define DDR_instr_fifo_almost_full_clear_3_pos 11
#define DDR_instr_fifo_almost_full_clear_3_width 1
#define DDR_invalid_opcode_int_clear_3_addr 0xa0
#define DDR_invalid_opcode_int_clear_3_pos 12
#define DDR_invalid_opcode_int_clear_3_width 1
#define DDR_host_int_clear_3_addr 0xa0
#define DDR_host_int_clear_3_pos 13
#define DDR_host_int_clear_3_width 1
#define DDR_adc_overflow_int_clear_3_addr 0xa0
#define DDR_adc_overflow_int_clear_3_pos 14
#define DDR_adc_overflow_int_clear_3_width 1
#define DDR_adc_underflow_int_clear_3_addr 0xa0
#define DDR_adc_underflow_int_clear_3_pos 15
#define DDR_adc_underflow_int_clear_3_width 1
#define DDR_adc_threshold_int_clear_3_addr 0xa0
#define DDR_adc_threshold_int_clear_3_pos 16
#define DDR_adc_threshold_int_clear_3_width 1
#define DDR_AD6634_OVF_int_clear_3_addr 0xa0
#define DDR_AD6634_OVF_int_clear_3_pos 17
#define DDR_AD6634_OVF_int_clear_3_width 1
#define DDR_sync_int_clear_3_addr 0xa0
#define DDR_sync_int_clear_3_pos 18
#define DDR_sync_int_clear_3_width 4
#define DDR_gp_int_clear_3_addr 0xa0
#define DDR_gp_int_clear_3_pos 22
#define DDR_gp_int_clear_3_width 8
#define DDR_fifo_overflow_status_4_addr 0xa4
#define DDR_fifo_overflow_status_4_pos 0
#define DDR_fifo_overflow_status_4_width 1
#define DDR_fifo_underflow_status_4_addr 0xa4
#define DDR_fifo_underflow_status_4_pos 1
#define DDR_fifo_underflow_status_4_width 1
#define DDR_fifo_finished_status_4_addr 0xa4
#define DDR_fifo_finished_status_4_pos 2
#define DDR_fifo_finished_status_4_width 1
#define DDR_fifo_started_status_4_addr 0xa4
#define DDR_fifo_started_status_4_pos 3
#define DDR_fifo_started_status_4_width 1
#define DDR_sw_int_status_4_addr 0xa4
#define DDR_sw_int_status_4_pos 4
#define DDR_sw_int_status_4_width 4
#define DDR_fail_int_status_4_addr 0xa4
#define DDR_fail_int_status_4_pos 8
#define DDR_fail_int_status_4_width 1
#define DDR_warn_int_status_4_addr 0xa4
#define DDR_warn_int_status_4_pos 9
#define DDR_warn_int_status_4_width 1
#define DDR_data_fifo_almost_empty_status_4_addr 0xa4
#define DDR_data_fifo_almost_empty_status_4_pos 10
#define DDR_data_fifo_almost_empty_status_4_width 1
#define DDR_instr_fifo_almost_full_status_4_addr 0xa4
#define DDR_instr_fifo_almost_full_status_4_pos 11
#define DDR_instr_fifo_almost_full_status_4_width 1
#define DDR_invalid_opcode_int_status_4_addr 0xa4
#define DDR_invalid_opcode_int_status_4_pos 12
#define DDR_invalid_opcode_int_status_4_width 1
#define DDR_host_int_status_4_addr 0xa4
#define DDR_host_int_status_4_pos 13
#define DDR_host_int_status_4_width 1
#define DDR_adc_overflow_int_status_4_addr 0xa4
#define DDR_adc_overflow_int_status_4_pos 14
#define DDR_adc_overflow_int_status_4_width 1
#define DDR_adc_underflow_int_status_4_addr 0xa4
#define DDR_adc_underflow_int_status_4_pos 15
#define DDR_adc_underflow_int_status_4_width 1
#define DDR_adc_threshold_int_status_4_addr 0xa4
#define DDR_adc_threshold_int_status_4_pos 16
#define DDR_adc_threshold_int_status_4_width 1
#define DDR_AD6634_OVF_int_status_4_addr 0xa4
#define DDR_AD6634_OVF_int_status_4_pos 17
#define DDR_AD6634_OVF_int_status_4_width 1
#define DDR_sync_int_status_4_addr 0xa4
#define DDR_sync_int_status_4_pos 18
#define DDR_sync_int_status_4_width 4
#define DDR_gp_int_status_4_addr 0xa4
#define DDR_gp_int_status_4_pos 22
#define DDR_gp_int_status_4_width 8
#define DDR_fifo_overflow_enable_4_addr 0xa8
#define DDR_fifo_overflow_enable_4_pos 0
#define DDR_fifo_overflow_enable_4_width 1
#define DDR_fifo_underflow_enable_4_addr 0xa8
#define DDR_fifo_underflow_enable_4_pos 1
#define DDR_fifo_underflow_enable_4_width 1
#define DDR_fifo_finished_enable_4_addr 0xa8
#define DDR_fifo_finished_enable_4_pos 2
#define DDR_fifo_finished_enable_4_width 1
#define DDR_fifo_started_enable_4_addr 0xa8
#define DDR_fifo_started_enable_4_pos 3
#define DDR_fifo_started_enable_4_width 1
#define DDR_sw_int_enable_4_addr 0xa8
#define DDR_sw_int_enable_4_pos 4
#define DDR_sw_int_enable_4_width 4
#define DDR_fail_int_enable_4_addr 0xa8
#define DDR_fail_int_enable_4_pos 8
#define DDR_fail_int_enable_4_width 1
#define DDR_warn_int_enable_4_addr 0xa8
#define DDR_warn_int_enable_4_pos 9
#define DDR_warn_int_enable_4_width 1
#define DDR_data_fifo_almost_empty_enable_4_addr 0xa8
#define DDR_data_fifo_almost_empty_enable_4_pos 10
#define DDR_data_fifo_almost_empty_enable_4_width 1
#define DDR_instr_fifo_almost_full_enable_4_addr 0xa8
#define DDR_instr_fifo_almost_full_enable_4_pos 11
#define DDR_instr_fifo_almost_full_enable_4_width 1
#define DDR_invalid_opcode_int_enable_4_addr 0xa8
#define DDR_invalid_opcode_int_enable_4_pos 12
#define DDR_invalid_opcode_int_enable_4_width 1
#define DDR_host_int_enable_4_addr 0xa8
#define DDR_host_int_enable_4_pos 13
#define DDR_host_int_enable_4_width 1
#define DDR_adc_overflow_int_enable_4_addr 0xa8
#define DDR_adc_overflow_int_enable_4_pos 14
#define DDR_adc_overflow_int_enable_4_width 1
#define DDR_adc_underflow_int_enable_4_addr 0xa8
#define DDR_adc_underflow_int_enable_4_pos 15
#define DDR_adc_underflow_int_enable_4_width 1
#define DDR_adc_threshold_int_enable_4_addr 0xa8
#define DDR_adc_threshold_int_enable_4_pos 16
#define DDR_adc_threshold_int_enable_4_width 1
#define DDR_AD6634_OVF_int_enable_4_addr 0xa8
#define DDR_AD6634_OVF_int_enable_4_pos 17
#define DDR_AD6634_OVF_int_enable_4_width 1
#define DDR_sync_int_enable_4_addr 0xa8
#define DDR_sync_int_enable_4_pos 18
#define DDR_sync_int_enable_4_width 4
#define DDR_gp_int_enable_4_addr 0xa8
#define DDR_gp_int_enable_4_pos 22
#define DDR_gp_int_enable_4_width 8
#define DDR_fifo_overflow_clear_4_addr 0xac
#define DDR_fifo_overflow_clear_4_pos 0
#define DDR_fifo_overflow_clear_4_width 1
#define DDR_fifo_underflow_clear_4_addr 0xac
#define DDR_fifo_underflow_clear_4_pos 1
#define DDR_fifo_underflow_clear_4_width 1
#define DDR_fifo_finished_clear_4_addr 0xac
#define DDR_fifo_finished_clear_4_pos 2
#define DDR_fifo_finished_clear_4_width 1
#define DDR_fifo_started_clear_4_addr 0xac
#define DDR_fifo_started_clear_4_pos 3
#define DDR_fifo_started_clear_4_width 1
#define DDR_sw_int_clear_4_addr 0xac
#define DDR_sw_int_clear_4_pos 4
#define DDR_sw_int_clear_4_width 4
#define DDR_fail_int_clear_4_addr 0xac
#define DDR_fail_int_clear_4_pos 8
#define DDR_fail_int_clear_4_width 1
#define DDR_warn_int_clear_4_addr 0xac
#define DDR_warn_int_clear_4_pos 9
#define DDR_warn_int_clear_4_width 1
#define DDR_data_fifo_almost_empty_clear_4_addr 0xac
#define DDR_data_fifo_almost_empty_clear_4_pos 10
#define DDR_data_fifo_almost_empty_clear_4_width 1
#define DDR_instr_fifo_almost_full_clear_4_addr 0xac
#define DDR_instr_fifo_almost_full_clear_4_pos 11
#define DDR_instr_fifo_almost_full_clear_4_width 1
#define DDR_invalid_opcode_int_clear_4_addr 0xac
#define DDR_invalid_opcode_int_clear_4_pos 12
#define DDR_invalid_opcode_int_clear_4_width 1
#define DDR_host_int_clear_4_addr 0xac
#define DDR_host_int_clear_4_pos 13
#define DDR_host_int_clear_4_width 1
#define DDR_adc_overflow_int_clear_4_addr 0xac
#define DDR_adc_overflow_int_clear_4_pos 14
#define DDR_adc_overflow_int_clear_4_width 1
#define DDR_adc_underflow_int_clear_4_addr 0xac
#define DDR_adc_underflow_int_clear_4_pos 15
#define DDR_adc_underflow_int_clear_4_width 1
#define DDR_adc_threshold_int_clear_4_addr 0xac
#define DDR_adc_threshold_int_clear_4_pos 16
#define DDR_adc_threshold_int_clear_4_width 1
#define DDR_AD6634_OVF_int_clear_4_addr 0xac
#define DDR_AD6634_OVF_int_clear_4_pos 17
#define DDR_AD6634_OVF_int_clear_4_width 1
#define DDR_sync_int_clear_4_addr 0xac
#define DDR_sync_int_clear_4_pos 18
#define DDR_sync_int_clear_4_width 4
#define DDR_gp_int_clear_4_addr 0xac
#define DDR_gp_int_clear_4_pos 22
#define DDR_gp_int_clear_4_width 8
#define DDR_fifo_overflow_status_5_addr 0xb0
#define DDR_fifo_overflow_status_5_pos 0
#define DDR_fifo_overflow_status_5_width 1
#define DDR_fifo_underflow_status_5_addr 0xb0
#define DDR_fifo_underflow_status_5_pos 1
#define DDR_fifo_underflow_status_5_width 1
#define DDR_fifo_finished_status_5_addr 0xb0
#define DDR_fifo_finished_status_5_pos 2
#define DDR_fifo_finished_status_5_width 1
#define DDR_fifo_started_status_5_addr 0xb0
#define DDR_fifo_started_status_5_pos 3
#define DDR_fifo_started_status_5_width 1
#define DDR_sw_int_status_5_addr 0xb0
#define DDR_sw_int_status_5_pos 4
#define DDR_sw_int_status_5_width 4
#define DDR_fail_int_status_5_addr 0xb0
#define DDR_fail_int_status_5_pos 8
#define DDR_fail_int_status_5_width 1
#define DDR_warn_int_status_5_addr 0xb0
#define DDR_warn_int_status_5_pos 9
#define DDR_warn_int_status_5_width 1
#define DDR_data_fifo_almost_empty_status_5_addr 0xb0
#define DDR_data_fifo_almost_empty_status_5_pos 10
#define DDR_data_fifo_almost_empty_status_5_width 1
#define DDR_instr_fifo_almost_full_status_5_addr 0xb0
#define DDR_instr_fifo_almost_full_status_5_pos 11
#define DDR_instr_fifo_almost_full_status_5_width 1
#define DDR_invalid_opcode_int_status_5_addr 0xb0
#define DDR_invalid_opcode_int_status_5_pos 12
#define DDR_invalid_opcode_int_status_5_width 1
#define DDR_host_int_status_5_addr 0xb0
#define DDR_host_int_status_5_pos 13
#define DDR_host_int_status_5_width 1
#define DDR_adc_overflow_int_status_5_addr 0xb0
#define DDR_adc_overflow_int_status_5_pos 14
#define DDR_adc_overflow_int_status_5_width 1
#define DDR_adc_underflow_int_status_5_addr 0xb0
#define DDR_adc_underflow_int_status_5_pos 15
#define DDR_adc_underflow_int_status_5_width 1
#define DDR_adc_threshold_int_status_5_addr 0xb0
#define DDR_adc_threshold_int_status_5_pos 16
#define DDR_adc_threshold_int_status_5_width 1
#define DDR_AD6634_OVF_int_status_5_addr 0xb0
#define DDR_AD6634_OVF_int_status_5_pos 17
#define DDR_AD6634_OVF_int_status_5_width 1
#define DDR_sync_int_status_5_addr 0xb0
#define DDR_sync_int_status_5_pos 18
#define DDR_sync_int_status_5_width 4
#define DDR_gp_int_status_5_addr 0xb0
#define DDR_gp_int_status_5_pos 22
#define DDR_gp_int_status_5_width 8
#define DDR_fifo_overflow_enable_5_addr 0xb4
#define DDR_fifo_overflow_enable_5_pos 0
#define DDR_fifo_overflow_enable_5_width 1
#define DDR_fifo_underflow_enable_5_addr 0xb4
#define DDR_fifo_underflow_enable_5_pos 1
#define DDR_fifo_underflow_enable_5_width 1
#define DDR_fifo_finished_enable_5_addr 0xb4
#define DDR_fifo_finished_enable_5_pos 2
#define DDR_fifo_finished_enable_5_width 1
#define DDR_fifo_started_enable_5_addr 0xb4
#define DDR_fifo_started_enable_5_pos 3
#define DDR_fifo_started_enable_5_width 1
#define DDR_sw_int_enable_5_addr 0xb4
#define DDR_sw_int_enable_5_pos 4
#define DDR_sw_int_enable_5_width 4
#define DDR_fail_int_enable_5_addr 0xb4
#define DDR_fail_int_enable_5_pos 8
#define DDR_fail_int_enable_5_width 1
#define DDR_warn_int_enable_5_addr 0xb4
#define DDR_warn_int_enable_5_pos 9
#define DDR_warn_int_enable_5_width 1
#define DDR_data_fifo_almost_empty_enable_5_addr 0xb4
#define DDR_data_fifo_almost_empty_enable_5_pos 10
#define DDR_data_fifo_almost_empty_enable_5_width 1
#define DDR_instr_fifo_almost_full_enable_5_addr 0xb4
#define DDR_instr_fifo_almost_full_enable_5_pos 11
#define DDR_instr_fifo_almost_full_enable_5_width 1
#define DDR_invalid_opcode_int_enable_5_addr 0xb4
#define DDR_invalid_opcode_int_enable_5_pos 12
#define DDR_invalid_opcode_int_enable_5_width 1
#define DDR_host_int_enable_5_addr 0xb4
#define DDR_host_int_enable_5_pos 13
#define DDR_host_int_enable_5_width 1
#define DDR_adc_overflow_int_enable_5_addr 0xb4
#define DDR_adc_overflow_int_enable_5_pos 14
#define DDR_adc_overflow_int_enable_5_width 1
#define DDR_adc_underflow_int_enable_5_addr 0xb4
#define DDR_adc_underflow_int_enable_5_pos 15
#define DDR_adc_underflow_int_enable_5_width 1
#define DDR_adc_threshold_int_enable_5_addr 0xb4
#define DDR_adc_threshold_int_enable_5_pos 16
#define DDR_adc_threshold_int_enable_5_width 1
#define DDR_AD6634_OVF_int_enable_5_addr 0xb4
#define DDR_AD6634_OVF_int_enable_5_pos 17
#define DDR_AD6634_OVF_int_enable_5_width 1
#define DDR_sync_int_enable_5_addr 0xb4
#define DDR_sync_int_enable_5_pos 18
#define DDR_sync_int_enable_5_width 4
#define DDR_gp_int_enable_5_addr 0xb4
#define DDR_gp_int_enable_5_pos 22
#define DDR_gp_int_enable_5_width 8
#define DDR_fifo_overflow_clear_5_addr 0xb8
#define DDR_fifo_overflow_clear_5_pos 0
#define DDR_fifo_overflow_clear_5_width 1
#define DDR_fifo_underflow_clear_5_addr 0xb8
#define DDR_fifo_underflow_clear_5_pos 1
#define DDR_fifo_underflow_clear_5_width 1
#define DDR_fifo_finished_clear_5_addr 0xb8
#define DDR_fifo_finished_clear_5_pos 2
#define DDR_fifo_finished_clear_5_width 1
#define DDR_fifo_started_clear_5_addr 0xb8
#define DDR_fifo_started_clear_5_pos 3
#define DDR_fifo_started_clear_5_width 1
#define DDR_sw_int_clear_5_addr 0xb8
#define DDR_sw_int_clear_5_pos 4
#define DDR_sw_int_clear_5_width 4
#define DDR_fail_int_clear_5_addr 0xb8
#define DDR_fail_int_clear_5_pos 8
#define DDR_fail_int_clear_5_width 1
#define DDR_warn_int_clear_5_addr 0xb8
#define DDR_warn_int_clear_5_pos 9
#define DDR_warn_int_clear_5_width 1
#define DDR_data_fifo_almost_empty_clear_5_addr 0xb8
#define DDR_data_fifo_almost_empty_clear_5_pos 10
#define DDR_data_fifo_almost_empty_clear_5_width 1
#define DDR_instr_fifo_almost_full_clear_5_addr 0xb8
#define DDR_instr_fifo_almost_full_clear_5_pos 11
#define DDR_instr_fifo_almost_full_clear_5_width 1
#define DDR_invalid_opcode_int_clear_5_addr 0xb8
#define DDR_invalid_opcode_int_clear_5_pos 12
#define DDR_invalid_opcode_int_clear_5_width 1
#define DDR_host_int_clear_5_addr 0xb8
#define DDR_host_int_clear_5_pos 13
#define DDR_host_int_clear_5_width 1
#define DDR_adc_overflow_int_clear_5_addr 0xb8
#define DDR_adc_overflow_int_clear_5_pos 14
#define DDR_adc_overflow_int_clear_5_width 1
#define DDR_adc_underflow_int_clear_5_addr 0xb8
#define DDR_adc_underflow_int_clear_5_pos 15
#define DDR_adc_underflow_int_clear_5_width 1
#define DDR_adc_threshold_int_clear_5_addr 0xb8
#define DDR_adc_threshold_int_clear_5_pos 16
#define DDR_adc_threshold_int_clear_5_width 1
#define DDR_AD6634_OVF_int_clear_5_addr 0xb8
#define DDR_AD6634_OVF_int_clear_5_pos 17
#define DDR_AD6634_OVF_int_clear_5_width 1
#define DDR_sync_int_clear_5_addr 0xb8
#define DDR_sync_int_clear_5_pos 18
#define DDR_sync_int_clear_5_width 4
#define DDR_gp_int_clear_5_addr 0xb8
#define DDR_gp_int_clear_5_pos 22
#define DDR_gp_int_clear_5_width 8
#define DDR_sw_gates_addr 0xbc
#define DDR_sw_gates_pos 0
#define DDR_sw_gates_width 12
#define DDR_sw_gain_addr 0xc0
#define DDR_sw_gain_pos 0
#define DDR_sw_gain_width 5
#define DDR_sw_aux_addr 0xc4
#define DDR_sw_aux_pos 0
#define DDR_sw_aux_width 12
#define DDR_sw_aux_reset_addr 0xc8
#define DDR_sw_aux_reset_pos 0
#define DDR_sw_aux_reset_width 1
#define DDR_sw_aux_strobe_addr 0xcc
#define DDR_sw_aux_strobe_pos 0
#define DDR_sw_aux_strobe_width 1
#define DDR_fifo_output_select_addr 0xd0
#define DDR_fifo_output_select_pos 0
#define DDR_fifo_output_select_width 1
#define DDR_fifo_gates_addr 0xd4
#define DDR_fifo_gates_pos 0
#define DDR_fifo_gates_width 12
#define DDR_fifo_gain_addr 0xd8
#define DDR_fifo_gain_pos 0
#define DDR_fifo_gain_width 5
#define DDR_fifo_aux_addr 0xdc
#define DDR_fifo_aux_pos 0
#define DDR_fifo_aux_width 12
#define DDR_aux_read_addr 0xe0
#define DDR_aux_read_pos 0
#define DDR_aux_read_width 8
#define DDR_holding_duration_addr 0xe4
#define DDR_holding_duration_pos 0
#define DDR_holding_duration_width 26
#define DDR_holding_gates_addr 0xe8
#define DDR_holding_gates_pos 0
#define DDR_holding_gates_width 12
#define DDR_holding_gain_addr 0xec
#define DDR_holding_gain_pos 0
#define DDR_holding_gain_width 5
#define DDR_fifo_instruction_addr 0xf0
#define DDR_fifo_instruction_pos 0
#define DDR_fifo_instruction_width 32
#define DDR_C67_ResetN_addr 0xf4
#define DDR_C67_ResetN_pos 0
#define DDR_C67_ResetN_width 1
#define DDR_c67_configuration_addr 0xf8
#define DDR_c67_configuration_pos 0
#define DDR_c67_configuration_width 16
#define DDR_hpi_base_address0_addr 0xfc
#define DDR_hpi_base_address0_pos 0
#define DDR_hpi_base_address0_width 32
#define DDR_hpi_base_address1_addr 0x100
#define DDR_hpi_base_address1_pos 0
#define DDR_hpi_base_address1_width 32
#define DDR_hpi_base_address2_addr 0x104
#define DDR_hpi_base_address2_pos 0
#define DDR_hpi_base_address2_width 32
#define DDR_hpi_auto_increment_addr 0x108
#define DDR_hpi_auto_increment_pos 0
#define DDR_hpi_auto_increment_width 1
#define DDR_hpi_control_access_addr 0x10c
#define DDR_hpi_control_access_pos 0
#define DDR_hpi_control_access_width 1
#define DDR_c67_hpi_read_strobe_low_count_addr 0x110
#define DDR_c67_hpi_read_strobe_low_count_pos 0
#define DDR_c67_hpi_read_strobe_low_count_width 8
#define DDR_c67_hpi_read_strobe_high_count_addr 0x110
#define DDR_c67_hpi_read_strobe_high_count_pos 8
#define DDR_c67_hpi_read_strobe_high_count_width 8
#define DDR_c67_hpi_write_strobe_low_count_addr 0x110
#define DDR_c67_hpi_write_strobe_low_count_pos 16
#define DDR_c67_hpi_write_strobe_low_count_width 8
#define DDR_c67_hpi_write_strobe_high_count_addr 0x110
#define DDR_c67_hpi_write_strobe_high_count_pos 24
#define DDR_c67_hpi_write_strobe_high_count_width 8
#define DDR_c67_hpi_retry_limit_addr 0x114
#define DDR_c67_hpi_retry_limit_pos 0
#define DDR_c67_hpi_retry_limit_width 16
#define DDR_c67_hpi_busy_addr 0x118
#define DDR_c67_hpi_busy_pos 0
#define DDR_c67_hpi_busy_width 1
#define DDR_c67if_enable_addr 0x11c
#define DDR_c67if_enable_pos 0
#define DDR_c67if_enable_width 1
#define DDR_c67if_finished_addr 0x11c
#define DDR_c67if_finished_pos 1
#define DDR_c67if_finished_width 1
#define DDR_c67_emif_state_addr 0x120
#define DDR_c67_emif_state_pos 0
#define DDR_c67_emif_state_width 9
#define DDR_eclkout_rst_addr 0x124
#define DDR_eclkout_rst_pos 0
#define DDR_eclkout_rst_width 1
#define DDR_eclkout_psincdec_addr 0x124
#define DDR_eclkout_psincdec_pos 1
#define DDR_eclkout_psincdec_width 1
#define DDR_eclkout_psen_addr 0x124
#define DDR_eclkout_psen_pos 2
#define DDR_eclkout_psen_width 1
#define DDR_eclkout_psclk_addr 0x124
#define DDR_eclkout_psclk_pos 3
#define DDR_eclkout_psclk_width 1
#define DDR_eclkout_locked_addr 0x128
#define DDR_eclkout_locked_pos 0
#define DDR_eclkout_locked_width 1
#define DDR_eclkout_psdone_addr 0x128
#define DDR_eclkout_psdone_pos 1
#define DDR_eclkout_psdone_width 1
#define DDR_eclkout_status_addr 0x128
#define DDR_eclkout_status_pos 2
#define DDR_eclkout_status_width 3
#define DDR_eclkout_resetting_addr 0x128
#define DDR_eclkout_resetting_pos 5
#define DDR_eclkout_resetting_width 1
#define DDR_eclkout_lost_lock_addr 0x128
#define DDR_eclkout_lost_lock_pos 6
#define DDR_eclkout_lost_lock_width 1
#define DDR_ebc_timeout_limit_addr 0x12c
#define DDR_ebc_timeout_limit_pos 0
#define DDR_ebc_timeout_limit_width 11
#define DDR_adc_collect_data_addr 0x130
#define DDR_adc_collect_data_pos 0
#define DDR_adc_collect_data_width 1
#define DDR_adc_arm_fifo_start_addr 0x130
#define DDR_adc_arm_fifo_start_pos 1
#define DDR_adc_arm_fifo_start_width 1
#define DDR_adc_arm_fifo_stop_addr 0x130
#define DDR_adc_arm_fifo_stop_pos 2
#define DDR_adc_arm_fifo_stop_width 1
#define DDR_adc_debug_mode_addr 0x130
#define DDR_adc_debug_mode_pos 3
#define DDR_adc_debug_mode_width 1
#define DDR_adc_trip_point_addr 0x134
#define DDR_adc_trip_point_pos 0
#define DDR_adc_trip_point_width 13
#define DDR_adc_fifo_clear_addr 0x134
#define DDR_adc_fifo_clear_pos 13
#define DDR_adc_fifo_clear_width 1
#define DDR_adc_collect_data_delay_addr 0x138
#define DDR_adc_collect_data_delay_pos 0
#define DDR_adc_collect_data_delay_width 8
#define DDR_adc_count_addr 0x13c
#define DDR_adc_count_pos 0
#define DDR_adc_count_width 13
#define DDR_adc_read_pointer_addr 0x140
#define DDR_adc_read_pointer_pos 0
#define DDR_adc_read_pointer_width 13
#define DDR_AD6634_DIT_OFF_addr 0x144
#define DDR_AD6634_DIT_OFF_pos 0
#define DDR_AD6634_DIT_OFF_width 1
#define DDR_AD6634_RST_addr 0x148
#define DDR_AD6634_RST_pos 0
#define DDR_AD6634_RST_width 1
#define DDR_ad6634_sync_phase_addr 0x14c
#define DDR_ad6634_sync_phase_pos 0
#define DDR_ad6634_sync_phase_width 8
#define DDR_la_trigger_select_addr 0x150
#define DDR_la_trigger_select_pos 0
#define DDR_la_trigger_select_width 8
#define DDR_la_trigger_polarity_addr 0x150
#define DDR_la_trigger_polarity_pos 8
#define DDR_la_trigger_polarity_width 2
#define DDR_la_trigger_arm_addr 0x150
#define DDR_la_trigger_arm_pos 10
#define DDR_la_trigger_arm_width 1
#define DDR_la_force_trigger_addr 0x150
#define DDR_la_force_trigger_pos 11
#define DDR_la_force_trigger_width 1
#define DDR_la_trigger_leadin_addr 0x150
#define DDR_la_trigger_leadin_pos 12
#define DDR_la_trigger_leadin_width 10
#define DDR_la_sample_divisor_addr 0x150
#define DDR_la_sample_divisor_pos 22
#define DDR_la_sample_divisor_width 8
#define DDR_la_start_data_addr 0x154
#define DDR_la_start_data_pos 0
#define DDR_la_start_data_width 10
#define DDR_la_triggered_addr 0x154
#define DDR_la_triggered_pos 10
#define DDR_la_triggered_width 1
#define DDR_la_checksum_addr 0x158
#define DDR_la_checksum_pos 0
#define DDR_la_checksum_width 16
#define DDR_la_address_addr 0x15c
#define DDR_la_address_pos 0
#define DDR_la_address_width 13
#define DDR_la_data_addr 0x160
#define DDR_la_data_pos 0
#define DDR_la_data_width 32
#endif
