//@copy-c-declaration /*
//@copy-c-declaration *
//@copy-c-declaration * Varian,Inc. All Rights Reserved.
//@copy-c-declaration * This software contains proprietary and confidential
//@copy-c-declaration * information of Varian, Inc. and its contributors.
//@copy-c-declaration * Use, disclosure and reproduction is prohibited without
//@copy-c-declaration * prior consent.
//@copy-c-declaration */
//@copy-c-declaration /*
//@copy-c-declaration *  Author: Greg Brissey  4/28/2004
//@copy-c-declaration */

//@copy-c-declaration #include "NDDS_Obj.h"


//@copy-c-declaration /* topic name form */
//@copy-c-declaration /* topic names form: ?/lock1/cmdstrm, lock1/?/cmdstrm */

const string FIDCT_PUB_STAT_TOPIC_FORMAT_STR = "%s/fid/status";
const string FIDCT_SUB_PATTERN_TOPIC_STR = "*/fid/status";
const string FIDCT_STAT_M21TOPIC_STR = "fid/status";

struct FidCt_Stat {
        long key; //@key
        long FidCt;
        long Ct;
};

//@copy-c-declaration 
//@copy-c-declaration #ifdef __cplusplus
//@copy-c-declaration     extern "C" {
//@copy-c-declaration #endif
//@copy-c-declaration 
//@copy-c-declaration extern void getFidCt_StatInfo(NDDS_OBJ *pObj);
//@copy-c-declaration 
//@copy-c-declaration #ifdef __cplusplus
//@copy-c-declaration }
//@copy-c-declaration #endif

// //@copy-c  /* Direct Code from Codes_Downld.x */
// //@copy-c void getFidCt_StatInfo(NDDS_OBJ *pObj)
// //@copy-c {
// //@copy-c     strcpy(pObj->dataTypeName,FidCt_StatNDDSType);
// //@copy-c 
// //@copy-c     pObj->TypeRegisterFunc = FidCt_StatNddsRegister;
// //@copy-c     pObj->TypeAllocFunc = (DataTypeAllocate) FidCt_StatAllocate;
// //@copy-c     pObj->TypeSizeFunc = FidCt_StatMaxSize;
// //@copy-c }

