/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
#ifndef GRADIENT_H
#define GRADIENT_H
#ifndef get_field
  #define get_field(fpga,field) \
    ((*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))>> \
    fpga##_##field##_pos) & (((fpga##_##field##_width<32) ? (1<<fpga##_##field##_width):0)-1))
#endif
#ifndef set_field
  #define set_field(fpga,field,value) \
    ((*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))) = \
    (*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))) & \
    ~((((fpga##_##field##_width<32)?(1<<fpga##_##field##_width):0)-1)<<fpga##_##field##_pos) | \
    ((value&(((fpga##_##field##_width<32)?(1<<fpga##_##field##_width):0)-1))<<fpga##_##field##_pos))
#endif
#define GRADIENT_CHECKSUM 41571
#define GRADIENT_ID 0x0
#define GRADIENT_LED 0x4
#define GRADIENT_BoardAddress 0x8
#define GRADIENT_InterfaceType 0xc
#define GRADIENT_Failure 0x10
#define GRADIENT_DMARequest 0x14
#define GRADIENT_SCLKClockControl 0x18
#define GRADIENT_SCLKClockStatus 0x1c
#define GRADIENT_FIFOControl 0x20
#define GRADIENT_FIFOStatus 0x24
#define GRADIENT_InstructionFIFOHighThreshold 0x28
#define GRADIENT_InstructionFIFOLowThreshold 0x2c
#define GRADIENT_InstructionFIFOCount 0x30
#define GRADIENT_DataFIFOCount 0x34
#define GRADIENT_ClearCumulativeDuration 0x38
#define GRADIENT_CumulativeDurationLow 0x3c
#define GRADIENT_CumulativeDurationHigh 0x40
#define GRADIENT_J1COutput 0x44
#define GRADIENT_J1CEnable 0x48
#define GRADIENT_J1CInput 0x4c
#define GRADIENT_J2COutput 0x50
#define GRADIENT_J2CEnable 0x54
#define GRADIENT_J2CInput 0x58
#define GRADIENT_InterruptStatus 0x5c
#define GRADIENT_InterruptEnable 0x60
#define GRADIENT_InterruptClear 0x64
#define GRADIENT_DelayFifoEmpty 0x68
#define GRADIENT_DelayFifoFull 0x6c
#define GRADIENT_XDelayFifoCount 0x70
#define GRADIENT_YDelayFifoCount 0x74
#define GRADIENT_ZDelayFifoCount 0x78
#define GRADIENT_B0DelayFifoCount 0x7c
#define GRADIENT_InstructionFifoCountTotal 0x80
#define GRADIENT_ClearInstructionFifoCountTotal 0x84
#define GRADIENT_InvalidOpcode 0x88
#define GRADIENT_XSlewLimit 0x8c
#define GRADIENT_YSlewLimit 0x90
#define GRADIENT_ZSlewLimit 0x94
#define GRADIENT_B0SlewLimit 0x98
#define GRADIENT_SlewLimitDisable 0x9c
#define GRADIENT_ClearDelayBuffer 0xa0
#define GRADIENT_CoarseXDelay 0xa4
#define GRADIENT_CoarseYDelay 0xa8
#define GRADIENT_CoarseZDelay 0xac
#define GRADIENT_CoarseB0Delay 0xb0
#define GRADIENT_FineXDelay 0xb4
#define GRADIENT_FineYDelay 0xb8
#define GRADIENT_FineZDelay 0xbc
#define GRADIENT_FineB0Delay 0xc0
#define GRADIENT_GradReset 0xc4
#define GRADIENT_GradResetDone 0xc8
#define GRADIENT_GradFault 0xcc
#define GRADIENT_GradientAmpType 0xd0
#define GRADIENT_SPIConfig 0xd4
#define GRADIENT_SPIDataOut 0xd8
#define GRADIENT_SPIDataIn 0xdc
#define GRADIENT_SPIStart 0xe0
#define GRADIENT_SPIChipSelect 0xe4
#define GRADIENT_SPIBusy 0xe8
#define GRADIENT_GradientAmpBusy 0xec
#define GRADIENT_GradientECCBusy 0xf0
#define GRADIENT_SoftwareXAmp 0xf4
#define GRADIENT_SoftwareYAmp 0xf8
#define GRADIENT_SoftwareZAmp 0xfc
#define GRADIENT_SoftwareB0Amp 0x100
#define GRADIENT_SoftwareXAmpUpdated 0x104
#define GRADIENT_SoftwareYAmpUpdated 0x108
#define GRADIENT_SoftwareZAmpUpdated 0x10c
#define GRADIENT_SoftwareB0AmpUpdated 0x110
#define GRADIENT_SoftwareXEcc 0x114
#define GRADIENT_SoftwareYEcc 0x118
#define GRADIENT_SoftwareZEcc 0x11c
#define GRADIENT_SoftwareB0Ecc 0x120
#define GRADIENT_SoftwareXEccUpdated 0x124
#define GRADIENT_SoftwareYEccUpdated 0x128
#define GRADIENT_SoftwareZEccUpdated 0x12c
#define GRADIENT_SoftwareB0EccUpdated 0x130
#define GRADIENT_SoftwareShim 0x134
#define GRADIENT_SoftwareShimUpdated 0x138
#define GRADIENT_SoftwareGates 0x13c
#define GRADIENT_SoftwareUser 0x140
#define GRADIENT_FIFOOutputSelect 0x144
#define GRADIENT_SoftwareUpdate 0x148
#define GRADIENT_FIFOXAmp 0x14c
#define GRADIENT_FIFOYAmp 0x150
#define GRADIENT_FIFOZAmp 0x154
#define GRADIENT_FIFOB0Amp 0x158
#define GRADIENT_FIFOXAmpUpdated 0x15c
#define GRADIENT_FIFOYAmpUpdated 0x160
#define GRADIENT_FIFOZAmpUpdated 0x164
#define GRADIENT_FIFOB0AmpUpdated 0x168
#define GRADIENT_FIFOECCCalcSelect 0x16c
#define GRADIENT_FIFOXEcc 0x170
#define GRADIENT_FIFOYEcc 0x174
#define GRADIENT_FIFOZEcc 0x178
#define GRADIENT_FIFOB0Ecc 0x17c
#define GRADIENT_FIFOXEccUpdated 0x180
#define GRADIENT_FIFOYEccUpdated 0x184
#define GRADIENT_FIFOZEccUpdated 0x188
#define GRADIENT_FIFOB0EccUpdated 0x18c
#define GRADIENT_FIFOShim 0x190
#define GRADIENT_FIFOShimUpdated 0x194
#define GRADIENT_FIFOGates 0x198
#define GRADIENT_FIFOUser 0x19c
#define GRADIENT_Duration 0x1a0
#define GRADIENT_DurationCount 0x1a4
#define GRADIENT_XAmp 0x1a8
#define GRADIENT_XAmpIncrement 0x1ac
#define GRADIENT_XAmpCount 0x1b0
#define GRADIENT_XAmpClear 0x1b4
#define GRADIENT_YAmp 0x1b8
#define GRADIENT_YAmpIncrement 0x1bc
#define GRADIENT_YAmpCount 0x1c0
#define GRADIENT_YAmpClear 0x1c4
#define GRADIENT_ZAmp 0x1c8
#define GRADIENT_ZAmpIncrement 0x1cc
#define GRADIENT_ZAmpCount 0x1d0
#define GRADIENT_ZAmpClear 0x1d4
#define GRADIENT_B0Amp 0x1d8
#define GRADIENT_B0AmpIncrement 0x1dc
#define GRADIENT_B0AmpCount 0x1e0
#define GRADIENT_B0AmpClear 0x1e4
#define GRADIENT_XAmpScale 0x1e8
#define GRADIENT_XAmpScaleIncrement 0x1ec
#define GRADIENT_XAmpScaleCount 0x1f0
#define GRADIENT_XAmpScaleClear 0x1f4
#define GRADIENT_YAmpScale 0x1f8
#define GRADIENT_YAmpScaleIncrement 0x1fc
#define GRADIENT_YAmpScaleCount 0x200
#define GRADIENT_YAmpScaleClear 0x204
#define GRADIENT_ZAmpScale 0x208
#define GRADIENT_ZAmpScaleIncrement 0x20c
#define GRADIENT_ZAmpScaleCount 0x210
#define GRADIENT_ZAmpScaleClear 0x214
#define GRADIENT_B0AmpScale 0x218
#define GRADIENT_B0AmpScaleIncrement 0x21c
#define GRADIENT_B0AmpScaleCount 0x220
#define GRADIENT_B0AmpScaleClear 0x224
#define GRADIENT_XAmpUpdated 0x228
#define GRADIENT_YAmpUpdated 0x22c
#define GRADIENT_ZAmpUpdated 0x230
#define GRADIENT_B0AmpUpdated 0x234
#define GRADIENT_XEcc 0x238
#define GRADIENT_YEcc 0x23c
#define GRADIENT_ZEcc 0x240
#define GRADIENT_B0Ecc 0x244
#define GRADIENT_XEccUpdated 0x248
#define GRADIENT_YEccUpdated 0x24c
#define GRADIENT_ZEccUpdated 0x250
#define GRADIENT_B0EccUpdated 0x254
#define GRADIENT_Shim 0x258
#define GRADIENT_ShimUpdated 0x25c
#define GRADIENT_Gates 0x260
#define GRADIENT_User 0x264
#define GRADIENT_FIFOInstructionWrite 0x268
#define GRADIENT_LogicAnalyzerConfig 0x26c
#define GRADIENT_LogicAnalyzerStatus 0x270
#define GRADIENT_LogicAnalyzerChecksum 0x274
#define GRADIENT_LogicAnalyzerAddress 0x278
#define GRADIENT_LogicAnalyzerSampleData 0x27c
#define GRADIENT_ECCAmp 0x300
#define GRADIENT_ECCTimeConstant 0x400
#define GRADIENT_ID_addr 0x0
#define GRADIENT_ID_pos 0
#define GRADIENT_ID_width 4
#define GRADIENT_revision_addr 0x0
#define GRADIENT_revision_pos 4
#define GRADIENT_revision_width 4
#define GRADIENT_checksum_addr 0x0
#define GRADIENT_checksum_pos 8
#define GRADIENT_checksum_width 16
#define GRADIENT_led_addr 0x4
#define GRADIENT_led_pos 0
#define GRADIENT_led_width 6
#define GRADIENT_bd_addr_addr 0x8
#define GRADIENT_bd_addr_pos 0
#define GRADIENT_bd_addr_width 5
#define GRADIENT_type_addr_addr 0xc
#define GRADIENT_type_addr_pos 0
#define GRADIENT_type_addr_width 3
#define GRADIENT_sw_failure_addr 0x10
#define GRADIENT_sw_failure_pos 0
#define GRADIENT_sw_failure_width 1
#define GRADIENT_sw_warning_addr 0x10
#define GRADIENT_sw_warning_pos 1
#define GRADIENT_sw_warning_width 1
#define GRADIENT_dma_request_addr 0x14
#define GRADIENT_dma_request_pos 0
#define GRADIENT_dma_request_width 1
#define GRADIENT_sclk_rst_addr 0x18
#define GRADIENT_sclk_rst_pos 0
#define GRADIENT_sclk_rst_width 1
#define GRADIENT_sclk_psincdec_addr 0x18
#define GRADIENT_sclk_psincdec_pos 1
#define GRADIENT_sclk_psincdec_width 1
#define GRADIENT_sclk_psen_addr 0x18
#define GRADIENT_sclk_psen_pos 2
#define GRADIENT_sclk_psen_width 1
#define GRADIENT_sclk_psclk_addr 0x18
#define GRADIENT_sclk_psclk_pos 3
#define GRADIENT_sclk_psclk_width 1
#define GRADIENT_sclk_locked_addr 0x1c
#define GRADIENT_sclk_locked_pos 0
#define GRADIENT_sclk_locked_width 1
#define GRADIENT_sclk_psdone_addr 0x1c
#define GRADIENT_sclk_psdone_pos 1
#define GRADIENT_sclk_psdone_width 1
#define GRADIENT_sclk_status_addr 0x1c
#define GRADIENT_sclk_status_pos 2
#define GRADIENT_sclk_status_width 3
#define GRADIENT_fifo_start_addr 0x20
#define GRADIENT_fifo_start_pos 0
#define GRADIENT_fifo_start_width 1
#define GRADIENT_fifo_sync_start_addr 0x20
#define GRADIENT_fifo_sync_start_pos 1
#define GRADIENT_fifo_sync_start_width 1
#define GRADIENT_fifo_reset_addr 0x20
#define GRADIENT_fifo_reset_pos 2
#define GRADIENT_fifo_reset_width 1
#define GRADIENT_fifo_active_addr 0x24
#define GRADIENT_fifo_active_pos 0
#define GRADIENT_fifo_active_width 1
#define GRADIENT_instruction_fifo_high_threshold_addr 0x28
#define GRADIENT_instruction_fifo_high_threshold_pos 0
#define GRADIENT_instruction_fifo_high_threshold_width 10
#define GRADIENT_instruction_fifo_low_threshold_addr 0x2c
#define GRADIENT_instruction_fifo_low_threshold_pos 0
#define GRADIENT_instruction_fifo_low_threshold_width 10
#define GRADIENT_instruction_fifo_count_addr 0x30
#define GRADIENT_instruction_fifo_count_pos 0
#define GRADIENT_instruction_fifo_count_width 10
#define GRADIENT_data_fifo_count_addr 0x34
#define GRADIENT_data_fifo_count_pos 0
#define GRADIENT_data_fifo_count_width 9
#define GRADIENT_clear_cumulative_duration_addr 0x38
#define GRADIENT_clear_cumulative_duration_pos 0
#define GRADIENT_clear_cumulative_duration_width 1
#define GRADIENT_cumulative_duration_low_addr 0x3c
#define GRADIENT_cumulative_duration_low_pos 0
#define GRADIENT_cumulative_duration_low_width 32
#define GRADIENT_cumulative_duration_high_addr 0x40
#define GRADIENT_cumulative_duration_high_pos 0
#define GRADIENT_cumulative_duration_high_width 32
#define GRADIENT_J1_C_out_addr 0x44
#define GRADIENT_J1_C_out_pos 0
#define GRADIENT_J1_C_out_width 32
#define GRADIENT_J1_C_en_addr 0x48
#define GRADIENT_J1_C_en_pos 0
#define GRADIENT_J1_C_en_width 32
#define GRADIENT_J1_C_addr 0x4c
#define GRADIENT_J1_C_pos 0
#define GRADIENT_J1_C_width 32
#define GRADIENT_J2_C_out_addr 0x50
#define GRADIENT_J2_C_out_pos 0
#define GRADIENT_J2_C_out_width 32
#define GRADIENT_J2_C_en_addr 0x54
#define GRADIENT_J2_C_en_pos 0
#define GRADIENT_J2_C_en_width 32
#define GRADIENT_J2_C_addr 0x58
#define GRADIENT_J2_C_pos 0
#define GRADIENT_J2_C_width 32
#define GRADIENT_fifo_overflow_status_addr 0x5c
#define GRADIENT_fifo_overflow_status_pos 0
#define GRADIENT_fifo_overflow_status_width 1
#define GRADIENT_fifo_underflow_status_addr 0x5c
#define GRADIENT_fifo_underflow_status_pos 1
#define GRADIENT_fifo_underflow_status_width 1
#define GRADIENT_fifo_finished_status_addr 0x5c
#define GRADIENT_fifo_finished_status_pos 2
#define GRADIENT_fifo_finished_status_width 1
#define GRADIENT_fifo_started_status_addr 0x5c
#define GRADIENT_fifo_started_status_pos 3
#define GRADIENT_fifo_started_status_width 1
#define GRADIENT_sw_int_status_addr 0x5c
#define GRADIENT_sw_int_status_pos 4
#define GRADIENT_sw_int_status_width 4
#define GRADIENT_fail_int_status_addr 0x5c
#define GRADIENT_fail_int_status_pos 8
#define GRADIENT_fail_int_status_width 1
#define GRADIENT_warn_int_status_addr 0x5c
#define GRADIENT_warn_int_status_pos 9
#define GRADIENT_warn_int_status_width 1
#define GRADIENT_data_fifo_almost_empty_status_addr 0x5c
#define GRADIENT_data_fifo_almost_empty_status_pos 10
#define GRADIENT_data_fifo_almost_empty_status_width 1
#define GRADIENT_instr_fifo_almost_full_status_addr 0x5c
#define GRADIENT_instr_fifo_almost_full_status_pos 11
#define GRADIENT_instr_fifo_almost_full_status_width 1
#define GRADIENT_invalid_opcode_int_status_addr 0x5c
#define GRADIENT_invalid_opcode_int_status_pos 12
#define GRADIENT_invalid_opcode_int_status_width 1
#define GRADIENT_spi_failed_busy_status_addr 0x5c
#define GRADIENT_spi_failed_busy_status_pos 13
#define GRADIENT_spi_failed_busy_status_width 1
#define GRADIENT_slew_limit_exceeded_status_addr 0x5c
#define GRADIENT_slew_limit_exceeded_status_pos 14
#define GRADIENT_slew_limit_exceeded_status_width 4
#define GRADIENT_grad_isi_fault_status_addr 0x5c
#define GRADIENT_grad_isi_fault_status_pos 18
#define GRADIENT_grad_isi_fault_status_width 1
#define GRADIENT_fifo_overflow_enable_addr 0x60
#define GRADIENT_fifo_overflow_enable_pos 0
#define GRADIENT_fifo_overflow_enable_width 1
#define GRADIENT_fifo_underflow_enable_addr 0x60
#define GRADIENT_fifo_underflow_enable_pos 1
#define GRADIENT_fifo_underflow_enable_width 1
#define GRADIENT_fifo_finished_enable_addr 0x60
#define GRADIENT_fifo_finished_enable_pos 2
#define GRADIENT_fifo_finished_enable_width 1
#define GRADIENT_fifo_started_enable_addr 0x60
#define GRADIENT_fifo_started_enable_pos 3
#define GRADIENT_fifo_started_enable_width 1
#define GRADIENT_sw_int_enable_addr 0x60
#define GRADIENT_sw_int_enable_pos 4
#define GRADIENT_sw_int_enable_width 4
#define GRADIENT_fail_int_enable_addr 0x60
#define GRADIENT_fail_int_enable_pos 8
#define GRADIENT_fail_int_enable_width 1
#define GRADIENT_warn_int_enable_addr 0x60
#define GRADIENT_warn_int_enable_pos 9
#define GRADIENT_warn_int_enable_width 1
#define GRADIENT_data_fifo_almost_empty_enable_addr 0x60
#define GRADIENT_data_fifo_almost_empty_enable_pos 10
#define GRADIENT_data_fifo_almost_empty_enable_width 1
#define GRADIENT_instr_fifo_almost_full_enable_addr 0x60
#define GRADIENT_instr_fifo_almost_full_enable_pos 11
#define GRADIENT_instr_fifo_almost_full_enable_width 1
#define GRADIENT_invalid_opcode_int_enable_addr 0x60
#define GRADIENT_invalid_opcode_int_enable_pos 12
#define GRADIENT_invalid_opcode_int_enable_width 1
#define GRADIENT_spi_failed_busy_enable_addr 0x60
#define GRADIENT_spi_failed_busy_enable_pos 13
#define GRADIENT_spi_failed_busy_enable_width 1
#define GRADIENT_slew_limit_exceeded_enable_addr 0x60
#define GRADIENT_slew_limit_exceeded_enable_pos 14
#define GRADIENT_slew_limit_exceeded_enable_width 4
#define GRADIENT_grad_isi_fault_enable_addr 0x60
#define GRADIENT_grad_isi_fault_enable_pos 18
#define GRADIENT_grad_isi_fault_enable_width 1
#define GRADIENT_fifo_overflow_clear_addr 0x64
#define GRADIENT_fifo_overflow_clear_pos 0
#define GRADIENT_fifo_overflow_clear_width 1
#define GRADIENT_fifo_underflow_clear_addr 0x64
#define GRADIENT_fifo_underflow_clear_pos 1
#define GRADIENT_fifo_underflow_clear_width 1
#define GRADIENT_fifo_finished_clear_addr 0x64
#define GRADIENT_fifo_finished_clear_pos 2
#define GRADIENT_fifo_finished_clear_width 1
#define GRADIENT_fifo_started_clear_addr 0x64
#define GRADIENT_fifo_started_clear_pos 3
#define GRADIENT_fifo_started_clear_width 1
#define GRADIENT_sw_int_clear_addr 0x64
#define GRADIENT_sw_int_clear_pos 4
#define GRADIENT_sw_int_clear_width 4
#define GRADIENT_fail_int_clear_addr 0x64
#define GRADIENT_fail_int_clear_pos 8
#define GRADIENT_fail_int_clear_width 1
#define GRADIENT_warn_int_clear_addr 0x64
#define GRADIENT_warn_int_clear_pos 9
#define GRADIENT_warn_int_clear_width 1
#define GRADIENT_data_fifo_almost_empty_clear_addr 0x64
#define GRADIENT_data_fifo_almost_empty_clear_pos 10
#define GRADIENT_data_fifo_almost_empty_clear_width 1
#define GRADIENT_instr_fifo_almost_full_clear_addr 0x64
#define GRADIENT_instr_fifo_almost_full_clear_pos 11
#define GRADIENT_instr_fifo_almost_full_clear_width 1
#define GRADIENT_invalid_opcode_int_clear_addr 0x64
#define GRADIENT_invalid_opcode_int_clear_pos 12
#define GRADIENT_invalid_opcode_int_clear_width 1
#define GRADIENT_spi_failed_busy_clear_addr 0x64
#define GRADIENT_spi_failed_busy_clear_pos 13
#define GRADIENT_spi_failed_busy_clear_width 1
#define GRADIENT_slew_limit_exceeded_clear_addr 0x64
#define GRADIENT_slew_limit_exceeded_clear_pos 14
#define GRADIENT_slew_limit_exceeded_clear_width 4
#define GRADIENT_grad_isi_fault_clear_addr 0x64
#define GRADIENT_grad_isi_fault_clear_pos 18
#define GRADIENT_grad_isi_fault_clear_width 1
#define GRADIENT_xdelay_fifo_empty_addr 0x68
#define GRADIENT_xdelay_fifo_empty_pos 0
#define GRADIENT_xdelay_fifo_empty_width 1
#define GRADIENT_ydelay_fifo_empty_addr 0x68
#define GRADIENT_ydelay_fifo_empty_pos 1
#define GRADIENT_ydelay_fifo_empty_width 1
#define GRADIENT_zdelay_fifo_empty_addr 0x68
#define GRADIENT_zdelay_fifo_empty_pos 2
#define GRADIENT_zdelay_fifo_empty_width 1
#define GRADIENT_b0delay_fifo_empty_addr 0x68
#define GRADIENT_b0delay_fifo_empty_pos 3
#define GRADIENT_b0delay_fifo_empty_width 1
#define GRADIENT_xdelay_fifo_full_addr 0x6c
#define GRADIENT_xdelay_fifo_full_pos 0
#define GRADIENT_xdelay_fifo_full_width 1
#define GRADIENT_ydelay_fifo_full_addr 0x6c
#define GRADIENT_ydelay_fifo_full_pos 1
#define GRADIENT_ydelay_fifo_full_width 1
#define GRADIENT_zdelay_fifo_full_addr 0x6c
#define GRADIENT_zdelay_fifo_full_pos 2
#define GRADIENT_zdelay_fifo_full_width 1
#define GRADIENT_b0delay_fifo_full_addr 0x6c
#define GRADIENT_b0delay_fifo_full_pos 3
#define GRADIENT_b0delay_fifo_full_width 1
#define GRADIENT_xdelay_fifo_count_addr 0x70
#define GRADIENT_xdelay_fifo_count_pos 0
#define GRADIENT_xdelay_fifo_count_width 9
#define GRADIENT_ydelay_fifo_count_addr 0x74
#define GRADIENT_ydelay_fifo_count_pos 0
#define GRADIENT_ydelay_fifo_count_width 9
#define GRADIENT_zdelay_fifo_count_addr 0x78
#define GRADIENT_zdelay_fifo_count_pos 0
#define GRADIENT_zdelay_fifo_count_width 9
#define GRADIENT_b0delay_fifo_count_addr 0x7c
#define GRADIENT_b0delay_fifo_count_pos 0
#define GRADIENT_b0delay_fifo_count_width 9
#define GRADIENT_instr_fifo_count_total_addr 0x80
#define GRADIENT_instr_fifo_count_total_pos 0
#define GRADIENT_instr_fifo_count_total_width 32
#define GRADIENT_clear_instr_fifo_count_total_addr 0x84
#define GRADIENT_clear_instr_fifo_count_total_pos 0
#define GRADIENT_clear_instr_fifo_count_total_width 1
#define GRADIENT_invalid_opcode_addr 0x88
#define GRADIENT_invalid_opcode_pos 0
#define GRADIENT_invalid_opcode_width 16
#define GRADIENT_xslewlimit_addr 0x8c
#define GRADIENT_xslewlimit_pos 0
#define GRADIENT_xslewlimit_width 16
#define GRADIENT_yslewlimit_addr 0x90
#define GRADIENT_yslewlimit_pos 0
#define GRADIENT_yslewlimit_width 16
#define GRADIENT_zslewlimit_addr 0x94
#define GRADIENT_zslewlimit_pos 0
#define GRADIENT_zslewlimit_width 16
#define GRADIENT_b0slewlimit_addr 0x98
#define GRADIENT_b0slewlimit_pos 0
#define GRADIENT_b0slewlimit_width 16
#define GRADIENT_slewlimit_disable_addr 0x9c
#define GRADIENT_slewlimit_disable_pos 0
#define GRADIENT_slewlimit_disable_width 1
#define GRADIENT_clear_xdelay_addr 0xa0
#define GRADIENT_clear_xdelay_pos 0
#define GRADIENT_clear_xdelay_width 1
#define GRADIENT_clear_ydelay_addr 0xa0
#define GRADIENT_clear_ydelay_pos 1
#define GRADIENT_clear_ydelay_width 1
#define GRADIENT_clear_zdelay_addr 0xa0
#define GRADIENT_clear_zdelay_pos 2
#define GRADIENT_clear_zdelay_width 1
#define GRADIENT_clear_b0delay_addr 0xa0
#define GRADIENT_clear_b0delay_pos 3
#define GRADIENT_clear_b0delay_width 1
#define GRADIENT_coarse_xdelay_addr 0xa4
#define GRADIENT_coarse_xdelay_pos 0
#define GRADIENT_coarse_xdelay_width 9
#define GRADIENT_coarse_ydelay_addr 0xa8
#define GRADIENT_coarse_ydelay_pos 0
#define GRADIENT_coarse_ydelay_width 9
#define GRADIENT_coarse_zdelay_addr 0xac
#define GRADIENT_coarse_zdelay_pos 0
#define GRADIENT_coarse_zdelay_width 9
#define GRADIENT_coarse_b0delay_addr 0xb0
#define GRADIENT_coarse_b0delay_pos 0
#define GRADIENT_coarse_b0delay_width 9
#define GRADIENT_fine_xdelay_addr 0xb4
#define GRADIENT_fine_xdelay_pos 0
#define GRADIENT_fine_xdelay_width 9
#define GRADIENT_fine_ydelay_addr 0xb8
#define GRADIENT_fine_ydelay_pos 0
#define GRADIENT_fine_ydelay_width 9
#define GRADIENT_fine_zdelay_addr 0xbc
#define GRADIENT_fine_zdelay_pos 0
#define GRADIENT_fine_zdelay_width 9
#define GRADIENT_fine_b0delay_addr 0xc0
#define GRADIENT_fine_b0delay_pos 0
#define GRADIENT_fine_b0delay_width 9
#define GRADIENT_grad_reset_addr 0xc4
#define GRADIENT_grad_reset_pos 0
#define GRADIENT_grad_reset_width 1
#define GRADIENT_grad_reset_done_addr 0xc8
#define GRADIENT_grad_reset_done_pos 0
#define GRADIENT_grad_reset_done_width 1
#define GRADIENT_grad_isi_fault_addr 0xcc
#define GRADIENT_grad_isi_fault_pos 0
#define GRADIENT_grad_isi_fault_width 1
#define GRADIENT_gradient_amp_type_addr 0xd0
#define GRADIENT_gradient_amp_type_pos 0
#define GRADIENT_gradient_amp_type_width 3
#define GRADIENT_spi_clk_rate_divisor_addr 0xd4
#define GRADIENT_spi_clk_rate_divisor_pos 0
#define GRADIENT_spi_clk_rate_divisor_width 7
#define GRADIENT_spi_data_size_addr 0xd4
#define GRADIENT_spi_data_size_pos 7
#define GRADIENT_spi_data_size_width 1
#define GRADIENT_spi_clk_polarity_addr 0xd4
#define GRADIENT_spi_clk_polarity_pos 8
#define GRADIENT_spi_clk_polarity_width 1
#define GRADIENT_spi_clk_resting_addr 0xd4
#define GRADIENT_spi_clk_resting_pos 9
#define GRADIENT_spi_clk_resting_width 1
#define GRADIENT_spi_data_out_addr 0xd8
#define GRADIENT_spi_data_out_pos 0
#define GRADIENT_spi_data_out_width 16
#define GRADIENT_spi_data_in_addr 0xdc
#define GRADIENT_spi_data_in_pos 0
#define GRADIENT_spi_data_in_width 16
#define GRADIENT_spi_start_addr 0xe0
#define GRADIENT_spi_start_pos 0
#define GRADIENT_spi_start_width 1
#define GRADIENT_spi_chip_selectN_addr 0xe4
#define GRADIENT_spi_chip_selectN_pos 0
#define GRADIENT_spi_chip_selectN_width 4
#define GRADIENT_spi_busy_addr 0xe8
#define GRADIENT_spi_busy_pos 0
#define GRADIENT_spi_busy_width 1
#define GRADIENT_grad_amp_busy_addr 0xec
#define GRADIENT_grad_amp_busy_pos 0
#define GRADIENT_grad_amp_busy_width 4
#define GRADIENT_grad_ecc_busy_addr 0xf0
#define GRADIENT_grad_ecc_busy_pos 0
#define GRADIENT_grad_ecc_busy_width 4
#define GRADIENT_sw_xamp_addr 0xf4
#define GRADIENT_sw_xamp_pos 0
#define GRADIENT_sw_xamp_width 16
#define GRADIENT_sw_yamp_addr 0xf8
#define GRADIENT_sw_yamp_pos 0
#define GRADIENT_sw_yamp_width 16
#define GRADIENT_sw_zamp_addr 0xfc
#define GRADIENT_sw_zamp_pos 0
#define GRADIENT_sw_zamp_width 16
#define GRADIENT_sw_b0amp_addr 0x100
#define GRADIENT_sw_b0amp_pos 0
#define GRADIENT_sw_b0amp_width 16
#define GRADIENT_sw_xamp_updated_addr 0x104
#define GRADIENT_sw_xamp_updated_pos 0
#define GRADIENT_sw_xamp_updated_width 1
#define GRADIENT_sw_yamp_updated_addr 0x108
#define GRADIENT_sw_yamp_updated_pos 0
#define GRADIENT_sw_yamp_updated_width 1
#define GRADIENT_sw_zamp_updated_addr 0x10c
#define GRADIENT_sw_zamp_updated_pos 0
#define GRADIENT_sw_zamp_updated_width 1
#define GRADIENT_sw_b0amp_updated_addr 0x110
#define GRADIENT_sw_b0amp_updated_pos 0
#define GRADIENT_sw_b0amp_updated_width 1
#define GRADIENT_sw_xecc_addr 0x114
#define GRADIENT_sw_xecc_pos 0
#define GRADIENT_sw_xecc_width 16
#define GRADIENT_sw_yecc_addr 0x118
#define GRADIENT_sw_yecc_pos 0
#define GRADIENT_sw_yecc_width 16
#define GRADIENT_sw_zecc_addr 0x11c
#define GRADIENT_sw_zecc_pos 0
#define GRADIENT_sw_zecc_width 16
#define GRADIENT_sw_b0ecc_addr 0x120
#define GRADIENT_sw_b0ecc_pos 0
#define GRADIENT_sw_b0ecc_width 16
#define GRADIENT_sw_xecc_updated_addr 0x124
#define GRADIENT_sw_xecc_updated_pos 0
#define GRADIENT_sw_xecc_updated_width 1
#define GRADIENT_sw_yecc_updated_addr 0x128
#define GRADIENT_sw_yecc_updated_pos 0
#define GRADIENT_sw_yecc_updated_width 1
#define GRADIENT_sw_zecc_updated_addr 0x12c
#define GRADIENT_sw_zecc_updated_pos 0
#define GRADIENT_sw_zecc_updated_width 1
#define GRADIENT_sw_b0ecc_updated_addr 0x130
#define GRADIENT_sw_b0ecc_updated_pos 0
#define GRADIENT_sw_b0ecc_updated_width 1
#define GRADIENT_sw_shim_addr 0x134
#define GRADIENT_sw_shim_pos 0
#define GRADIENT_sw_shim_width 20
#define GRADIENT_sw_shim_updated_addr 0x138
#define GRADIENT_sw_shim_updated_pos 0
#define GRADIENT_sw_shim_updated_width 1
#define GRADIENT_sw_gates_addr 0x13c
#define GRADIENT_sw_gates_pos 0
#define GRADIENT_sw_gates_width 12
#define GRADIENT_sw_user_addr 0x140
#define GRADIENT_sw_user_pos 0
#define GRADIENT_sw_user_width 3
#define GRADIENT_fifo_output_select_addr 0x144
#define GRADIENT_fifo_output_select_pos 0
#define GRADIENT_fifo_output_select_width 1
#define GRADIENT_sw_update_addr 0x148
#define GRADIENT_sw_update_pos 0
#define GRADIENT_sw_update_width 1
#define GRADIENT_new_fifo_xamp_addr 0x14c
#define GRADIENT_new_fifo_xamp_pos 0
#define GRADIENT_new_fifo_xamp_width 16
#define GRADIENT_new_fifo_yamp_addr 0x150
#define GRADIENT_new_fifo_yamp_pos 0
#define GRADIENT_new_fifo_yamp_width 16
#define GRADIENT_new_fifo_zamp_addr 0x154
#define GRADIENT_new_fifo_zamp_pos 0
#define GRADIENT_new_fifo_zamp_width 16
#define GRADIENT_new_fifo_b0amp_addr 0x158
#define GRADIENT_new_fifo_b0amp_pos 0
#define GRADIENT_new_fifo_b0amp_width 16
#define GRADIENT_fifo_xamp_updated_addr 0x15c
#define GRADIENT_fifo_xamp_updated_pos 0
#define GRADIENT_fifo_xamp_updated_width 1
#define GRADIENT_fifo_yamp_updated_addr 0x160
#define GRADIENT_fifo_yamp_updated_pos 0
#define GRADIENT_fifo_yamp_updated_width 1
#define GRADIENT_fifo_zamp_updated_addr 0x164
#define GRADIENT_fifo_zamp_updated_pos 0
#define GRADIENT_fifo_zamp_updated_width 1
#define GRADIENT_fifo_b0amp_updated_addr 0x168
#define GRADIENT_fifo_b0amp_updated_pos 0
#define GRADIENT_fifo_b0amp_updated_width 1
#define GRADIENT_fifo_ecccalc_select_addr 0x16c
#define GRADIENT_fifo_ecccalc_select_pos 0
#define GRADIENT_fifo_ecccalc_select_width 1
#define GRADIENT_fifo_ecccalc_decay_addr 0x16c
#define GRADIENT_fifo_ecccalc_decay_pos 1
#define GRADIENT_fifo_ecccalc_decay_width 1
#define GRADIENT_new_fifo_xecc_addr 0x170
#define GRADIENT_new_fifo_xecc_pos 0
#define GRADIENT_new_fifo_xecc_width 16
#define GRADIENT_new_fifo_yecc_addr 0x174
#define GRADIENT_new_fifo_yecc_pos 0
#define GRADIENT_new_fifo_yecc_width 16
#define GRADIENT_new_fifo_zecc_addr 0x178
#define GRADIENT_new_fifo_zecc_pos 0
#define GRADIENT_new_fifo_zecc_width 16
#define GRADIENT_new_fifo_b0ecc_addr 0x17c
#define GRADIENT_new_fifo_b0ecc_pos 0
#define GRADIENT_new_fifo_b0ecc_width 16
#define GRADIENT_fifo_xecc_updated_addr 0x180
#define GRADIENT_fifo_xecc_updated_pos 0
#define GRADIENT_fifo_xecc_updated_width 1
#define GRADIENT_fifo_yecc_updated_addr 0x184
#define GRADIENT_fifo_yecc_updated_pos 0
#define GRADIENT_fifo_yecc_updated_width 1
#define GRADIENT_fifo_zecc_updated_addr 0x188
#define GRADIENT_fifo_zecc_updated_pos 0
#define GRADIENT_fifo_zecc_updated_width 1
#define GRADIENT_fifo_b0ecc_updated_addr 0x18c
#define GRADIENT_fifo_b0ecc_updated_pos 0
#define GRADIENT_fifo_b0ecc_updated_width 1
#define GRADIENT_fifo_shim_addr 0x190
#define GRADIENT_fifo_shim_pos 0
#define GRADIENT_fifo_shim_width 20
#define GRADIENT_fifo_shim_updated_addr 0x194
#define GRADIENT_fifo_shim_updated_pos 0
#define GRADIENT_fifo_shim_updated_width 1
#define GRADIENT_fifo_gates_addr 0x198
#define GRADIENT_fifo_gates_pos 0
#define GRADIENT_fifo_gates_width 12
#define GRADIENT_fifo_user_addr 0x19c
#define GRADIENT_fifo_user_pos 0
#define GRADIENT_fifo_user_width 3
#define GRADIENT_holding_duration_addr 0x1a0
#define GRADIENT_holding_duration_pos 0
#define GRADIENT_holding_duration_width 26
#define GRADIENT_holding_duration_count_addr 0x1a4
#define GRADIENT_holding_duration_count_pos 0
#define GRADIENT_holding_duration_count_width 16
#define GRADIENT_holding_xamp_addr 0x1a8
#define GRADIENT_holding_xamp_pos 0
#define GRADIENT_holding_xamp_width 16
#define GRADIENT_holding_xamp_increment_addr 0x1ac
#define GRADIENT_holding_xamp_increment_pos 0
#define GRADIENT_holding_xamp_increment_width 16
#define GRADIENT_holding_xamp_count_addr 0x1b0
#define GRADIENT_holding_xamp_count_pos 0
#define GRADIENT_holding_xamp_count_width 9
#define GRADIENT_holding_xamp_clear_addr 0x1b4
#define GRADIENT_holding_xamp_clear_pos 0
#define GRADIENT_holding_xamp_clear_width 1
#define GRADIENT_holding_yamp_addr 0x1b8
#define GRADIENT_holding_yamp_pos 0
#define GRADIENT_holding_yamp_width 16
#define GRADIENT_holding_yamp_increment_addr 0x1bc
#define GRADIENT_holding_yamp_increment_pos 0
#define GRADIENT_holding_yamp_increment_width 16
#define GRADIENT_holding_yamp_count_addr 0x1c0
#define GRADIENT_holding_yamp_count_pos 0
#define GRADIENT_holding_yamp_count_width 9
#define GRADIENT_holding_yamp_clear_addr 0x1c4
#define GRADIENT_holding_yamp_clear_pos 0
#define GRADIENT_holding_yamp_clear_width 1
#define GRADIENT_holding_zamp_addr 0x1c8
#define GRADIENT_holding_zamp_pos 0
#define GRADIENT_holding_zamp_width 16
#define GRADIENT_holding_zamp_increment_addr 0x1cc
#define GRADIENT_holding_zamp_increment_pos 0
#define GRADIENT_holding_zamp_increment_width 16
#define GRADIENT_holding_zamp_count_addr 0x1d0
#define GRADIENT_holding_zamp_count_pos 0
#define GRADIENT_holding_zamp_count_width 9
#define GRADIENT_holding_zamp_clear_addr 0x1d4
#define GRADIENT_holding_zamp_clear_pos 0
#define GRADIENT_holding_zamp_clear_width 1
#define GRADIENT_holding_b0amp_addr 0x1d8
#define GRADIENT_holding_b0amp_pos 0
#define GRADIENT_holding_b0amp_width 16
#define GRADIENT_holding_b0amp_increment_addr 0x1dc
#define GRADIENT_holding_b0amp_increment_pos 0
#define GRADIENT_holding_b0amp_increment_width 16
#define GRADIENT_holding_b0amp_count_addr 0x1e0
#define GRADIENT_holding_b0amp_count_pos 0
#define GRADIENT_holding_b0amp_count_width 9
#define GRADIENT_holding_b0amp_clear_addr 0x1e4
#define GRADIENT_holding_b0amp_clear_pos 0
#define GRADIENT_holding_b0amp_clear_width 1
#define GRADIENT_holding_xamp_scale_addr 0x1e8
#define GRADIENT_holding_xamp_scale_pos 0
#define GRADIENT_holding_xamp_scale_width 16
#define GRADIENT_holding_xamp_scale_increment_addr 0x1ec
#define GRADIENT_holding_xamp_scale_increment_pos 0
#define GRADIENT_holding_xamp_scale_increment_width 16
#define GRADIENT_holding_xamp_scale_count_addr 0x1f0
#define GRADIENT_holding_xamp_scale_count_pos 0
#define GRADIENT_holding_xamp_scale_count_width 9
#define GRADIENT_holding_xamp_scale_clear_addr 0x1f4
#define GRADIENT_holding_xamp_scale_clear_pos 0
#define GRADIENT_holding_xamp_scale_clear_width 1
#define GRADIENT_holding_yamp_scale_addr 0x1f8
#define GRADIENT_holding_yamp_scale_pos 0
#define GRADIENT_holding_yamp_scale_width 16
#define GRADIENT_holding_yamp_scale_increment_addr 0x1fc
#define GRADIENT_holding_yamp_scale_increment_pos 0
#define GRADIENT_holding_yamp_scale_increment_width 16
#define GRADIENT_holding_yamp_scale_count_addr 0x200
#define GRADIENT_holding_yamp_scale_count_pos 0
#define GRADIENT_holding_yamp_scale_count_width 9
#define GRADIENT_holding_yamp_scale_clear_addr 0x204
#define GRADIENT_holding_yamp_scale_clear_pos 0
#define GRADIENT_holding_yamp_scale_clear_width 1
#define GRADIENT_holding_zamp_scale_addr 0x208
#define GRADIENT_holding_zamp_scale_pos 0
#define GRADIENT_holding_zamp_scale_width 16
#define GRADIENT_holding_zamp_scale_increment_addr 0x20c
#define GRADIENT_holding_zamp_scale_increment_pos 0
#define GRADIENT_holding_zamp_scale_increment_width 16
#define GRADIENT_holding_zamp_scale_count_addr 0x210
#define GRADIENT_holding_zamp_scale_count_pos 0
#define GRADIENT_holding_zamp_scale_count_width 9
#define GRADIENT_holding_zamp_scale_clear_addr 0x214
#define GRADIENT_holding_zamp_scale_clear_pos 0
#define GRADIENT_holding_zamp_scale_clear_width 1
#define GRADIENT_holding_b0amp_scale_addr 0x218
#define GRADIENT_holding_b0amp_scale_pos 0
#define GRADIENT_holding_b0amp_scale_width 16
#define GRADIENT_holding_b0amp_scale_increment_addr 0x21c
#define GRADIENT_holding_b0amp_scale_increment_pos 0
#define GRADIENT_holding_b0amp_scale_increment_width 16
#define GRADIENT_holding_b0amp_scale_count_addr 0x220
#define GRADIENT_holding_b0amp_scale_count_pos 0
#define GRADIENT_holding_b0amp_scale_count_width 9
#define GRADIENT_holding_b0amp_scale_clear_addr 0x224
#define GRADIENT_holding_b0amp_scale_clear_pos 0
#define GRADIENT_holding_b0amp_scale_clear_width 1
#define GRADIENT_holding_xamp_updated_addr 0x228
#define GRADIENT_holding_xamp_updated_pos 0
#define GRADIENT_holding_xamp_updated_width 1
#define GRADIENT_holding_yamp_updated_addr 0x22c
#define GRADIENT_holding_yamp_updated_pos 0
#define GRADIENT_holding_yamp_updated_width 1
#define GRADIENT_holding_zamp_updated_addr 0x230
#define GRADIENT_holding_zamp_updated_pos 0
#define GRADIENT_holding_zamp_updated_width 1
#define GRADIENT_holding_b0amp_updated_addr 0x234
#define GRADIENT_holding_b0amp_updated_pos 0
#define GRADIENT_holding_b0amp_updated_width 1
#define GRADIENT_holding_xecc_addr 0x238
#define GRADIENT_holding_xecc_pos 0
#define GRADIENT_holding_xecc_width 16
#define GRADIENT_holding_yecc_addr 0x23c
#define GRADIENT_holding_yecc_pos 0
#define GRADIENT_holding_yecc_width 16
#define GRADIENT_holding_zecc_addr 0x240
#define GRADIENT_holding_zecc_pos 0
#define GRADIENT_holding_zecc_width 16
#define GRADIENT_holding_b0ecc_addr 0x244
#define GRADIENT_holding_b0ecc_pos 0
#define GRADIENT_holding_b0ecc_width 16
#define GRADIENT_holding_xecc_updated_addr 0x248
#define GRADIENT_holding_xecc_updated_pos 0
#define GRADIENT_holding_xecc_updated_width 1
#define GRADIENT_holding_yecc_updated_addr 0x24c
#define GRADIENT_holding_yecc_updated_pos 0
#define GRADIENT_holding_yecc_updated_width 1
#define GRADIENT_holding_zecc_updated_addr 0x250
#define GRADIENT_holding_zecc_updated_pos 0
#define GRADIENT_holding_zecc_updated_width 1
#define GRADIENT_holding_b0ecc_updated_addr 0x254
#define GRADIENT_holding_b0ecc_updated_pos 0
#define GRADIENT_holding_b0ecc_updated_width 1
#define GRADIENT_holding_shim_addr 0x258
#define GRADIENT_holding_shim_pos 0
#define GRADIENT_holding_shim_width 20
#define GRADIENT_holding_shim_updated_addr 0x25c
#define GRADIENT_holding_shim_updated_pos 0
#define GRADIENT_holding_shim_updated_width 1
#define GRADIENT_holding_gates_addr 0x260
#define GRADIENT_holding_gates_pos 0
#define GRADIENT_holding_gates_width 12
#define GRADIENT_holding_user_addr 0x264
#define GRADIENT_holding_user_pos 0
#define GRADIENT_holding_user_width 3
#define GRADIENT_fifo_instruction_addr 0x268
#define GRADIENT_fifo_instruction_pos 0
#define GRADIENT_fifo_instruction_width 32
#define GRADIENT_la_trigger_select_addr 0x26c
#define GRADIENT_la_trigger_select_pos 0
#define GRADIENT_la_trigger_select_width 7
#define GRADIENT_la_trigger_polarity_addr 0x26c
#define GRADIENT_la_trigger_polarity_pos 7
#define GRADIENT_la_trigger_polarity_width 2
#define GRADIENT_la_trigger_arm_addr 0x26c
#define GRADIENT_la_trigger_arm_pos 9
#define GRADIENT_la_trigger_arm_width 1
#define GRADIENT_la_force_trigger_addr 0x26c
#define GRADIENT_la_force_trigger_pos 10
#define GRADIENT_la_force_trigger_width 1
#define GRADIENT_la_trigger_leadin_addr 0x26c
#define GRADIENT_la_trigger_leadin_pos 11
#define GRADIENT_la_trigger_leadin_width 10
#define GRADIENT_la_sample_divisor_addr 0x26c
#define GRADIENT_la_sample_divisor_pos 21
#define GRADIENT_la_sample_divisor_width 8
#define GRADIENT_la_start_data_addr 0x270
#define GRADIENT_la_start_data_pos 0
#define GRADIENT_la_start_data_width 10
#define GRADIENT_la_triggered_addr 0x270
#define GRADIENT_la_triggered_pos 10
#define GRADIENT_la_triggered_width 1
#define GRADIENT_la_checksum_addr 0x274
#define GRADIENT_la_checksum_pos 0
#define GRADIENT_la_checksum_width 16
#define GRADIENT_la_address_addr 0x278
#define GRADIENT_la_address_pos 0
#define GRADIENT_la_address_width 12
#define GRADIENT_la_data_addr 0x27c
#define GRADIENT_la_data_pos 0
#define GRADIENT_la_data_width 32
#define GRADIENT_eccamp_addr 0x300
#define GRADIENT_eccamp_pos 0
#define GRADIENT_eccamp_width 16
#define GRADIENT_ecctc_addr 0x400
#define GRADIENT_ecctc_pos 0
#define GRADIENT_ecctc_width 32
#endif
