/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
#ifndef __iCAT_H__
#define __iCAT_H__
#ifndef get_field
  #define __get_field(fpga,field,value) \
    (((value)>>fpga##_##field##_pos)&((1<<fpga##_##field##_width)-1))
  #define get_field(fpga,field,value) __get_field(fpga,field,value)
#endif
#ifndef set_field
  #define __set_field(fpga,field,value) \
    (((value)&((1<<fpga##_##field##_width)-1))<<fpga##_##field##_pos)
  #define set_field(fpga,field,value) __set_field(fpga,field,value)
#endif
#ifndef get_field_width
  #define __get_field_width(fpga,field) fpga##_##field##_width
  #define get_field_width(fpga,field) __get_field_width(fpga,field)
#endif
#ifndef get_field_addr
  #define __get_field_addr(fpga,field) fpga##_##field##_addr
  #define get_field_addr(fpga,field) __get_field_addr(fpga,field)
#endif
#define iCAT_CHECKSUM 21447
#define iCAT_ID 0x0
#define iCAT_Checksum 0x1
#define iCAT_ChipControl 0x2
#define iCAT_ChipStatus 0x3
#define iCAT_LED 0x4
#define iCAT_Reboot 0x5
#define iCAT_RebootAddressLow 0x6
#define iCAT_RebootAddressHigh 0x7
#define iCAT_TimeStampLow 0x8
#define iCAT_TimeStampHigh 0x9
#define iCAT_DNA0 0xA
#define iCAT_DNA1 0xB
#define iCAT_DNA2 0xC
#define iCAT_DNA3 0xD
#define iCAT_BoardRev 0xE
#define iCAT_TestPointLowOutput 0xF
#define iCAT_TestPointLowOutputEnable 0x10
#define iCAT_TestPointLowInput 0x11
#define iCAT_TestPointHighOutput 0x12
#define iCAT_TestPointHighOutputEnable 0x13
#define iCAT_TestPointHighInput 0x14
#define iCAT_MictorLowOutput 0x15
#define iCAT_MictorLowOutputEnable 0x16
#define iCAT_MictorLowInput 0x17
#define iCAT_MictorHighOutput 0x18
#define iCAT_MictorHighOutputEnable 0x19
#define iCAT_MictorHighInput 0x1A
#define iCAT_ResetSynchronizer 0x1B
#define iCAT_PrimaryDCMTarget 0x1C
#define iCAT_PrimaryDCMControl 0x1D
#define iCAT_PrimaryDCMStatus 0x1E
#define iCAT_PrimaryDCMCurrentPhaseShift 0x1F
#define iCAT_TXDDCMTarget 0x20
#define iCAT_TXDDCMControl 0x21
#define iCAT_TXDDCMStatus 0x22
#define iCAT_TXDDCMCurrentPhaseShift 0x23
#define iCAT_TemperatureControl 0x24
#define iCAT_TemperatureStatus 0x25
#define iCAT_TemperatureAcquisitionPeriod 0x26
#define iCAT_CurrentTemperature 0x27
#define iCAT_AverageTemperature 0x28
#define iCAT_Temperature 0x29
#define iCAT_ForcedTemperature 0x2A
#define iCAT_DACGainControl 0x2B
#define iCAT_SineGainNominal 0x2C
#define iCAT_AmpGainNominal 0x2D
#define iCAT_AmpNullNominal 0x2E
#define iCAT_FineGroupDelayNominal 0x2F
#define iCAT_SineGain 0x30
#define iCAT_AmpGain 0x31
#define iCAT_AmpNull 0x32
#define iCAT_FineGroupDelay 0x33
#define iCAT_PhaseTemperatureCoefficient 0x34
#define iCAT_AmpTemperatureCoefficient 0x35
#define iCAT_SineGainTemperatureCoefficient 0x36
#define iCAT_AmpGainTemperatureCoefficient 0x37
#define iCAT_AmpNullTemperatureCoefficient 0x38
#define iCAT_FineGroupDelayTemperatureCoefficient 0x39
#define iCAT_DelayTemperatureCoefficient 0x3A
#define iCAT_SynthesizerControl 0x3B
#define iCAT_SynthesizerEnableCount 0x3C
#define iCAT_SynthesizerOutputBias 0x3D
#define iCAT_SynthesizerScaleFrac 0x3E
#define iCAT_SynthesizerScaleInt 0x3F
#define iCAT_SynthesizerPhaseIncrementLow 0x40
#define iCAT_SynthesizerPhaseIncrementHigh 0x41
#define iCAT_AmpValue 0x42
#define iCAT_SynthesizerValue 0x43
#define iCAT_SynthesizerPhaseLoadLow 0x44
#define iCAT_SynthesizerPhaseLoadHigh 0x45
#define iCAT_SynthesizerPhaseCountLow 0x46
#define iCAT_SynthesizerPhaseCountHigh 0x47
#define iCAT_AmpScale 0x48
#define iCAT_AmpBias 0x49
#define iCAT_AmpInvert 0x4A
#define iCAT_CurrentPhase 0x4B
#define iCAT_CurrentAmp 0x4C
#define iCAT_CurrentFifoGates 0x4D
#define iCAT_CurrentFifoAux 0x4E
#define iCAT_CompensatedPhase 0x4F
#define iCAT_CompensatedAmp 0x50
#define iCAT_ClearChecksums 0x51
#define iCAT_PhaseChecksum 0x52
#define iCAT_AmpChecksum 0x53
#define iCAT_FifoGateChecksum 0x54
#define iCAT_TXDChecksumLow 0x55
#define iCAT_TXDChecksumHigh 0x56
#define iCAT_AmpDelay 0x57
#define iCAT_SineDelay 0x58
#define iCAT_FifoGateDelay 0x59
#define iCAT_AuxDelay 0x5A
#define iCAT_AttenDelay 0x5B
#define iCAT_DelayDelay 0x5C
#define iCAT_XmitLoRiseCutThrough 0x5D
#define iCAT_XmitLoFallCutThrough 0x5E
#define iCAT_AttenuatorSelect 0x5F
#define iCAT_ForceAttenuatorSelect 0x60
#define iCAT_CurrentAttenuatorIndex 0x61
#define iCAT_CurrentAttenuatorValueLow 0x62
#define iCAT_CurrentAttenuatorValueHigh 0x63
#define iCAT_CurrentDelayValue 0x64
#define iCAT_AttenuationCalibration 0x65
#define iCAT_CurrentMappedAttenuatorIndex 0x66
#define iCAT_AuxOverride 0x67
#define iCAT_AuxOverrideValue 0x68
#define iCAT_ForceGates 0x69
#define iCAT_SwapSineAndAmp 0x6A
#define iCAT_SineNoiseScaleLow 0x6B
#define iCAT_SineNoiseScaleHigh 0x6C
#define iCAT_NoiseScaleLow 0x6D
#define iCAT_NoiseScaleHigh 0x6E
#define iCAT_ShapedNoiseCoefficientTable 0x80
#define iCAT_AttenuatorTable 0x400
#define iCAT_AmpLinearizationTable 0x800
#define iCAT_AmpGainCompressionTable 0xA00
#define iCAT_TempCompTable 0x2000
#define iCAT_ID_addr 0x0
#define iCAT_ID_pos 0
#define iCAT_ID_width 4
#define iCAT_revision_addr 0x0
#define iCAT_revision_pos 4
#define iCAT_revision_width 4
#define iCAT_checksum_addr 0x1
#define iCAT_checksum_pos 0
#define iCAT_checksum_width 16
#define iCAT_hard_reset_addr 0x2
#define iCAT_hard_reset_pos 0
#define iCAT_hard_reset_width 1
#define iCAT_soft_reset_addr 0x2
#define iCAT_soft_reset_pos 1
#define iCAT_soft_reset_width 1
#define iCAT_assert_interrupt_addr 0x2
#define iCAT_assert_interrupt_pos 2
#define iCAT_assert_interrupt_width 1
#define iCAT_assert_tx_fail_addr 0x2
#define iCAT_assert_tx_fail_pos 3
#define iCAT_assert_tx_fail_width 1
#define iCAT_dac_reset_addr 0x2
#define iCAT_dac_reset_pos 4
#define iCAT_dac_reset_width 1
#define iCAT_pwr_fail_addr 0x3
#define iCAT_pwr_fail_pos 0
#define iCAT_pwr_fail_width 1
#define iCAT_led_out_addr 0x4
#define iCAT_led_out_pos 0
#define iCAT_led_out_width 8
#define iCAT_reboot_addr 0x5
#define iCAT_reboot_pos 0
#define iCAT_reboot_width 1
#define iCAT_reboot_low_addr 0x6
#define iCAT_reboot_low_pos 0
#define iCAT_reboot_low_width 16
#define iCAT_reboot_high_addr 0x7
#define iCAT_reboot_high_pos 0
#define iCAT_reboot_high_width 16
#define iCAT_timestamp_low_addr 0x8
#define iCAT_timestamp_low_pos 0
#define iCAT_timestamp_low_width 16
#define iCAT_timestamp_high_addr 0x9
#define iCAT_timestamp_high_pos 0
#define iCAT_timestamp_high_width 16
#define iCAT_dna0_addr 0xA
#define iCAT_dna0_pos 0
#define iCAT_dna0_width 16
#define iCAT_dna1_addr 0xB
#define iCAT_dna1_pos 0
#define iCAT_dna1_width 16
#define iCAT_dna2_addr 0xC
#define iCAT_dna2_pos 0
#define iCAT_dna2_width 16
#define iCAT_dna3_addr 0xD
#define iCAT_dna3_pos 0
#define iCAT_dna3_width 16
#define iCAT_board_rev_addr 0xE
#define iCAT_board_rev_pos 0
#define iCAT_board_rev_width 3
#define iCAT_tp_low_out_addr 0xF
#define iCAT_tp_low_out_pos 0
#define iCAT_tp_low_out_width 16
#define iCAT_tp_low_en_addr 0x10
#define iCAT_tp_low_en_pos 0
#define iCAT_tp_low_en_width 16
#define iCAT_tp_low_addr 0x11
#define iCAT_tp_low_pos 0
#define iCAT_tp_low_width 16
#define iCAT_tp_high_out_addr 0x12
#define iCAT_tp_high_out_pos 0
#define iCAT_tp_high_out_width 8
#define iCAT_tp_high_en_addr 0x13
#define iCAT_tp_high_en_pos 0
#define iCAT_tp_high_en_width 8
#define iCAT_tp_high_addr 0x14
#define iCAT_tp_high_pos 0
#define iCAT_tp_high_width 8
#define iCAT_mictor_low_out_addr 0x15
#define iCAT_mictor_low_out_pos 0
#define iCAT_mictor_low_out_width 16
#define iCAT_mictor_low_en_addr 0x16
#define iCAT_mictor_low_en_pos 0
#define iCAT_mictor_low_en_width 16
#define iCAT_mictor_low_addr 0x17
#define iCAT_mictor_low_pos 0
#define iCAT_mictor_low_width 16
#define iCAT_mictor_high_out_addr 0x18
#define iCAT_mictor_high_out_pos 0
#define iCAT_mictor_high_out_width 16
#define iCAT_mictor_high_en_addr 0x19
#define iCAT_mictor_high_en_pos 0
#define iCAT_mictor_high_en_width 16
#define iCAT_mictor_high_addr 0x1A
#define iCAT_mictor_high_pos 0
#define iCAT_mictor_high_width 16
#define iCAT_txd_sync_reset_addr 0x1B
#define iCAT_txd_sync_reset_pos 0
#define iCAT_txd_sync_reset_width 1
#define iCAT_primary_sync_reset_addr 0x1B
#define iCAT_primary_sync_reset_pos 1
#define iCAT_primary_sync_reset_width 1
#define iCAT_primary_phase_shift_addr 0x1C
#define iCAT_primary_phase_shift_pos 0
#define iCAT_primary_phase_shift_width 9
#define iCAT_primary_reset_addr 0x1D
#define iCAT_primary_reset_pos 0
#define iCAT_primary_reset_width 1
#define iCAT_primary_locked_addr 0x1E
#define iCAT_primary_locked_pos 0
#define iCAT_primary_locked_width 1
#define iCAT_primary_psidle_addr 0x1E
#define iCAT_primary_psidle_pos 1
#define iCAT_primary_psidle_width 1
#define iCAT_primary_status_addr 0x1E
#define iCAT_primary_status_pos 2
#define iCAT_primary_status_width 3
#define iCAT_primary_lost_locked_addr 0x1E
#define iCAT_primary_lost_locked_pos 5
#define iCAT_primary_lost_locked_width 1
#define iCAT_primary_current_phase_shift_addr 0x1F
#define iCAT_primary_current_phase_shift_pos 0
#define iCAT_primary_current_phase_shift_width 9
#define iCAT_txd_phase_shift_addr 0x20
#define iCAT_txd_phase_shift_pos 0
#define iCAT_txd_phase_shift_width 9
#define iCAT_txd_reset_addr 0x21
#define iCAT_txd_reset_pos 0
#define iCAT_txd_reset_width 1
#define iCAT_txd_locked_addr 0x22
#define iCAT_txd_locked_pos 0
#define iCAT_txd_locked_width 1
#define iCAT_txd_psidle_addr 0x22
#define iCAT_txd_psidle_pos 1
#define iCAT_txd_psidle_width 1
#define iCAT_txd_status_addr 0x22
#define iCAT_txd_status_pos 2
#define iCAT_txd_status_width 3
#define iCAT_txd_lost_locked_addr 0x22
#define iCAT_txd_lost_locked_pos 5
#define iCAT_txd_lost_locked_width 1
#define iCAT_txd_current_phase_shift_addr 0x23
#define iCAT_txd_current_phase_shift_pos 0
#define iCAT_txd_current_phase_shift_width 9
#define iCAT_acquire_temperature_addr 0x24
#define iCAT_acquire_temperature_pos 0
#define iCAT_acquire_temperature_width 1
#define iCAT_periodic_temperature_acquisition_enable_addr 0x24
#define iCAT_periodic_temperature_acquisition_enable_pos 1
#define iCAT_periodic_temperature_acquisition_enable_width 1
#define iCAT_reset_temp_sense_addr 0x24
#define iCAT_reset_temp_sense_pos 2
#define iCAT_reset_temp_sense_width 1
#define iCAT_force_temperature_addr 0x24
#define iCAT_force_temperature_pos 3
#define iCAT_force_temperature_width 1
#define iCAT_force_temperature_compensation_enable_addr 0x24
#define iCAT_force_temperature_compensation_enable_pos 4
#define iCAT_force_temperature_compensation_enable_width 1
#define iCAT_force_temperature_compensation_disable_addr 0x24
#define iCAT_force_temperature_compensation_disable_pos 5
#define iCAT_force_temperature_compensation_disable_width 1
#define iCAT_temperature_valid_addr 0x25
#define iCAT_temperature_valid_pos 0
#define iCAT_temperature_valid_width 1
#define iCAT_temperature_acquisition_busy_addr 0x25
#define iCAT_temperature_acquisition_busy_pos 1
#define iCAT_temperature_acquisition_busy_width 1
#define iCAT_temperature_counter_overflow_addr 0x25
#define iCAT_temperature_counter_overflow_pos 2
#define iCAT_temperature_counter_overflow_width 1
#define iCAT_temperature_addr 0x25
#define iCAT_temperature_pos 3
#define iCAT_temperature_width 1
#define iCAT_temperature_compensation_enabled_addr 0x25
#define iCAT_temperature_compensation_enabled_pos 4
#define iCAT_temperature_compensation_enabled_width 1
#define iCAT_continuous_update_mode_addr 0x25
#define iCAT_continuous_update_mode_pos 5
#define iCAT_continuous_update_mode_width 1
#define iCAT_temperature_acquisition_period_addr 0x26
#define iCAT_temperature_acquisition_period_pos 0
#define iCAT_temperature_acquisition_period_width 16
#define iCAT_current_temperature_addr 0x27
#define iCAT_current_temperature_pos 0
#define iCAT_current_temperature_width 16
#define iCAT_average_temperature_addr 0x28
#define iCAT_average_temperature_pos 0
#define iCAT_average_temperature_width 16
#define iCAT_measured_temperature_addr 0x29
#define iCAT_measured_temperature_pos 0
#define iCAT_measured_temperature_width 16
#define iCAT_forced_temperature_addr 0x2A
#define iCAT_forced_temperature_pos 0
#define iCAT_forced_temperature_width 16
#define iCAT_program_dac_gain_addr 0x2B
#define iCAT_program_dac_gain_pos 0
#define iCAT_program_dac_gain_width 1
#define iCAT_sinegainnom_addr 0x2C
#define iCAT_sinegainnom_pos 0
#define iCAT_sinegainnom_width 16
#define iCAT_ampgainnom_addr 0x2D
#define iCAT_ampgainnom_pos 0
#define iCAT_ampgainnom_width 16
#define iCAT_ampnullnom_addr 0x2E
#define iCAT_ampnullnom_pos 0
#define iCAT_ampnullnom_width 16
#define iCAT_fgdnom_addr 0x2F
#define iCAT_fgdnom_pos 0
#define iCAT_fgdnom_width 16
#define iCAT_sinegain_addr 0x30
#define iCAT_sinegain_pos 0
#define iCAT_sinegain_width 16
#define iCAT_ampgain_addr 0x31
#define iCAT_ampgain_pos 0
#define iCAT_ampgain_width 16
#define iCAT_ampnull_addr 0x32
#define iCAT_ampnull_pos 0
#define iCAT_ampnull_width 16
#define iCAT_fgd_addr 0x33
#define iCAT_fgd_pos 0
#define iCAT_fgd_width 16
#define iCAT_phasetc_addr 0x34
#define iCAT_phasetc_pos 0
#define iCAT_phasetc_width 16
#define iCAT_amptc_addr 0x35
#define iCAT_amptc_pos 0
#define iCAT_amptc_width 16
#define iCAT_sinegaintc_addr 0x36
#define iCAT_sinegaintc_pos 0
#define iCAT_sinegaintc_width 16
#define iCAT_ampgaintc_addr 0x37
#define iCAT_ampgaintc_pos 0
#define iCAT_ampgaintc_width 16
#define iCAT_ampnulltc_addr 0x38
#define iCAT_ampnulltc_pos 0
#define iCAT_ampnulltc_width 16
#define iCAT_fgdtc_addr 0x39
#define iCAT_fgdtc_pos 0
#define iCAT_fgdtc_width 16
#define iCAT_delaytc_addr 0x3A
#define iCAT_delaytc_pos 0
#define iCAT_delaytc_width 16
#define iCAT_enable_phase_counter_addr 0x3B
#define iCAT_enable_phase_counter_pos 0
#define iCAT_enable_phase_counter_width 1
#define iCAT_bypass_sine_addr 0x3B
#define iCAT_bypass_sine_pos 1
#define iCAT_bypass_sine_width 1
#define iCAT_reset_phase_accum_on_start_addr 0x3B
#define iCAT_reset_phase_accum_on_start_pos 2
#define iCAT_reset_phase_accum_on_start_width 1
#define iCAT_enable_count_addr 0x3C
#define iCAT_enable_count_pos 0
#define iCAT_enable_count_width 16
#define iCAT_bias_addr 0x3D
#define iCAT_bias_pos 0
#define iCAT_bias_width 16
#define iCAT_alpha_frac_addr 0x3E
#define iCAT_alpha_frac_pos 0
#define iCAT_alpha_frac_width 16
#define iCAT_alpha_int_addr 0x3F
#define iCAT_alpha_int_pos 0
#define iCAT_alpha_int_width 1
#define iCAT_phase_increment_low_addr 0x40
#define iCAT_phase_increment_low_pos 0
#define iCAT_phase_increment_low_width 16
#define iCAT_phase_increment_high_addr 0x41
#define iCAT_phase_increment_high_pos 0
#define iCAT_phase_increment_high_width 16
#define iCAT_dac0_addr 0x42
#define iCAT_dac0_pos 0
#define iCAT_dac0_width 16
#define iCAT_dac1_addr 0x43
#define iCAT_dac1_pos 0
#define iCAT_dac1_width 16
#define iCAT_phase_load_low_addr 0x44
#define iCAT_phase_load_low_pos 0
#define iCAT_phase_load_low_width 16
#define iCAT_phase_load_high_addr 0x45
#define iCAT_phase_load_high_pos 0
#define iCAT_phase_load_high_width 16
#define iCAT_phase_count_low_addr 0x46
#define iCAT_phase_count_low_pos 0
#define iCAT_phase_count_low_width 16
#define iCAT_phase_count_high_addr 0x47
#define iCAT_phase_count_high_pos 0
#define iCAT_phase_count_high_width 16
#define iCAT_amp_scale_addr 0x48
#define iCAT_amp_scale_pos 0
#define iCAT_amp_scale_width 16
#define iCAT_amp_bias_addr 0x49
#define iCAT_amp_bias_pos 0
#define iCAT_amp_bias_width 16
#define iCAT_amp_invert_addr 0x4A
#define iCAT_amp_invert_pos 0
#define iCAT_amp_invert_width 16
#define iCAT_phase_addr 0x4B
#define iCAT_phase_pos 0
#define iCAT_phase_width 16
#define iCAT_amp_addr 0x4C
#define iCAT_amp_pos 0
#define iCAT_amp_width 16
#define iCAT_fifo_gate_addr 0x4D
#define iCAT_fifo_gate_pos 0
#define iCAT_fifo_gate_width 8
#define iCAT_aux_addr 0x4E
#define iCAT_aux_pos 0
#define iCAT_aux_width 6
#define iCAT_adjusted_phase_addr 0x4F
#define iCAT_adjusted_phase_pos 0
#define iCAT_adjusted_phase_width 16
#define iCAT_adjusted_amp_addr 0x50
#define iCAT_adjusted_amp_pos 0
#define iCAT_adjusted_amp_width 16
#define iCAT_clear_checksum_addr 0x51
#define iCAT_clear_checksum_pos 0
#define iCAT_clear_checksum_width 1
#define iCAT_phase_checksum_addr 0x52
#define iCAT_phase_checksum_pos 0
#define iCAT_phase_checksum_width 16
#define iCAT_amp_checksum_addr 0x53
#define iCAT_amp_checksum_pos 0
#define iCAT_amp_checksum_width 16
#define iCAT_fifo_gate_checksum_addr 0x54
#define iCAT_fifo_gate_checksum_pos 0
#define iCAT_fifo_gate_checksum_width 16
#define iCAT_txd_checksum_low_addr 0x55
#define iCAT_txd_checksum_low_pos 0
#define iCAT_txd_checksum_low_width 16
#define iCAT_txd_checksum_high_addr 0x56
#define iCAT_txd_checksum_high_pos 0
#define iCAT_txd_checksum_high_width 16
#define iCAT_amp_delay_addr 0x57
#define iCAT_amp_delay_pos 0
#define iCAT_amp_delay_width 6
#define iCAT_sine_delay_addr 0x58
#define iCAT_sine_delay_pos 0
#define iCAT_sine_delay_width 6
#define iCAT_fifo_gate_delay_addr 0x59
#define iCAT_fifo_gate_delay_pos 0
#define iCAT_fifo_gate_delay_width 6
#define iCAT_aux_delay_addr 0x5A
#define iCAT_aux_delay_pos 0
#define iCAT_aux_delay_width 6
#define iCAT_atten_delay_addr 0x5B
#define iCAT_atten_delay_pos 0
#define iCAT_atten_delay_width 6
#define iCAT_delay_delay_addr 0x5C
#define iCAT_delay_delay_pos 0
#define iCAT_delay_delay_width 6
#define iCAT_xmit_lo_rise_cut_through_addr 0x5D
#define iCAT_xmit_lo_rise_cut_through_pos 0
#define iCAT_xmit_lo_rise_cut_through_width 2
#define iCAT_xmit_lo_fall_cut_through_addr 0x5E
#define iCAT_xmit_lo_fall_cut_through_pos 0
#define iCAT_xmit_lo_fall_cut_through_width 2
#define iCAT_atten_entry_select_addr 0x5F
#define iCAT_atten_entry_select_pos 0
#define iCAT_atten_entry_select_width 9
#define iCAT_force_atten_entry_select_addr 0x60
#define iCAT_force_atten_entry_select_pos 0
#define iCAT_force_atten_entry_select_width 1
#define iCAT_atten_index_addr 0x61
#define iCAT_atten_index_pos 0
#define iCAT_atten_index_width 9
#define iCAT_atten_low_addr 0x62
#define iCAT_atten_low_pos 0
#define iCAT_atten_low_width 16
#define iCAT_atten_high_addr 0x63
#define iCAT_atten_high_pos 0
#define iCAT_atten_high_width 8
#define iCAT_delay_width 7
#define iCAT_atten_calibration_addr 0x65
#define iCAT_atten_calibration_pos 0
#define iCAT_atten_calibration_width 8
#define iCAT_mapped_atten_index_addr 0x66
#define iCAT_mapped_atten_index_pos 0
#define iCAT_mapped_atten_index_width 9
#define iCAT_aux_override_addr 0x67
#define iCAT_aux_override_pos 0
#define iCAT_aux_override_width 1
#define iCAT_aux_override_value_addr 0x68
#define iCAT_aux_override_value_pos 0
#define iCAT_aux_override_value_width 6
#define iCAT_forced_gate_value_addr 0x69
#define iCAT_forced_gate_value_pos 0
#define iCAT_forced_gate_value_width 8
#define iCAT_forced_gate_mask_addr 0x69
#define iCAT_forced_gate_mask_pos 8
#define iCAT_forced_gate_mask_width 8
#define iCAT_swap_sine_and_amp_addr 0x6A
#define iCAT_swap_sine_and_amp_pos 0
#define iCAT_swap_sine_and_amp_width 1
#define iCAT_sine_scale_low_addr 0x6B
#define iCAT_sine_scale_low_pos 0
#define iCAT_sine_scale_low_width 16
#define iCAT_sine_scale_high_addr 0x6C
#define iCAT_sine_scale_high_pos 0
#define iCAT_sine_scale_high_width 16
#define iCAT_noise_scale_low_addr 0x6D
#define iCAT_noise_scale_low_pos 0
#define iCAT_noise_scale_low_width 16
#define iCAT_noise_scale_high_addr 0x6E
#define iCAT_noise_scale_high_pos 0
#define iCAT_noise_scale_high_width 18
#define iCAT_coefficient_addr 0x80
#define iCAT_coefficient_pos 0
#define iCAT_coefficient_width 18
#define iCAT_atten_addr 0x400
#define iCAT_atten_pos 0
#define iCAT_atten_width 24
#define iCAT_delay_addr 0x400
#define iCAT_delay_pos 24
#define iCAT_delay_width 7
#define iCAT_replacement_amplitude_addr 0x800
#define iCAT_replacement_amplitude_pos 0
#define iCAT_replacement_amplitude_width 16
#define iCAT_atten_point_addr 0xA00
#define iCAT_atten_point_pos 0
#define iCAT_atten_point_width 16
#define iCAT_tcomp_segment_endpoint_addr 0x2000
#define iCAT_tcomp_segment_endpoint_pos 0
#define iCAT_tcomp_segment_endpoint_width 16
#endif
