//@copy-c-declaration /*
//@copy-c-declaration *
//@copy-c-declaration * Varian,Inc. All Rights Reserved.
//@copy-c-declaration * This software contains proprietary and confidential
//@copy-c-declaration * information of Varian, Inc. and its contributors.
//@copy-c-declaration * Use, disclosure and reproduction is prohibited without
//@copy-c-declaration * prior consent.
//@copy-c-declaration */
//@copy-c-declaration /*
//@copy-c-declaration *  Author: Greg Brissey  5/06/2004
//@copy-c-declaration */

//@copy-c-declaration #include "NDDS_Obj.h"


//@copy-c-declaration /* topic name form */
//@copy-c-declaration /* topic names form: ?/lock1/cmdstrm, lock1/?/cmdstrm */

const string LOCK_PUB_FID_TOPIC_FORMAT_STR = "lock/fid";
const string SUB_FID_TOPIC_FORMAT_STR = "lock/fid";


const long LOCK_MAX_DATA = 5000;

struct Lock_FID {
        sequence<short, LOCK_MAX_DATA> lkfid;
};

//@copy-c-declaration 
//@copy-c-declaration #ifdef __cplusplus
//@copy-c-declaration     extern "C" {
//@copy-c-declaration #endif
//@copy-c-declaration 
//@copy-c-declaration extern void getLock_FIDInfo(NDDS_OBJ *pObj);
//@copy-c-declaration 
//@copy-c-declaration #ifdef __cplusplus
//@copy-c-declaration }
//@copy-c-declaration #endif
//@copy-c-declaration

// //@copy-c  /* Direct Code from Codes_Downld.x */
// //@copy-c void getLock_FIDInfo(NDDS_OBJ *pObj)
// //@copy-c {
// //@copy-c strcpy(pObj->dataTypeName,Lock_FIDNDDSType);
// //@copy-c 
// //@copy-c pObj->TypeRegisterFunc = Lock_FIDNddsRegister;
// //@copy-c pObj->TypeAllocFunc = (DataTypeAllocate) Lock_FIDAllocate;
// //@copy-c pObj->TypeSizeFunc = Lock_FIDMaxSize;
// //@copy-c }

