/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
#ifndef __LOCK_REG_H__
#define __LOCK_REG_H__
#define LOCK_CHECKSUM 43156
#define LOCK_ID 0x80000
#define LOCK_InterruptStatus 0x80004
#define LOCK_InterruptEnable 0x80008
#define LOCK_InterruptClear 0x8000C
#define LOCK_TransmitPhase 0x80010
#define LOCK_TransmitPower 0x80014
#define LOCK_ReceiverGain 0x80018
#define LOCK_LockAttenuation 0x8001C
#define LOCK_LockHiLow 0x80020
#define LOCK_Locked 0x80024
#define LOCK_SeqGenEnable 0x80028
#define LOCK_TransmitterStart 0x8002C
#define LOCK_TransmitterStop 0x80030
#define LOCK_ReceiverStart 0x80034
#define LOCK_ReceiverStop 0x80038
#define LOCK_CTCPulsePeriod 0x8003C
#define LOCK_NumCTCPulses 0x80040
#define LOCK_ChannelPhase 0x80044
#define LOCK_ChannelPulseWidth 0x80048
#define LOCK_ADCSpare 0x8004C
#define LOCK_ADCBufferPointer 0x80050
#define LOCK_ADC_Count0 0x80054
#define LOCK_ADC_Count1 0x80058
#define LOCK_DDSReset 0x8005C
#define LOCK_DDSFrequencyUpdate 0x80060
#define LOCK_DDSFrequencyUpdateEnable 0x80064
#define LOCK_DDSFrequencyUpdateOutput 0x80068
#define LOCK_ADCBuffer0 0x90000
#define LOCK_ADCBuffer1 0xA0000
#define LOCK_ID_addr 0x80000
#define LOCK_ID_pos 0
#define LOCK_ID_width 4
#define LOCK_revision_addr 0x80000
#define LOCK_revision_pos 4
#define LOCK_revision_width 4
#define LOCK_checksum_addr 0x80000
#define LOCK_checksum_pos 8
#define LOCK_checksum_width 16
#define LOCK_fail_int_status_addr 0x80004
#define LOCK_fail_int_status_pos 0
#define LOCK_fail_int_status_width 1
#define LOCK_warn_int_status_addr 0x80004
#define LOCK_warn_int_status_pos 1
#define LOCK_warn_int_status_width 1
#define LOCK_adc_overflow_int_status_addr 0x80004
#define LOCK_adc_overflow_int_status_pos 2
#define LOCK_adc_overflow_int_status_width 1
#define LOCK_adc_buffer_complete_int_0_status_addr 0x80004
#define LOCK_adc_buffer_complete_int_0_status_pos 3
#define LOCK_adc_buffer_complete_int_0_status_width 1
#define LOCK_adc_buffer_complete_int_1_status_addr 0x80004
#define LOCK_adc_buffer_complete_int_1_status_pos 4
#define LOCK_adc_buffer_complete_int_1_status_width 1
#define LOCK_fail_int_enable_addr 0x80008
#define LOCK_fail_int_enable_pos 0
#define LOCK_fail_int_enable_width 1
#define LOCK_warn_int_enable_addr 0x80008
#define LOCK_warn_int_enable_pos 1
#define LOCK_warn_int_enable_width 1
#define LOCK_adc_overflow_int_enable_addr 0x80008
#define LOCK_adc_overflow_int_enable_pos 2
#define LOCK_adc_overflow_int_enable_width 1
#define LOCK_adc_buffer_complete_int_0_enable_addr 0x80008
#define LOCK_adc_buffer_complete_int_0_enable_pos 3
#define LOCK_adc_buffer_complete_int_0_enable_width 1
#define LOCK_adc_buffer_complete_int_1_enable_addr 0x80008
#define LOCK_adc_buffer_complete_int_1_enable_pos 4
#define LOCK_adc_buffer_complete_int_1_enable_width 1
#define LOCK_fail_int_clear_addr 0x8000C
#define LOCK_fail_int_clear_pos 0
#define LOCK_fail_int_clear_width 1
#define LOCK_warn_int_clear_addr 0x8000C
#define LOCK_warn_int_clear_pos 1
#define LOCK_warn_int_clear_width 1
#define LOCK_adc_overflow_int_clear_addr 0x8000C
#define LOCK_adc_overflow_int_clear_pos 2
#define LOCK_adc_overflow_int_clear_width 1
#define LOCK_adc_buffer_complete_int_0_clear_addr 0x8000C
#define LOCK_adc_buffer_complete_int_0_clear_pos 3
#define LOCK_adc_buffer_complete_int_0_clear_width 1
#define LOCK_adc_buffer_complete_int_1_clear_addr 0x8000C
#define LOCK_adc_buffer_complete_int_1_clear_pos 4
#define LOCK_adc_buffer_complete_int_1_clear_width 1
#define LOCK_tx_phase_addr 0x80010
#define LOCK_tx_phase_pos 0
#define LOCK_tx_phase_width 8
#define LOCK_tx_power_addr 0x80014
#define LOCK_tx_power_pos 0
#define LOCK_tx_power_width 8
#define LOCK_rx_gain_addr 0x80018
#define LOCK_rx_gain_pos 0
#define LOCK_rx_gain_width 8
#define LOCK_lock_attenuation_addr 0x8001C
#define LOCK_lock_attenuation_pos 0
#define LOCK_lock_attenuation_width 1
#define LOCK_lock_gain_hi_lo_addr 0x80020
#define LOCK_lock_gain_hi_lo_pos 0
#define LOCK_lock_gain_hi_lo_width 1
#define LOCK_locked_addr 0x80024
#define LOCK_locked_pos 0
#define LOCK_locked_width 1
#define LOCK_seq_gen_enable_addr 0x80028
#define LOCK_seq_gen_enable_pos 0
#define LOCK_seq_gen_enable_width 1
#define LOCK_tx_start_addr 0x8002C
#define LOCK_tx_start_pos 0
#define LOCK_tx_start_width 32
#define LOCK_tx_stop_addr 0x80030
#define LOCK_tx_stop_pos 0
#define LOCK_tx_stop_width 32
#define LOCK_rx_start_addr 0x80034
#define LOCK_rx_start_pos 0
#define LOCK_rx_start_width 32
#define LOCK_rx_stop_addr 0x80038
#define LOCK_rx_stop_pos 0
#define LOCK_rx_stop_width 32
#define LOCK_ctc_period_addr 0x8003C
#define LOCK_ctc_period_pos 0
#define LOCK_ctc_period_width 16
#define LOCK_num_ctc_pulses_addr 0x80040
#define LOCK_num_ctc_pulses_pos 0
#define LOCK_num_ctc_pulses_width 16
#define LOCK_channel_phase_addr 0x80044
#define LOCK_channel_phase_pos 0
#define LOCK_channel_phase_width 16
#define LOCK_channel_pulse_width_addr 0x80048
#define LOCK_channel_pulse_width_pos 0
#define LOCK_channel_pulse_width_width 16
#define LOCK_adc_spare_addr 0x8004C
#define LOCK_adc_spare_pos 0
#define LOCK_adc_spare_width 2
#define LOCK_sample_block_select_addr 0x80050
#define LOCK_sample_block_select_pos 0
#define LOCK_sample_block_select_width 1
#define LOCK_adc_count0_addr 0x80054
#define LOCK_adc_count0_pos 0
#define LOCK_adc_count0_width 13
#define LOCK_adc_count1_addr 0x80058
#define LOCK_adc_count1_pos 0
#define LOCK_adc_count1_width 13
#define LOCK_dds_reset_addr 0x8005C
#define LOCK_dds_reset_pos 0
#define LOCK_dds_reset_width 1
#define LOCK_dds_update_addr 0x80060
#define LOCK_dds_update_pos 0
#define LOCK_dds_update_width 1
#define LOCK_dds_update_en_addr 0x80064
#define LOCK_dds_update_en_pos 0
#define LOCK_dds_update_en_width 1
#define LOCK_dds_update_out_addr 0x80068
#define LOCK_dds_update_out_pos 0
#define LOCK_dds_update_out_width 1
#define LOCK_real_data0_addr 0x90000
#define LOCK_real_data0_pos 0
#define LOCK_real_data0_width 16
#define LOCK_imaginary_data0_addr 0x90000
#define LOCK_imaginary_data0_pos 16
#define LOCK_imaginary_data0_width 16
#define LOCK_real_data1_addr 0xA0000
#define LOCK_real_data1_pos 0
#define LOCK_real_data1_width 16
#define LOCK_imaginary_data1_addr 0xA0000
#define LOCK_imaginary_data1_pos 16
#define LOCK_imaginary_data1_width 16
#endif
