/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
#ifndef MASTER_H
#define MASTER_H
#include "fpga.h"
/*
#ifndef get_field
  #define get_field(fpga,field) \
    ((*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))>> \
    fpga##_##field##_pos) & (((fpga##_##field##_width<32) ? (1<<fpga##_##field##_width):0)-1))
#endif
#ifndef set_field
  #define set_field(fpga,field,value) \
    ((*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))) = \
    (*((volatile unsigned *)(fpga##_BASE + fpga##_##field##_addr))) & \
    ~((((fpga##_##field##_width<32)?(1<<fpga##_##field##_width):0)-1)<<fpga##_##field##_pos) | \
    ((value&(((fpga##_##field##_width<32)?(1<<fpga##_##field##_width):0)-1))<<fpga##_##field##_pos))
#endif
*/
#define MASTER_CHECKSUM 21257
#define MASTER_ID 0x0
#define MASTER_LED 0x4
#define MASTER_BoardAddress 0x8
#define MASTER_InterfaceType 0xc
#define MASTER_Failure 0x10
#define MASTER_DMARequest 0x14
#define MASTER_SCLKClockControl 0x18
#define MASTER_SCLKClockStatus 0x1c
#define MASTER_FIFOControl 0x20
#define MASTER_FIFOStatus 0x24
#define MASTER_InstructionFIFOHighThreshold 0x28
#define MASTER_InstructionFIFOLowThreshold 0x2c
#define MASTER_InstructionFIFOCount 0x30
#define MASTER_DataFIFOCount 0x34
#define MASTER_ClearCumulativeDuration 0x38
#define MASTER_CumulativeDurationLow 0x3c
#define MASTER_CumulativeDurationHigh 0x40
#define MASTER_J1COutput 0x44
#define MASTER_J1CEnable 0x48
#define MASTER_J1CInput 0x4c
#define MASTER_J2COutput 0x50
#define MASTER_J2CEnable 0x54
#define MASTER_J2CInput 0x58
#define MASTER_ExternalTimebaseSelect 0x5c
#define MASTER_InterruptStatus 0x60
#define MASTER_InterruptEnable 0x64
#define MASTER_InterruptClear 0x68
#define MASTER_SYNCClockControl 0x6c
#define MASTER_SYNCClockStatus 0x70
#define MASTER_ClearExtTrigSclkCumulativeDuration 0x74
#define MASTER_ExtTrigSclkCumulativeDurationLow 0x78
#define MASTER_ExtTrigSclkCumulativeDurationHigh 0x7c
#define MASTER_ClearExtTrigCumulativeDuration 0x80
#define MASTER_ExtTrigCumulativeDurationLow 0x84
#define MASTER_ExtTrigCumulativeDurationHigh 0x88
#define MASTER_InstructionFifoCountTotal 0x8c
#define MASTER_ClearInstructionFifoCountTotal 0x90
#define MASTER_InvalidOpcode 0x94
#define MASTER_SamplePresent 0x98
#define MASTER_SpinnerPulseSelect 0x9c
#define MASTER_SpinnerPhase 0xa0
#define MASTER_SpinnerEnable 0xa4
#define MASTER_SpinnerSpeed 0xa8
#define MASTER_SpinnerCount 0xac
#define MASTER_SampledSpinnerSpeed 0xb0
#define MASTER_SpinnerCountThreshold 0xb4
#define MASTER_DebounceThreshold 0xb8
#define MASTER_PulseGenerationEnable 0xbc
#define MASTER_SpinPulseLow 0xc0
#define MASTER_SpinPulsePeriod 0xc4
#define MASTER_TimerPeriod 0xc8
#define MASTER_SPIData0 0xcc
#define MASTER_SPIConfig0 0xd0
#define MASTER_SPIStart0 0xd4
#define MASTER_SPIBusy0 0xd8
#define MASTER_SPIReadData0 0xdc
#define MASTER_SPIData1 0xe0
#define MASTER_SPIConfig1 0xe4
#define MASTER_SPIStart1 0xe8
#define MASTER_SPIBusy1 0xec
#define MASTER_SPIReadData1 0xf0
#define MASTER_SPIData2 0xf4
#define MASTER_SPIConfig2 0xf8
#define MASTER_SPIStart2 0xfc
#define MASTER_SPIBusy2 0x100
#define MASTER_SPIReadData2 0x104
#define MASTER_SoftwareGates 0x108
#define MASTER_SoftwareSpi0 0x10c
#define MASTER_SoftwareSpi1 0x110
#define MASTER_SoftwareSpi2 0x114
#define MASTER_SoftwareAUX 0x118
#define MASTER_SoftwareAUXReset 0x11c
#define MASTER_SoftwareAUXStrobe 0x120
#define MASTER_FIFOOutputSelect 0x124
#define MASTER_FIFOGates 0x128
#define MASTER_FIFOSpi0 0x12c
#define MASTER_FIFOSpi1 0x130
#define MASTER_FIFOSpi2 0x134
#define MASTER_FIFOAUX 0x138
#define MASTER_AUXRead 0x13c
#define MASTER_Duration 0x140
#define MASTER_Gates 0x144
#define MASTER_ExtTime 0x148
#define MASTER_Spi0 0x14c
#define MASTER_Spi1 0x150
#define MASTER_Spi2 0x154
#define MASTER_FIFOInstructionWrite 0x158
#define MASTER_LogicAnalyzerConfig 0x15c
#define MASTER_LogicAnalyzerStatus 0x160
#define MASTER_LogicAnalyzerChecksum 0x164
#define MASTER_LogicAnalyzerAddress 0x168
#define MASTER_LogicAnalyzerSampleData 0x16c
#define MASTER_ID_addr 0x0
#define MASTER_ID_pos 0
#define MASTER_ID_width 4
#define MASTER_revision_addr 0x0
#define MASTER_revision_pos 4
#define MASTER_revision_width 4
#define MASTER_checksum_addr 0x0
#define MASTER_checksum_pos 8
#define MASTER_checksum_width 16
#define MASTER_led_addr 0x4
#define MASTER_led_pos 0
#define MASTER_led_width 6
#define MASTER_bd_addr_addr 0x8
#define MASTER_bd_addr_pos 0
#define MASTER_bd_addr_width 5
#define MASTER_type_addr_addr 0xc
#define MASTER_type_addr_pos 0
#define MASTER_type_addr_width 3
#define MASTER_sw_failure_addr 0x10
#define MASTER_sw_failure_pos 0
#define MASTER_sw_failure_width 1
#define MASTER_sw_warning_addr 0x10
#define MASTER_sw_warning_pos 1
#define MASTER_sw_warning_width 1
#define MASTER_dma_request_addr 0x14
#define MASTER_dma_request_pos 0
#define MASTER_dma_request_width 1
#define MASTER_sclk_rst_addr 0x18
#define MASTER_sclk_rst_pos 0
#define MASTER_sclk_rst_width 1
#define MASTER_sclk_psincdec_addr 0x18
#define MASTER_sclk_psincdec_pos 1
#define MASTER_sclk_psincdec_width 1
#define MASTER_sclk_psen_addr 0x18
#define MASTER_sclk_psen_pos 2
#define MASTER_sclk_psen_width 1
#define MASTER_sclk_psclk_addr 0x18
#define MASTER_sclk_psclk_pos 3
#define MASTER_sclk_psclk_width 1
#define MASTER_sclk_locked_addr 0x1c
#define MASTER_sclk_locked_pos 0
#define MASTER_sclk_locked_width 1
#define MASTER_sclk_psdone_addr 0x1c
#define MASTER_sclk_psdone_pos 1
#define MASTER_sclk_psdone_width 1
#define MASTER_sclk_status_addr 0x1c
#define MASTER_sclk_status_pos 2
#define MASTER_sclk_status_width 3
#define MASTER_fifo_start_addr 0x20
#define MASTER_fifo_start_pos 0
#define MASTER_fifo_start_width 1
#define MASTER_fifo_sync_start_addr 0x20
#define MASTER_fifo_sync_start_pos 1
#define MASTER_fifo_sync_start_width 1
#define MASTER_fifo_reset_addr 0x20
#define MASTER_fifo_reset_pos 2
#define MASTER_fifo_reset_width 1
#define MASTER_fifo_active_addr 0x24
#define MASTER_fifo_active_pos 0
#define MASTER_fifo_active_width 1
#define MASTER_instruction_fifo_high_threshold_addr 0x28
#define MASTER_instruction_fifo_high_threshold_pos 0
#define MASTER_instruction_fifo_high_threshold_width 10
#define MASTER_instruction_fifo_low_threshold_addr 0x2c
#define MASTER_instruction_fifo_low_threshold_pos 0
#define MASTER_instruction_fifo_low_threshold_width 10
#define MASTER_instruction_fifo_count_addr 0x30
#define MASTER_instruction_fifo_count_pos 0
#define MASTER_instruction_fifo_count_width 10
#define MASTER_data_fifo_count_addr 0x34
#define MASTER_data_fifo_count_pos 0
#define MASTER_data_fifo_count_width 9
#define MASTER_clear_cumulative_duration_addr 0x38
#define MASTER_clear_cumulative_duration_pos 0
#define MASTER_clear_cumulative_duration_width 1
#define MASTER_cumulative_duration_low_addr 0x3c
#define MASTER_cumulative_duration_low_pos 0
#define MASTER_cumulative_duration_low_width 32
#define MASTER_cumulative_duration_high_addr 0x40
#define MASTER_cumulative_duration_high_pos 0
#define MASTER_cumulative_duration_high_width 32
#define MASTER_J1_C_out_addr 0x44
#define MASTER_J1_C_out_pos 0
#define MASTER_J1_C_out_width 32
#define MASTER_J1_C_en_addr 0x48
#define MASTER_J1_C_en_pos 0
#define MASTER_J1_C_en_width 32
#define MASTER_J1_C_addr 0x4c
#define MASTER_J1_C_pos 0
#define MASTER_J1_C_width 32
#define MASTER_J2_C_out_addr 0x50
#define MASTER_J2_C_out_pos 0
#define MASTER_J2_C_out_width 32
#define MASTER_J2_C_en_addr 0x54
#define MASTER_J2_C_en_pos 0
#define MASTER_J2_C_en_width 32
#define MASTER_J2_C_addr 0x58
#define MASTER_J2_C_pos 0
#define MASTER_J2_C_width 32
#define MASTER_ext_timebase_select_addr 0x5c
#define MASTER_ext_timebase_select_pos 0
#define MASTER_ext_timebase_select_width 1
#define MASTER_fifo_overflow_status_addr 0x60
#define MASTER_fifo_overflow_status_pos 0
#define MASTER_fifo_overflow_status_width 1
#define MASTER_fifo_underflow_status_addr 0x60
#define MASTER_fifo_underflow_status_pos 1
#define MASTER_fifo_underflow_status_width 1
#define MASTER_fifo_finished_status_addr 0x60
#define MASTER_fifo_finished_status_pos 2
#define MASTER_fifo_finished_status_width 1
#define MASTER_fifo_started_status_addr 0x60
#define MASTER_fifo_started_status_pos 3
#define MASTER_fifo_started_status_width 1
#define MASTER_sw_int_status_addr 0x60
#define MASTER_sw_int_status_pos 4
#define MASTER_sw_int_status_width 4
#define MASTER_fail_int_status_addr 0x60
#define MASTER_fail_int_status_pos 8
#define MASTER_fail_int_status_width 1
#define MASTER_warn_int_status_addr 0x60
#define MASTER_warn_int_status_pos 9
#define MASTER_warn_int_status_width 1
#define MASTER_data_fifo_almost_empty_status_addr 0x60
#define MASTER_data_fifo_almost_empty_status_pos 10
#define MASTER_data_fifo_almost_empty_status_width 1
#define MASTER_instr_fifo_almost_full_status_addr 0x60
#define MASTER_instr_fifo_almost_full_status_pos 11
#define MASTER_instr_fifo_almost_full_status_width 1
#define MASTER_invalid_opcode_int_status_addr 0x60
#define MASTER_invalid_opcode_int_status_pos 12
#define MASTER_invalid_opcode_int_status_width 1
#define MASTER_probe_id_int_status_addr 0x60
#define MASTER_probe_id_int_status_pos 13
#define MASTER_probe_id_int_status_width 1
#define MASTER_tune_int_status_addr 0x60
#define MASTER_tune_int_status_pos 14
#define MASTER_tune_int_status_width 1
#define MASTER_uart_int_status_addr 0x60
#define MASTER_uart_int_status_pos 15
#define MASTER_uart_int_status_width 4
#define MASTER_timer_int_status_addr 0x60
#define MASTER_timer_int_status_pos 19
#define MASTER_timer_int_status_width 1
#define MASTER_eject_switch_int_status_addr 0x60
#define MASTER_eject_switch_int_status_pos 20
#define MASTER_eject_switch_int_status_width 1
#define MASTER_pneumatic_fault_int_status_addr 0x60
#define MASTER_pneumatic_fault_int_status_pos 21
#define MASTER_pneumatic_fault_int_status_width 1
#define MASTER_spi_failed_busy0_status_addr 0x60
#define MASTER_spi_failed_busy0_status_pos 22
#define MASTER_spi_failed_busy0_status_width 1
#define MASTER_spi_failed_busy1_status_addr 0x60
#define MASTER_spi_failed_busy1_status_pos 23
#define MASTER_spi_failed_busy1_status_width 1
#define MASTER_spi_failed_busy2_status_addr 0x60
#define MASTER_spi_failed_busy2_status_pos 24
#define MASTER_spi_failed_busy2_status_width 1
#define MASTER_spinner_int_status_addr 0x60
#define MASTER_spinner_int_status_pos 25
#define MASTER_spinner_int_status_width 1
#define MASTER_fifo_overflow_enable_addr 0x64
#define MASTER_fifo_overflow_enable_pos 0
#define MASTER_fifo_overflow_enable_width 1
#define MASTER_fifo_underflow_enable_addr 0x64
#define MASTER_fifo_underflow_enable_pos 1
#define MASTER_fifo_underflow_enable_width 1
#define MASTER_fifo_finished_enable_addr 0x64
#define MASTER_fifo_finished_enable_pos 2
#define MASTER_fifo_finished_enable_width 1
#define MASTER_fifo_started_enable_addr 0x64
#define MASTER_fifo_started_enable_pos 3
#define MASTER_fifo_started_enable_width 1
#define MASTER_sw_int_enable_addr 0x64
#define MASTER_sw_int_enable_pos 4
#define MASTER_sw_int_enable_width 4
#define MASTER_fail_int_enable_addr 0x64
#define MASTER_fail_int_enable_pos 8
#define MASTER_fail_int_enable_width 1
#define MASTER_warn_int_enable_addr 0x64
#define MASTER_warn_int_enable_pos 9
#define MASTER_warn_int_enable_width 1
#define MASTER_data_fifo_almost_empty_enable_addr 0x64
#define MASTER_data_fifo_almost_empty_enable_pos 10
#define MASTER_data_fifo_almost_empty_enable_width 1
#define MASTER_instr_fifo_almost_full_enable_addr 0x64
#define MASTER_instr_fifo_almost_full_enable_pos 11
#define MASTER_instr_fifo_almost_full_enable_width 1
#define MASTER_invalid_opcode_int_enable_addr 0x64
#define MASTER_invalid_opcode_int_enable_pos 12
#define MASTER_invalid_opcode_int_enable_width 1
#define MASTER_probe_id_int_enable_addr 0x64
#define MASTER_probe_id_int_enable_pos 13
#define MASTER_probe_id_int_enable_width 1
#define MASTER_tune_int_enable_addr 0x64
#define MASTER_tune_int_enable_pos 14
#define MASTER_tune_int_enable_width 1
#define MASTER_uart_int_enable_addr 0x64
#define MASTER_uart_int_enable_pos 15
#define MASTER_uart_int_enable_width 4
#define MASTER_timer_int_enable_addr 0x64
#define MASTER_timer_int_enable_pos 19
#define MASTER_timer_int_enable_width 1
#define MASTER_eject_switch_int_enable_addr 0x64
#define MASTER_eject_switch_int_enable_pos 20
#define MASTER_eject_switch_int_enable_width 1
#define MASTER_pneumatic_fault_int_enable_addr 0x64
#define MASTER_pneumatic_fault_int_enable_pos 21
#define MASTER_pneumatic_fault_int_enable_width 1
#define MASTER_spi_failed_busy0_enable_addr 0x64
#define MASTER_spi_failed_busy0_enable_pos 22
#define MASTER_spi_failed_busy0_enable_width 1
#define MASTER_spi_failed_busy1_enable_addr 0x64
#define MASTER_spi_failed_busy1_enable_pos 23
#define MASTER_spi_failed_busy1_enable_width 1
#define MASTER_spi_failed_busy2_enable_addr 0x64
#define MASTER_spi_failed_busy2_enable_pos 24
#define MASTER_spi_failed_busy2_enable_width 1
#define MASTER_spinner_int_enable_addr 0x64
#define MASTER_spinner_int_enable_pos 25
#define MASTER_spinner_int_enable_width 1
#define MASTER_fifo_overflow_clear_addr 0x68
#define MASTER_fifo_overflow_clear_pos 0
#define MASTER_fifo_overflow_clear_width 1
#define MASTER_fifo_underflow_clear_addr 0x68
#define MASTER_fifo_underflow_clear_pos 1
#define MASTER_fifo_underflow_clear_width 1
#define MASTER_fifo_finished_clear_addr 0x68
#define MASTER_fifo_finished_clear_pos 2
#define MASTER_fifo_finished_clear_width 1
#define MASTER_fifo_started_clear_addr 0x68
#define MASTER_fifo_started_clear_pos 3
#define MASTER_fifo_started_clear_width 1
#define MASTER_sw_int_clear_addr 0x68
#define MASTER_sw_int_clear_pos 4
#define MASTER_sw_int_clear_width 4
#define MASTER_fail_int_clear_addr 0x68
#define MASTER_fail_int_clear_pos 8
#define MASTER_fail_int_clear_width 1
#define MASTER_warn_int_clear_addr 0x68
#define MASTER_warn_int_clear_pos 9
#define MASTER_warn_int_clear_width 1
#define MASTER_data_fifo_almost_empty_clear_addr 0x68
#define MASTER_data_fifo_almost_empty_clear_pos 10
#define MASTER_data_fifo_almost_empty_clear_width 1
#define MASTER_instr_fifo_almost_full_clear_addr 0x68
#define MASTER_instr_fifo_almost_full_clear_pos 11
#define MASTER_instr_fifo_almost_full_clear_width 1
#define MASTER_invalid_opcode_int_clear_addr 0x68
#define MASTER_invalid_opcode_int_clear_pos 12
#define MASTER_invalid_opcode_int_clear_width 1
#define MASTER_probe_id_int_clear_addr 0x68
#define MASTER_probe_id_int_clear_pos 13
#define MASTER_probe_id_int_clear_width 1
#define MASTER_tune_int_clear_addr 0x68
#define MASTER_tune_int_clear_pos 14
#define MASTER_tune_int_clear_width 1
#define MASTER_uart_int_clear_addr 0x68
#define MASTER_uart_int_clear_pos 15
#define MASTER_uart_int_clear_width 4
#define MASTER_timer_int_clear_addr 0x68
#define MASTER_timer_int_clear_pos 19
#define MASTER_timer_int_clear_width 1
#define MASTER_eject_switch_int_clear_addr 0x68
#define MASTER_eject_switch_int_clear_pos 20
#define MASTER_eject_switch_int_clear_width 1
#define MASTER_pneumatic_fault_int_clear_addr 0x68
#define MASTER_pneumatic_fault_int_clear_pos 21
#define MASTER_pneumatic_fault_int_clear_width 1
#define MASTER_spi_failed_busy0_clear_addr 0x68
#define MASTER_spi_failed_busy0_clear_pos 22
#define MASTER_spi_failed_busy0_clear_width 1
#define MASTER_spi_failed_busy1_clear_addr 0x68
#define MASTER_spi_failed_busy1_clear_pos 23
#define MASTER_spi_failed_busy1_clear_width 1
#define MASTER_spi_failed_busy2_clear_addr 0x68
#define MASTER_spi_failed_busy2_clear_pos 24
#define MASTER_spi_failed_busy2_clear_width 1
#define MASTER_spinner_int_clear_addr 0x68
#define MASTER_spinner_int_clear_pos 25
#define MASTER_spinner_int_clear_width 1
#define MASTER_sync_clk_rst_addr 0x6c
#define MASTER_sync_clk_rst_pos 0
#define MASTER_sync_clk_rst_width 1
#define MASTER_sync_clk_psincdec_addr 0x6c
#define MASTER_sync_clk_psincdec_pos 1
#define MASTER_sync_clk_psincdec_width 1
#define MASTER_sync_clk_psen_addr 0x6c
#define MASTER_sync_clk_psen_pos 2
#define MASTER_sync_clk_psen_width 1
#define MASTER_sync_clk_psclk_addr 0x6c
#define MASTER_sync_clk_psclk_pos 3
#define MASTER_sync_clk_psclk_width 1
#define MASTER_sync_clk_locked_addr 0x70
#define MASTER_sync_clk_locked_pos 0
#define MASTER_sync_clk_locked_width 1
#define MASTER_sync_clk_psdone_addr 0x70
#define MASTER_sync_clk_psdone_pos 1
#define MASTER_sync_clk_psdone_width 1
#define MASTER_sync_clk_status_addr 0x70
#define MASTER_sync_clk_status_pos 2
#define MASTER_sync_clk_status_width 3
#define MASTER_clear_ext_trig_sclk_cumulative_duration_addr 0x74
#define MASTER_clear_ext_trig_sclk_cumulative_duration_pos 0
#define MASTER_clear_ext_trig_sclk_cumulative_duration_width 1
#define MASTER_ext_trig_sclk_cumulative_duration_low_addr 0x78
#define MASTER_ext_trig_sclk_cumulative_duration_low_pos 0
#define MASTER_ext_trig_sclk_cumulative_duration_low_width 32
#define MASTER_ext_trig_sclk_cumulative_duration_high_addr 0x7c
#define MASTER_ext_trig_sclk_cumulative_duration_high_pos 0
#define MASTER_ext_trig_sclk_cumulative_duration_high_width 32
#define MASTER_clear_ext_trig_cumulative_duration_addr 0x80
#define MASTER_clear_ext_trig_cumulative_duration_pos 0
#define MASTER_clear_ext_trig_cumulative_duration_width 1
#define MASTER_ext_trig_cumulative_duration_low_addr 0x84
#define MASTER_ext_trig_cumulative_duration_low_pos 0
#define MASTER_ext_trig_cumulative_duration_low_width 32
#define MASTER_ext_trig_cumulative_duration_high_addr 0x88
#define MASTER_ext_trig_cumulative_duration_high_pos 0
#define MASTER_ext_trig_cumulative_duration_high_width 32
#define MASTER_instr_fifo_count_total_addr 0x8c
#define MASTER_instr_fifo_count_total_pos 0
#define MASTER_instr_fifo_count_total_width 32
#define MASTER_clear_instr_fifo_count_total_addr 0x90
#define MASTER_clear_instr_fifo_count_total_pos 0
#define MASTER_clear_instr_fifo_count_total_width 1
#define MASTER_invalid_opcode_addr 0x94
#define MASTER_invalid_opcode_pos 0
#define MASTER_invalid_opcode_width 16
#define MASTER_samp_present_top_addr 0x98
#define MASTER_samp_present_top_pos 0
#define MASTER_samp_present_top_width 1
#define MASTER_samp_present_bot_addr 0x98
#define MASTER_samp_present_bot_pos 1
#define MASTER_samp_present_bot_width 1
#define MASTER_eject_switch_addr 0x98
#define MASTER_eject_switch_pos 2
#define MASTER_eject_switch_width 1
#define MASTER_spinner_pulse_select_addr 0x9c
#define MASTER_spinner_pulse_select_pos 0
#define MASTER_spinner_pulse_select_width 1
#define MASTER_spinner_phase_addr 0xa0
#define MASTER_spinner_phase_pos 0
#define MASTER_spinner_phase_width 32
#define MASTER_spinner_enable_addr 0xa4
#define MASTER_spinner_enable_pos 0
#define MASTER_spinner_enable_width 1
#define MASTER_spinner_speed_addr 0xa8
#define MASTER_spinner_speed_pos 0
#define MASTER_spinner_speed_width 32
#define MASTER_spinner_count_addr 0xac
#define MASTER_spinner_count_pos 0
#define MASTER_spinner_count_width 16
#define MASTER_sampled_spinner_speed_addr 0xb0
#define MASTER_sampled_spinner_speed_pos 0
#define MASTER_sampled_spinner_speed_width 32
#define MASTER_spinner_count_threshold_addr 0xb4
#define MASTER_spinner_count_threshold_pos 0
#define MASTER_spinner_count_threshold_width 16
#define MASTER_spinner_debounce_threshold_addr 0xb8
#define MASTER_spinner_debounce_threshold_pos 0
#define MASTER_spinner_debounce_threshold_width 19
#define MASTER_spin_pulse_enable_addr 0xbc
#define MASTER_spin_pulse_enable_pos 0
#define MASTER_spin_pulse_enable_width 1
#define MASTER_timer_enable_addr 0xbc
#define MASTER_timer_enable_pos 1
#define MASTER_timer_enable_width 1
#define MASTER_spin_pulse_low_addr 0xc0
#define MASTER_spin_pulse_low_pos 0
#define MASTER_spin_pulse_low_width 32
#define MASTER_spin_pulse_period_addr 0xc4
#define MASTER_spin_pulse_period_pos 0
#define MASTER_spin_pulse_period_width 32
#define MASTER_timer_period_addr 0xc8
#define MASTER_timer_period_pos 0
#define MASTER_timer_period_width 32
#define MASTER_spi_data0_addr 0xcc
#define MASTER_spi_data0_pos 0
#define MASTER_spi_data0_width 24
#define MASTER_spi_cs0N_addr 0xcc
#define MASTER_spi_cs0N_pos 24
#define MASTER_spi_cs0N_width 4
#define MASTER_spi_clk_rate_divisor0_addr 0xd0
#define MASTER_spi_clk_rate_divisor0_pos 0
#define MASTER_spi_clk_rate_divisor0_width 7
#define MASTER_spi_data_size0_addr 0xd0
#define MASTER_spi_data_size0_pos 7
#define MASTER_spi_data_size0_width 1
#define MASTER_spi_clk_polarity0_addr 0xd0
#define MASTER_spi_clk_polarity0_pos 8
#define MASTER_spi_clk_polarity0_width 1
#define MASTER_spi_clk_resting0_addr 0xd0
#define MASTER_spi_clk_resting0_pos 9
#define MASTER_spi_clk_resting0_width 1
#define MASTER_spi_start0_addr 0xd4
#define MASTER_spi_start0_pos 0
#define MASTER_spi_start0_width 1
#define MASTER_spi_busy0_addr 0xd8
#define MASTER_spi_busy0_pos 0
#define MASTER_spi_busy0_width 1
#define MASTER_spi_read0_addr 0xdc
#define MASTER_spi_read0_pos 0
#define MASTER_spi_read0_width 24
#define MASTER_spi_data1_addr 0xe0
#define MASTER_spi_data1_pos 0
#define MASTER_spi_data1_width 24
#define MASTER_spi_cs1N_addr 0xe0
#define MASTER_spi_cs1N_pos 24
#define MASTER_spi_cs1N_width 4
#define MASTER_spi_clk_rate_divisor1_addr 0xe4
#define MASTER_spi_clk_rate_divisor1_pos 0
#define MASTER_spi_clk_rate_divisor1_width 7
#define MASTER_spi_data_size1_addr 0xe4
#define MASTER_spi_data_size1_pos 7
#define MASTER_spi_data_size1_width 1
#define MASTER_spi_clk_polarity1_addr 0xe4
#define MASTER_spi_clk_polarity1_pos 8
#define MASTER_spi_clk_polarity1_width 1
#define MASTER_spi_clk_resting1_addr 0xe4
#define MASTER_spi_clk_resting1_pos 9
#define MASTER_spi_clk_resting1_width 1
#define MASTER_spi_start1_addr 0xe8
#define MASTER_spi_start1_pos 0
#define MASTER_spi_start1_width 1
#define MASTER_spi_busy1_addr 0xec
#define MASTER_spi_busy1_pos 0
#define MASTER_spi_busy1_width 1
#define MASTER_spi_read1_addr 0xf0
#define MASTER_spi_read1_pos 0
#define MASTER_spi_read1_width 24
#define MASTER_spi_data2_addr 0xf4
#define MASTER_spi_data2_pos 0
#define MASTER_spi_data2_width 24
#define MASTER_spi_cs2N_addr 0xf4
#define MASTER_spi_cs2N_pos 24
#define MASTER_spi_cs2N_width 4
#define MASTER_spi_clk_rate_divisor2_addr 0xf8
#define MASTER_spi_clk_rate_divisor2_pos 0
#define MASTER_spi_clk_rate_divisor2_width 7
#define MASTER_spi_data_size2_addr 0xf8
#define MASTER_spi_data_size2_pos 7
#define MASTER_spi_data_size2_width 1
#define MASTER_spi_clk_polarity2_addr 0xf8
#define MASTER_spi_clk_polarity2_pos 8
#define MASTER_spi_clk_polarity2_width 1
#define MASTER_spi_clk_resting2_addr 0xf8
#define MASTER_spi_clk_resting2_pos 9
#define MASTER_spi_clk_resting2_width 1
#define MASTER_spi_start2_addr 0xfc
#define MASTER_spi_start2_pos 0
#define MASTER_spi_start2_width 1
#define MASTER_spi_busy2_addr 0x100
#define MASTER_spi_busy2_pos 0
#define MASTER_spi_busy2_width 1
#define MASTER_spi_read2_addr 0x104
#define MASTER_spi_read2_pos 0
#define MASTER_spi_read2_width 24
#define MASTER_sw_gates_addr 0x108
#define MASTER_sw_gates_pos 0
#define MASTER_sw_gates_width 12
#define MASTER_sw_spi0_addr 0x10c
#define MASTER_sw_spi0_pos 0
#define MASTER_sw_spi0_width 24
#define MASTER_sw_ctl0_addr 0x10c
#define MASTER_sw_ctl0_pos 24
#define MASTER_sw_ctl0_width 4
#define MASTER_sw_updated0_addr 0x10c
#define MASTER_sw_updated0_pos 28
#define MASTER_sw_updated0_width 1
#define MASTER_sw_spi1_addr 0x110
#define MASTER_sw_spi1_pos 0
#define MASTER_sw_spi1_width 24
#define MASTER_sw_ctl1_addr 0x110
#define MASTER_sw_ctl1_pos 24
#define MASTER_sw_ctl1_width 4
#define MASTER_sw_updated1_addr 0x110
#define MASTER_sw_updated1_pos 28
#define MASTER_sw_updated1_width 1
#define MASTER_sw_spi2_addr 0x114
#define MASTER_sw_spi2_pos 0
#define MASTER_sw_spi2_width 24
#define MASTER_sw_ctl2_addr 0x114
#define MASTER_sw_ctl2_pos 24
#define MASTER_sw_ctl2_width 4
#define MASTER_sw_updated2_addr 0x114
#define MASTER_sw_updated2_pos 28
#define MASTER_sw_updated2_width 1
#define MASTER_sw_aux_addr 0x118
#define MASTER_sw_aux_pos 0
#define MASTER_sw_aux_width 12
#define MASTER_sw_aux_reset_addr 0x11c
#define MASTER_sw_aux_reset_pos 0
#define MASTER_sw_aux_reset_width 1
#define MASTER_sw_aux_strobe_addr 0x120
#define MASTER_sw_aux_strobe_pos 0
#define MASTER_sw_aux_strobe_width 1
#define MASTER_fifo_output_select_addr 0x124
#define MASTER_fifo_output_select_pos 0
#define MASTER_fifo_output_select_width 1
#define MASTER_fifo_gates_addr 0x128
#define MASTER_fifo_gates_pos 0
#define MASTER_fifo_gates_width 12
#define MASTER_fifo_spi0_addr 0x12c
#define MASTER_fifo_spi0_pos 0
#define MASTER_fifo_spi0_width 24
#define MASTER_fifo_ctl0_addr 0x12c
#define MASTER_fifo_ctl0_pos 24
#define MASTER_fifo_ctl0_width 4
#define MASTER_fifo_updated0_addr 0x12c
#define MASTER_fifo_updated0_pos 28
#define MASTER_fifo_updated0_width 1
#define MASTER_fifo_spi1_addr 0x130
#define MASTER_fifo_spi1_pos 0
#define MASTER_fifo_spi1_width 24
#define MASTER_fifo_ctl1_addr 0x130
#define MASTER_fifo_ctl1_pos 24
#define MASTER_fifo_ctl1_width 4
#define MASTER_fifo_updated1_addr 0x130
#define MASTER_fifo_updated1_pos 28
#define MASTER_fifo_updated1_width 1
#define MASTER_fifo_spi2_addr 0x134
#define MASTER_fifo_spi2_pos 0
#define MASTER_fifo_spi2_width 24
#define MASTER_fifo_ctl2_addr 0x134
#define MASTER_fifo_ctl2_pos 24
#define MASTER_fifo_ctl2_width 4
#define MASTER_fifo_updated2_addr 0x134
#define MASTER_fifo_updated2_pos 28
#define MASTER_fifo_updated2_width 1
#define MASTER_fifo_aux_addr 0x138
#define MASTER_fifo_aux_pos 0
#define MASTER_fifo_aux_width 12
#define MASTER_aux_read_addr 0x13c
#define MASTER_aux_read_pos 0
#define MASTER_aux_read_width 8
#define MASTER_holding_duration_addr 0x140
#define MASTER_holding_duration_pos 0
#define MASTER_holding_duration_width 26
#define MASTER_holding_gates_addr 0x144
#define MASTER_holding_gates_pos 0
#define MASTER_holding_gates_width 12
#define MASTER_holding_ext_time_addr 0x148
#define MASTER_holding_ext_time_pos 0
#define MASTER_holding_ext_time_width 1
#define MASTER_holding_spi0_addr 0x14c
#define MASTER_holding_spi0_pos 0
#define MASTER_holding_spi0_width 24
#define MASTER_holding_ctl0_addr 0x14c
#define MASTER_holding_ctl0_pos 24
#define MASTER_holding_ctl0_width 4
#define MASTER_holding_updated0_addr 0x14c
#define MASTER_holding_updated0_pos 28
#define MASTER_holding_updated0_width 1
#define MASTER_holding_spi1_addr 0x150
#define MASTER_holding_spi1_pos 0
#define MASTER_holding_spi1_width 24
#define MASTER_holding_ctl1_addr 0x150
#define MASTER_holding_ctl1_pos 24
#define MASTER_holding_ctl1_width 4
#define MASTER_holding_updated1_addr 0x150
#define MASTER_holding_updated1_pos 28
#define MASTER_holding_updated1_width 1
#define MASTER_holding_spi2_addr 0x154
#define MASTER_holding_spi2_pos 0
#define MASTER_holding_spi2_width 24
#define MASTER_holding_ctl2_addr 0x154
#define MASTER_holding_ctl2_pos 24
#define MASTER_holding_ctl2_width 4
#define MASTER_holding_updated2_addr 0x154
#define MASTER_holding_updated2_pos 28
#define MASTER_holding_updated2_width 1
#define MASTER_fifo_instruction_addr 0x158
#define MASTER_fifo_instruction_pos 0
#define MASTER_fifo_instruction_width 32
#define MASTER_la_trigger_select_addr 0x15c
#define MASTER_la_trigger_select_pos 0
#define MASTER_la_trigger_select_width 8
#define MASTER_la_trigger_polarity_addr 0x15c
#define MASTER_la_trigger_polarity_pos 8
#define MASTER_la_trigger_polarity_width 2
#define MASTER_la_trigger_arm_addr 0x15c
#define MASTER_la_trigger_arm_pos 10
#define MASTER_la_trigger_arm_width 1
#define MASTER_la_force_trigger_addr 0x15c
#define MASTER_la_force_trigger_pos 11
#define MASTER_la_force_trigger_width 1
#define MASTER_la_trigger_leadin_addr 0x15c
#define MASTER_la_trigger_leadin_pos 12
#define MASTER_la_trigger_leadin_width 11
#define MASTER_la_sample_divisor_addr 0x15c
#define MASTER_la_sample_divisor_pos 23
#define MASTER_la_sample_divisor_width 8
#define MASTER_la_start_data_addr 0x160
#define MASTER_la_start_data_pos 0
#define MASTER_la_start_data_width 11
#define MASTER_la_triggered_addr 0x160
#define MASTER_la_triggered_pos 11
#define MASTER_la_triggered_width 1
#define MASTER_la_checksum_addr 0x164
#define MASTER_la_checksum_pos 0
#define MASTER_la_checksum_width 16
#define MASTER_la_address_addr 0x168
#define MASTER_la_address_pos 0
#define MASTER_la_address_width 14
#define MASTER_la_data_addr 0x16c
#define MASTER_la_data_pos 0
#define MASTER_la_data_width 32
#endif
