/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
#ifndef __PFG_REG_H__
#define __PFG_REG_H__
#define PFG_CHECKSUM 32650
#define PFG_ID 0x0
#define PFG_LED 0x4
#define PFG_BoardAddress 0x8
#define PFG_InterfaceType 0xC
#define PFG_Failure 0x10
#define PFG_DMARequest 0x14
#define PFG_SCLKClockControl 0x18
#define PFG_SCLKClockStatus 0x1C
#define PFG_FIFOControl 0x20
#define PFG_FIFOStatus 0x24
#define PFG_InstructionFIFOHighThreshold 0x28
#define PFG_InstructionFIFOLowThreshold 0x2C
#define PFG_InstructionFIFOCount 0x30
#define PFG_DataFIFOCount 0x34
#define PFG_ClearCumulativeDuration 0x38
#define PFG_CumulativeDurationLow 0x3C
#define PFG_CumulativeDurationHigh 0x40
#define PFG_J1COutput 0x44
#define PFG_J1CEnable 0x48
#define PFG_J1CInput 0x4C
#define PFG_J2COutput 0x50
#define PFG_J2CEnable 0x54
#define PFG_J2CInput 0x58
#define PFG_InterruptStatus 0x5C
#define PFG_InterruptEnable 0x60
#define PFG_InterruptClear 0x64
#define PFG_ForceSync 0x68
#define PFG_SYNCSeen 0x6C
#define PFG_InstructionFifoCountTotal 0x70
#define PFG_ClearInstructionFifoCountTotal 0x74
#define PFG_InvalidInstruction 0x78
#define PFG_PFGAmpAddress 0x7C
#define PFG_PFGAmpEnable 0x80
#define PFG_PFGAmpOk 0x84
#define PFG_PFGAmpReset 0x88
#define PFG_PFGAmpResetDone 0x8C
#define PFG_PFGAmpType 0x90
#define PFG_PFGAmpBusy 0x94
#define PFG_SoftwareUpdate 0x98
#define PFG_SoftwareXAmp 0x9C
#define PFG_SoftwareYAmp 0xA0
#define PFG_SoftwareZAmp 0xA4
#define PFG_SoftwareXAmpUpdated 0xA8
#define PFG_SoftwareYAmpUpdated 0xAC
#define PFG_SoftwareZAmpUpdated 0xB0
#define PFG_SoftwareGates 0xB4
#define PFG_SoftwareUser 0xB8
#define PFG_FIFOOutputSelect 0xBC
#define PFG_FIFOXAmp 0xC0
#define PFG_FIFOYAmp 0xC4
#define PFG_FIFOZAmp 0xC8
#define PFG_FIFOXAmpUpdated 0xCC
#define PFG_FIFOYAmpUpdated 0xD0
#define PFG_FIFOZAmpUpdated 0xD4
#define PFG_FIFOGates 0xD8
#define PFG_FIFOUser 0xDC
#define PFG_Duration 0xE0
#define PFG_XAmp 0xE4
#define PFG_XAmpIncrement 0xE8
#define PFG_XAmpCount 0xEC
#define PFG_XAmpClear 0xF0
#define PFG_YAmp 0xF4
#define PFG_YAmpIncrement 0xF8
#define PFG_YAmpCount 0xFC
#define PFG_YAmpClear 0x100
#define PFG_ZAmp 0x104
#define PFG_ZAmpIncrement 0x108
#define PFG_ZAmpCount 0x10C
#define PFG_ZAmpClear 0x110
#define PFG_XAmpScale 0x114
#define PFG_XAmpScaleIncrement 0x118
#define PFG_XAmpScaleCount 0x11C
#define PFG_XAmpScaleClear 0x120
#define PFG_YAmpScale 0x124
#define PFG_YAmpScaleIncrement 0x128
#define PFG_YAmpScaleCount 0x12C
#define PFG_YAmpScaleClear 0x130
#define PFG_ZAmpScale 0x134
#define PFG_ZAmpScaleIncrement 0x138
#define PFG_ZAmpScaleCount 0x13C
#define PFG_ZAmpScaleClear 0x140
#define PFG_XAmpUpdated 0x144
#define PFG_YAmpUpdated 0x148
#define PFG_ZAmpUpdated 0x14C
#define PFG_Gates 0x150
#define PFG_User 0x154
#define PFG_FIFOInstructionWrite 0x158
#define PFG_DMAReqCount 0x15C
#define PFG_DMAReqValue 0x160
#define PFG_ID_addr 0x0
#define PFG_ID_pos 0
#define PFG_ID_width 4
#define PFG_revision_addr 0x0
#define PFG_revision_pos 4
#define PFG_revision_width 4
#define PFG_checksum_addr 0x0
#define PFG_checksum_pos 8
#define PFG_checksum_width 16
#define PFG_led_addr 0x4
#define PFG_led_pos 0
#define PFG_led_width 6
#define PFG_bd_addr_addr 0x8
#define PFG_bd_addr_pos 0
#define PFG_bd_addr_width 5
#define PFG_type_addr_addr 0xC
#define PFG_type_addr_pos 0
#define PFG_type_addr_width 3
#define PFG_sw_failure_addr 0x10
#define PFG_sw_failure_pos 0
#define PFG_sw_failure_width 1
#define PFG_sw_warning_addr 0x10
#define PFG_sw_warning_pos 1
#define PFG_sw_warning_width 1
#define PFG_dma_request_addr 0x14
#define PFG_dma_request_pos 0
#define PFG_dma_request_width 1
#define PFG_sclk_rst_addr 0x18
#define PFG_sclk_rst_pos 0
#define PFG_sclk_rst_width 1
#define PFG_sclk_psincdec_addr 0x18
#define PFG_sclk_psincdec_pos 1
#define PFG_sclk_psincdec_width 1
#define PFG_sclk_psen_addr 0x18
#define PFG_sclk_psen_pos 2
#define PFG_sclk_psen_width 1
#define PFG_sclk_psclk_addr 0x18
#define PFG_sclk_psclk_pos 3
#define PFG_sclk_psclk_width 1
#define PFG_sclk_locked_addr 0x1C
#define PFG_sclk_locked_pos 0
#define PFG_sclk_locked_width 1
#define PFG_sclk_psdone_addr 0x1C
#define PFG_sclk_psdone_pos 1
#define PFG_sclk_psdone_width 1
#define PFG_sclk_status_addr 0x1C
#define PFG_sclk_status_pos 2
#define PFG_sclk_status_width 3
#define PFG_sclk_psidle_addr 0x1C
#define PFG_sclk_psidle_pos 5
#define PFG_sclk_psidle_width 1
#define PFG_fifo_start_addr 0x20
#define PFG_fifo_start_pos 0
#define PFG_fifo_start_width 1
#define PFG_fifo_sync_start_addr 0x20
#define PFG_fifo_sync_start_pos 1
#define PFG_fifo_sync_start_width 1
#define PFG_fifo_reset_addr 0x20
#define PFG_fifo_reset_pos 2
#define PFG_fifo_reset_width 1
#define PFG_fifo_active_addr 0x24
#define PFG_fifo_active_pos 0
#define PFG_fifo_active_width 1
#define PFG_instruction_fifo_high_threshold_addr 0x28
#define PFG_instruction_fifo_high_threshold_pos 0
#define PFG_instruction_fifo_high_threshold_width 10
#define PFG_instruction_fifo_low_threshold_addr 0x2C
#define PFG_instruction_fifo_low_threshold_pos 0
#define PFG_instruction_fifo_low_threshold_width 10
#define PFG_instruction_fifo_count_addr 0x30
#define PFG_instruction_fifo_count_pos 0
#define PFG_instruction_fifo_count_width 10
#define PFG_data_fifo_count_addr 0x34
#define PFG_data_fifo_count_pos 0
#define PFG_data_fifo_count_width 9
#define PFG_clear_cumulative_duration_addr 0x38
#define PFG_clear_cumulative_duration_pos 0
#define PFG_clear_cumulative_duration_width 1
#define PFG_cumulative_duration_low_addr 0x3C
#define PFG_cumulative_duration_low_pos 0
#define PFG_cumulative_duration_low_width 32
#define PFG_cumulative_duration_high_addr 0x40
#define PFG_cumulative_duration_high_pos 0
#define PFG_cumulative_duration_high_width 32
#define PFG_J1_C_out_addr 0x44
#define PFG_J1_C_out_pos 0
#define PFG_J1_C_out_width 32
#define PFG_J1_C_en_addr 0x48
#define PFG_J1_C_en_pos 0
#define PFG_J1_C_en_width 32
#define PFG_J1_C_addr 0x4C
#define PFG_J1_C_pos 0
#define PFG_J1_C_width 32
#define PFG_J2_C_out_addr 0x50
#define PFG_J2_C_out_pos 0
#define PFG_J2_C_out_width 32
#define PFG_J2_C_en_addr 0x54
#define PFG_J2_C_en_pos 0
#define PFG_J2_C_en_width 32
#define PFG_J2_C_addr 0x58
#define PFG_J2_C_pos 0
#define PFG_J2_C_width 32
#define PFG_fifo_overflow_status_addr 0x5C
#define PFG_fifo_overflow_status_pos 0
#define PFG_fifo_overflow_status_width 1
#define PFG_fifo_underflow_status_addr 0x5C
#define PFG_fifo_underflow_status_pos 1
#define PFG_fifo_underflow_status_width 1
#define PFG_fifo_finished_status_addr 0x5C
#define PFG_fifo_finished_status_pos 2
#define PFG_fifo_finished_status_width 1
#define PFG_fifo_started_status_addr 0x5C
#define PFG_fifo_started_status_pos 3
#define PFG_fifo_started_status_width 1
#define PFG_sw_int_status_addr 0x5C
#define PFG_sw_int_status_pos 4
#define PFG_sw_int_status_width 4
#define PFG_fail_int_status_addr 0x5C
#define PFG_fail_int_status_pos 8
#define PFG_fail_int_status_width 1
#define PFG_warn_int_status_addr 0x5C
#define PFG_warn_int_status_pos 9
#define PFG_warn_int_status_width 1
#define PFG_data_fifo_almost_empty_status_addr 0x5C
#define PFG_data_fifo_almost_empty_status_pos 10
#define PFG_data_fifo_almost_empty_status_width 1
#define PFG_instr_fifo_almost_full_status_addr 0x5C
#define PFG_instr_fifo_almost_full_status_pos 11
#define PFG_instr_fifo_almost_full_status_width 1
#define PFG_invalid_opcode_int_status_addr 0x5C
#define PFG_invalid_opcode_int_status_pos 12
#define PFG_invalid_opcode_int_status_width 1
#define PFG_fifo_amp_duration_too_short_status_addr 0x5C
#define PFG_fifo_amp_duration_too_short_status_pos 13
#define PFG_fifo_amp_duration_too_short_status_width 3
#define PFG_external_sync_status_addr 0x5C
#define PFG_external_sync_status_pos 16
#define PFG_external_sync_status_width 1
#define PFG_fifo_overflow_enable_addr 0x60
#define PFG_fifo_overflow_enable_pos 0
#define PFG_fifo_overflow_enable_width 1
#define PFG_fifo_underflow_enable_addr 0x60
#define PFG_fifo_underflow_enable_pos 1
#define PFG_fifo_underflow_enable_width 1
#define PFG_fifo_finished_enable_addr 0x60
#define PFG_fifo_finished_enable_pos 2
#define PFG_fifo_finished_enable_width 1
#define PFG_fifo_started_enable_addr 0x60
#define PFG_fifo_started_enable_pos 3
#define PFG_fifo_started_enable_width 1
#define PFG_sw_int_enable_addr 0x60
#define PFG_sw_int_enable_pos 4
#define PFG_sw_int_enable_width 4
#define PFG_fail_int_enable_addr 0x60
#define PFG_fail_int_enable_pos 8
#define PFG_fail_int_enable_width 1
#define PFG_warn_int_enable_addr 0x60
#define PFG_warn_int_enable_pos 9
#define PFG_warn_int_enable_width 1
#define PFG_data_fifo_almost_empty_enable_addr 0x60
#define PFG_data_fifo_almost_empty_enable_pos 10
#define PFG_data_fifo_almost_empty_enable_width 1
#define PFG_instr_fifo_almost_full_enable_addr 0x60
#define PFG_instr_fifo_almost_full_enable_pos 11
#define PFG_instr_fifo_almost_full_enable_width 1
#define PFG_invalid_opcode_int_enable_addr 0x60
#define PFG_invalid_opcode_int_enable_pos 12
#define PFG_invalid_opcode_int_enable_width 1
#define PFG_fifo_amp_duration_too_short_enable_addr 0x60
#define PFG_fifo_amp_duration_too_short_enable_pos 13
#define PFG_fifo_amp_duration_too_short_enable_width 3
#define PFG_external_sync_enable_addr 0x60
#define PFG_external_sync_enable_pos 16
#define PFG_external_sync_enable_width 1
#define PFG_fifo_overflow_clear_addr 0x64
#define PFG_fifo_overflow_clear_pos 0
#define PFG_fifo_overflow_clear_width 1
#define PFG_fifo_underflow_clear_addr 0x64
#define PFG_fifo_underflow_clear_pos 1
#define PFG_fifo_underflow_clear_width 1
#define PFG_fifo_finished_clear_addr 0x64
#define PFG_fifo_finished_clear_pos 2
#define PFG_fifo_finished_clear_width 1
#define PFG_fifo_started_clear_addr 0x64
#define PFG_fifo_started_clear_pos 3
#define PFG_fifo_started_clear_width 1
#define PFG_sw_int_clear_addr 0x64
#define PFG_sw_int_clear_pos 4
#define PFG_sw_int_clear_width 4
#define PFG_fail_int_clear_addr 0x64
#define PFG_fail_int_clear_pos 8
#define PFG_fail_int_clear_width 1
#define PFG_warn_int_clear_addr 0x64
#define PFG_warn_int_clear_pos 9
#define PFG_warn_int_clear_width 1
#define PFG_data_fifo_almost_empty_clear_addr 0x64
#define PFG_data_fifo_almost_empty_clear_pos 10
#define PFG_data_fifo_almost_empty_clear_width 1
#define PFG_instr_fifo_almost_full_clear_addr 0x64
#define PFG_instr_fifo_almost_full_clear_pos 11
#define PFG_instr_fifo_almost_full_clear_width 1
#define PFG_invalid_opcode_int_clear_addr 0x64
#define PFG_invalid_opcode_int_clear_pos 12
#define PFG_invalid_opcode_int_clear_width 1
#define PFG_fifo_amp_duration_too_short_clear_addr 0x64
#define PFG_fifo_amp_duration_too_short_clear_pos 13
#define PFG_fifo_amp_duration_too_short_clear_width 3
#define PFG_external_sync_clear_addr 0x64
#define PFG_external_sync_clear_pos 16
#define PFG_external_sync_clear_width 1
#define PFG_force_sync_addr 0x68
#define PFG_force_sync_pos 0
#define PFG_force_sync_width 1
#define PFG_clear_sync_seen_addr 0x68
#define PFG_clear_sync_seen_pos 1
#define PFG_clear_sync_seen_width 1
#define PFG_sync_seen_addr 0x6C
#define PFG_sync_seen_pos 0
#define PFG_sync_seen_width 1
#define PFG_sync_seen2_addr 0x6C
#define PFG_sync_seen2_pos 1
#define PFG_sync_seen2_width 1
#define PFG_instr_fifo_count_total_addr 0x70
#define PFG_instr_fifo_count_total_pos 0
#define PFG_instr_fifo_count_total_width 32
#define PFG_clear_instr_fifo_count_total_addr 0x74
#define PFG_clear_instr_fifo_count_total_pos 0
#define PFG_clear_instr_fifo_count_total_width 1
#define PFG_invalid_instruction_addr 0x78
#define PFG_invalid_instruction_pos 0
#define PFG_invalid_instruction_width 32
#define PFG_pfg_amp_address_addr 0x7C
#define PFG_pfg_amp_address_pos 0
#define PFG_pfg_amp_address_width 3
#define PFG_pfg_amp_enable_addr 0x80
#define PFG_pfg_amp_enable_pos 0
#define PFG_pfg_amp_enable_width 3
#define PFG_pfg_amp_ok_addr 0x84
#define PFG_pfg_amp_ok_pos 0
#define PFG_pfg_amp_ok_width 3
#define PFG_pfg_amp_reset_addr 0x88
#define PFG_pfg_amp_reset_pos 0
#define PFG_pfg_amp_reset_width 1
#define PFG_pfg_amp_reset_done_addr 0x8C
#define PFG_pfg_amp_reset_done_pos 0
#define PFG_pfg_amp_reset_done_width 1
#define PFG_pfg_amp_type_addr 0x90
#define PFG_pfg_amp_type_pos 0
#define PFG_pfg_amp_type_width 3
#define PFG_pfg_amp_busy_addr 0x94
#define PFG_pfg_amp_busy_pos 0
#define PFG_pfg_amp_busy_width 3
#define PFG_sw_update_addr 0x98
#define PFG_sw_update_pos 0
#define PFG_sw_update_width 1
#define PFG_sw_xamp_addr 0x9C
#define PFG_sw_xamp_pos 0
#define PFG_sw_xamp_width 20
#define PFG_sw_yamp_addr 0xA0
#define PFG_sw_yamp_pos 0
#define PFG_sw_yamp_width 20
#define PFG_sw_zamp_addr 0xA4
#define PFG_sw_zamp_pos 0
#define PFG_sw_zamp_width 20
#define PFG_sw_xamp_updated_addr 0xA8
#define PFG_sw_xamp_updated_pos 0
#define PFG_sw_xamp_updated_width 1
#define PFG_sw_yamp_updated_addr 0xAC
#define PFG_sw_yamp_updated_pos 0
#define PFG_sw_yamp_updated_width 1
#define PFG_sw_zamp_updated_addr 0xB0
#define PFG_sw_zamp_updated_pos 0
#define PFG_sw_zamp_updated_width 1
#define PFG_sw_gates_addr 0xB4
#define PFG_sw_gates_pos 0
#define PFG_sw_gates_width 12
#define PFG_sw_user_addr 0xB8
#define PFG_sw_user_pos 0
#define PFG_sw_user_width 1
#define PFG_fifo_output_select_addr 0xBC
#define PFG_fifo_output_select_pos 0
#define PFG_fifo_output_select_width 1
#define PFG_fifo_xamp_addr 0xC0
#define PFG_fifo_xamp_pos 0
#define PFG_fifo_xamp_width 16
#define PFG_fifo_yamp_addr 0xC4
#define PFG_fifo_yamp_pos 0
#define PFG_fifo_yamp_width 16
#define PFG_fifo_zamp_addr 0xC8
#define PFG_fifo_zamp_pos 0
#define PFG_fifo_zamp_width 16
#define PFG_fifo_xamp_updated_addr 0xCC
#define PFG_fifo_xamp_updated_pos 0
#define PFG_fifo_xamp_updated_width 1
#define PFG_fifo_yamp_updated_addr 0xD0
#define PFG_fifo_yamp_updated_pos 0
#define PFG_fifo_yamp_updated_width 1
#define PFG_fifo_zamp_updated_addr 0xD4
#define PFG_fifo_zamp_updated_pos 0
#define PFG_fifo_zamp_updated_width 1
#define PFG_fifo_gates_addr 0xD8
#define PFG_fifo_gates_pos 0
#define PFG_fifo_gates_width 12
#define PFG_fifo_user_addr 0xDC
#define PFG_fifo_user_pos 0
#define PFG_fifo_user_width 1
#define PFG_holding_duration_addr 0xE0
#define PFG_holding_duration_pos 0
#define PFG_holding_duration_width 26
#define PFG_holding_xamp_addr 0xE4
#define PFG_holding_xamp_pos 0
#define PFG_holding_xamp_width 16
#define PFG_holding_xamp_increment_addr 0xE8
#define PFG_holding_xamp_increment_pos 0
#define PFG_holding_xamp_increment_width 16
#define PFG_holding_xamp_count_addr 0xEC
#define PFG_holding_xamp_count_pos 0
#define PFG_holding_xamp_count_width 9
#define PFG_holding_xamp_clear_addr 0xF0
#define PFG_holding_xamp_clear_pos 0
#define PFG_holding_xamp_clear_width 1
#define PFG_holding_yamp_addr 0xF4
#define PFG_holding_yamp_pos 0
#define PFG_holding_yamp_width 16
#define PFG_holding_yamp_increment_addr 0xF8
#define PFG_holding_yamp_increment_pos 0
#define PFG_holding_yamp_increment_width 16
#define PFG_holding_yamp_count_addr 0xFC
#define PFG_holding_yamp_count_pos 0
#define PFG_holding_yamp_count_width 9
#define PFG_holding_yamp_clear_addr 0x100
#define PFG_holding_yamp_clear_pos 0
#define PFG_holding_yamp_clear_width 1
#define PFG_holding_zamp_addr 0x104
#define PFG_holding_zamp_pos 0
#define PFG_holding_zamp_width 16
#define PFG_holding_zamp_increment_addr 0x108
#define PFG_holding_zamp_increment_pos 0
#define PFG_holding_zamp_increment_width 16
#define PFG_holding_zamp_count_addr 0x10C
#define PFG_holding_zamp_count_pos 0
#define PFG_holding_zamp_count_width 9
#define PFG_holding_zamp_clear_addr 0x110
#define PFG_holding_zamp_clear_pos 0
#define PFG_holding_zamp_clear_width 1
#define PFG_holding_xamp_scale_addr 0x114
#define PFG_holding_xamp_scale_pos 0
#define PFG_holding_xamp_scale_width 16
#define PFG_holding_xamp_scale_increment_addr 0x118
#define PFG_holding_xamp_scale_increment_pos 0
#define PFG_holding_xamp_scale_increment_width 16
#define PFG_holding_xamp_scale_count_addr 0x11C
#define PFG_holding_xamp_scale_count_pos 0
#define PFG_holding_xamp_scale_count_width 9
#define PFG_holding_xamp_scale_clear_addr 0x120
#define PFG_holding_xamp_scale_clear_pos 0
#define PFG_holding_xamp_scale_clear_width 1
#define PFG_holding_yamp_scale_addr 0x124
#define PFG_holding_yamp_scale_pos 0
#define PFG_holding_yamp_scale_width 16
#define PFG_holding_yamp_scale_increment_addr 0x128
#define PFG_holding_yamp_scale_increment_pos 0
#define PFG_holding_yamp_scale_increment_width 16
#define PFG_holding_yamp_scale_count_addr 0x12C
#define PFG_holding_yamp_scale_count_pos 0
#define PFG_holding_yamp_scale_count_width 9
#define PFG_holding_yamp_scale_clear_addr 0x130
#define PFG_holding_yamp_scale_clear_pos 0
#define PFG_holding_yamp_scale_clear_width 1
#define PFG_holding_zamp_scale_addr 0x134
#define PFG_holding_zamp_scale_pos 0
#define PFG_holding_zamp_scale_width 16
#define PFG_holding_zamp_scale_increment_addr 0x138
#define PFG_holding_zamp_scale_increment_pos 0
#define PFG_holding_zamp_scale_increment_width 16
#define PFG_holding_zamp_scale_count_addr 0x13C
#define PFG_holding_zamp_scale_count_pos 0
#define PFG_holding_zamp_scale_count_width 9
#define PFG_holding_zamp_scale_clear_addr 0x140
#define PFG_holding_zamp_scale_clear_pos 0
#define PFG_holding_zamp_scale_clear_width 1
#define PFG_holding_xamp_updated_addr 0x144
#define PFG_holding_xamp_updated_pos 0
#define PFG_holding_xamp_updated_width 1
#define PFG_holding_yamp_updated_addr 0x148
#define PFG_holding_yamp_updated_pos 0
#define PFG_holding_yamp_updated_width 1
#define PFG_holding_zamp_updated_addr 0x14C
#define PFG_holding_zamp_updated_pos 0
#define PFG_holding_zamp_updated_width 1
#define PFG_holding_gates_addr 0x150
#define PFG_holding_gates_pos 0
#define PFG_holding_gates_width 12
#define PFG_holding_user_addr 0x154
#define PFG_holding_user_pos 0
#define PFG_holding_user_width 1
#define PFG_fifo_instruction_addr 0x158
#define PFG_fifo_instruction_pos 0
#define PFG_fifo_instruction_width 32
#define PFG_dmareq_count_addr 0x15C
#define PFG_dmareq_count_pos 0
#define PFG_dmareq_count_width 32
#define PFG_dmareq_value_addr 0x160
#define PFG_dmareq_value_pos 0
#define PFG_dmareq_value_width 2
#endif
