#!/bin/bash

# set -x

dir="/Applications/OpenVnmrJ.app/Contents/Resources/OpenVnmrJ"
osVer=$(sw_vers -productVersion | tr "." " " | awk '{print $1}')
osSubVer=$(sw_vers -productVersion | tr "." " " | awk '{print $2}')

if ! [[ $osVer -gt 10 ]] && ! [[ $osSubVer -ge 15 ]]; then
   rm -rf /vnmr
   ln -s $dir /vnmr
else
   if [[ -f /etc/synthetic.conf ]]; then
      grep "/Applications/OpenVnmrJ.app/Contents/Resources/OpenVnmrJ" /etc/synthetic.conf >& /dev/null
      if [[ $? -ne 0 ]]; then
         grep -w vnmr /etc/synthetic.conf
         if [[ $? -eq 0 ]]; then
            grep -vw vnmr /etc/synthetic.conf > /etc/synthetic
            mv /etc/synthetic /etc/synthetic.conf
         fi
         printf "vnmr\t%s\n" $dir >> /etc/synthetic.conf  
      fi
   else
      printf "vnmr\t%s\n" $dir > /etc/synthetic.conf  
   fi
fi

codesign -s - $dir/bin/Vnmrbg

username=$(/usr/bin/stat -f%Su /dev/console)
chown -R -L $username $dir
export vnmrsystem=$dir
su $username $dir/bin/makeuser $username y
$dir/bin/ovjuser $username
cmd="source $dir/user_templates/.vnmrenvsh; $dir/bin/Vnmrbg -mback -n1 -s config auto; cd ~/vnmrsys; rm -f vnmr;  ln -s $dir vnmr"
su $username -c "$cmd"
# /vnmr/bin/dbsetup root /vnmr 
appdir="/Applications/OpenVnmrJ.app"
if [[ -d $appdir/OrIgCoNtEnTs ]]; then
   path=$appdir/OrIgCoNtEnTs/Resources/OpenVnmrJ
   if [[ -d  $path/fidlib/Ethylindanone ]]; then
      rm -rf $dir/fidlib
      mv $path/fidlib $dir/fidlib
   fi
   if [[ -d  $path/help ]]; then
      mv $path/help $dir/help
   fi
   if [[ -d  $path/nmrpipe ]]; then
      mv $path/nmrpipe $dir/nmrpipe
   fi
   rm -rf $appdir/OrIgCoNtEnTs
   rm -f /tmp/vnmrOrigPath
   chown -R -L $username $dir
fi
if [[ -f /tmp/vnmrOrigPath ]]; then
   path=$(cat /tmp/vnmrOrigPath)
   rm /tmp/vnmrOrigPath
   if [[ -d  $path/fidlib/Ethylindanone ]]; then
      rm -rf $dir/fidlib
      (cd $path; tar cf - fidlib | (cd $dir && tar xpf -))
   fi
   if [[ -d  $path/help ]]; then
      (cd $path; tar cf - help | (cd $dir && tar xpf -))
   fi
   if [[ -d  $path/nmrpipe ]]; then
      (cd $path; tar cf - nmrpipe | (cd $dir && tar xpf -))
   fi
   chown -R -L $username $dir
fi
