/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */

/* #define _POSIX_SOURCE /* defined when source is waited tobe POSIX-compliant */
/* #define _SYSV_SOURCE /* defined when source is System V */
/* #ifdef __STDC__ /* used to determine if using an ANSI compiler */


#ifndef INCinstrWvDefinesh
#define INCinstrWvDefinesh

/* FIFO WINDVIEW EVENTS */
#define EVENT_FIFO_WRDBUF	1000
#define EVENT_FIFO_AMFULL	1
#define EVENT_FIFO_AMMT		2
#define EVENT_FIFOSTART		3
#define EVENT_FIFO_STOP		4
#define EVENT_FIFO_UNDERFLOW	5
#define EVENT_FIFOSTRTEMPTY	6
#define EVENT_FIFOSTRTHALT	7
#define EVENT_NETBLERROR	8
#define EVENT_FORPERROR		9
#define EVENT_FIFOSTARTONSYNC	10
#define EVENT_FIFORESET		11
#define EVENT_FIFO_NETBAP	12
#define EVENT_APTIMEOUT		13
#define EVENT_FIFO_TAGITRP	14
#define EVENT_APFIFO		15
#define EVENT_FIFO_WT4STOP	16
#define EVENT_FIFO_WT4STOPITR	17
#define EVENT_FIFO_NOSTUFF	18
#define EVENT_FIFO_CLRNOSTUFF   19

/* STM WINDVIEW EVENTS */
#define EVENT_STM_ALLOC_BLKS		2000
#define EVENT_STM_CT_COMPLETE		20
#define EVENT_STM_IMMEDIATE		21
#define EVENT_STM_NP_INCOMPLETE		22
#define EVENT_STM_MAX_SUM		23
#define EVENT_STM_ALLOC_BLK		24
#define EVENT_STM_RESET			25
#define EVENT_STM_PSEUDO_CT		26
#define EVENT_ADM_OVERFLOW		27
#define EVENT_ADM_OVRFLW_CLR		28
#define EVENT_STM_MUTEX_TAKE		701
#define EVENT_STM_MUTEX_GIVE		702

/* ADC WINDVIEW EVENTS */
#define EVENT_ADC_OVERFLOW		30
#define EVENT_RCV_OVERFLOW		31
#define EVENT_ADC_RESET			32
#define EVENT_ADC_OVEFLW_CLR		33

/* namebufs  WINDVIEW EVENTS */
#define EVENT_NAMEBUF_FIXFREELIST	4000
#define EVENT_NAMEBUF_DYNFREELIST	5000
#define EVENT_NAMEBUF_FIXHASHLIST	6000
#define EVENT_NAMEBUF_DYNHASHLIST	7000
#define EVENT_NAMEBUF_MAKEENTRY		40
#define EVENT_NAMEBUF_FREE		41
#define EVENT_NAMEBUF_FINDENTRY_PEND	42
#define EVENT_NAMEBUF_MAKEENTRY_PEND	43

/* rngXBlkLib  WINDVIEW EVENTS */
#define EVENT_RNGX_PUTBLOCK		96
#define EVENT_RNGX_PUTFREED		97
#define EVENT_RNGX_GETBLOCK		98
#define EVENT_RNGX_GETFREED		99

/* PARSER   WINDVIEW EVENTS */
#define EVENT_INTRP_UPDATE		50	/* Acode Update */
#define EVENT_INTRP_SUSPEND		51	/* Suspend Parser, i.e. shandler activity */

/* fBufferLib  WINDVIEW EVENTS */
#define EVENT_FBUF_GET			60
#define EVENT_FBUF_PUT			61

/* PARALLEL WINDVIEW EVENTS	*/
#define EVENT_PARALLEL_INIT		70
#define EVENT_PARALLEL_START_CREATE	71
#define EVENT_PARALLEL_SELECT		72
#define EVENT_PARALLEL_LOCK		73
#define EVENT_PARALLEL_UNLOCK		74
#define EVENT_PARALLEL_SORT		75
#define EVENT_PARALLEL_CMPLT		76
#define EVENT_PARALLEL_FREE		77

/* AUTO WINDVIEW EVENTS */
#define EVENT_AUTO_RESET		100

#define EVENT_AUTO_SPINREG_ERR		101
#define EVENT_AUTO_LOCKED_ERR		102
#define EVENT_AUTO_VTREG_ERR		103
#define EVENT_AUTO_UNKNOWN_ERR		104

#define EVENT_AUTO_SPINMSG_SEND		110
#define EVENT_AUTO_SPINMSG_ACK		111
#define EVENT_AUTO_SPINMUX_TIMEOUT	112
#define EVENT_AUTO_SPINCMD_TIMEOUT	113

#define EVENT_AUTO_SHIMMSG_SEND		120
#define EVENT_AUTO_SHIMMSG_ACK		121
#define EVENT_AUTO_SHIMMUX_TIMEOUT	122
#define EVENT_AUTO_SHIMCMD_TIMEOUT	123

#define EVENT_AUTO_GENMSG_SEND		130
#define EVENT_AUTO_GENMSG_ACK		131
#define EVENT_AUTO_GENMUX_TIMEOUT	132
#define EVENT_AUTO_GENCMD_TIMEOUT	133

#define EVENT_AUTO_VTMSG_SEND		140
#define EVENT_AUTO_VTMSG_ACK		141
#define EVENT_AUTO_VTMUX_TIMEOUT	142
#define EVENT_AUTO_VTCMD_TIMEOUT	143

/* MONITOR CMDS  */
#define EVENT_MONITOR_CMD_ECHO		200
#define EVENT_MONITOR_CMD_XPARSER	201
#define EVENT_MONITOR_CMD_APARSER	202
#define EVENT_MONITOR_CMD_INTERACT	203
#define EVENT_MONITOR_CMD_AUPDT		204
#define EVENT_MONITOR_CMD_HALTACQ	205
#define EVENT_MONITOR_CMD_ABORTACQ	206
#define EVENT_MONITOR_CMD_STATINTERV	207
#define EVENT_MONITOR_CMD_STARTLOCK	208
#define EVENT_MONITOR_CMD_GETINTERACT	209
#define EVENT_MONITOR_CMD_STOPINTERACT	210
#define EVENT_MONITOR_CMD_STOPACQ	211
#define EVENT_MONITOR_CMD_ACQDEBUG	212
#define EVENT_MONITOR_CMD_HEARTBEAT	213
#define EVENT_MONITOR_CMD_GETSTATBLOCK	214
#define EVENT_MONITOR_CMD_ABORTALLACQS	215
#define EVENT_MONITOR_CMD_OK2TUNE	215
#define EVENT_MONITOR_CMD_ROBO_ACK	216
#define EVENT_MONITOR_CMD_CONSOLEINFO	217
#define EVENT_MONITOR_CMD_DOWNLOAD	218
#define EVENT_MONITOR_CMD_STARTFIDSCOPE	219
#define EVENT_MONITOR_CMD_STOPFIDSCOPE	220
#define EVENT_MONITOR_CMD_GETCONSOLEDEBUG 221

/* PARSER CMDS  */
#define EVENT_PARSE_READY		300
#define EVENT_PARSE_BUSY		301
#define EVENT_PARSE_ACODE		302
#define EVENT_PARSE_STOP		303
#define EVENT_PARSE_SUSPENDED		304
#define EVENT_PARSE_RESTART		305


#define EVENT_FIFOBUF_INITBUF		380
#define EVENT_FIFOBUF_RCVRDY		381
#define EVENT_FIFOBUF_SNDFREE		382
#define EVENT_FIFOBUF_RCVFREE		383
#define EVENT_FIFOBUF_SNDRDY		384

#define EVENT_SYSFLAG_WAIT4DWNLKR	390
#define EVENT_SYSFLAG_WAIT4PARSER	391
#define EVENT_SYSFLAG_WAIT4SYSTEM	392
#define EVENT_SYSFLAG_SEMTAKE		393

#define EVENT_DOWNLINKER_READY		400
#define EVENT_DOWNLINKER_BUSY		401
#define EVENT_DOWNLINKER_DUMP		402
#define EVENT_DOWNLINKER_CMD_DWNLD	403
#define EVENT_DOWNLINKER_CMD_XPARSE	404
#define EVENT_DOWNLINKER_CMD_APARSE	405
#define EVENT_DOWNLINKER_CMD_AUPDT	406
#define EVENT_DOWNLINKER_DYNAMIC	407
#define EVENT_DOWNLINKER_FIXED		408
#define EVENT_DOWNLINKER_VME		409
#define EVENT_DOWNLINKER_GETBUF		410
#define EVENT_DOWNLINKER_HOST_ACK	411
#define EVENT_DOWNLINKER_XFER_STATCMPLT	412
#define EVENT_DOWNLINKER_XFER_STATABORT	413
#define EVENT_DOWNLINKER_XFER_STATRESETCNT 414
#define EVENT_DOWNLINKER_XFERCMPLT	415

/* Shandler Commands  */
#define EVENT_SHDLR_WDISR 			500
#define EVENT_SHDLR_AA 				501
#define EVENT_SHDLR_SETUPCMPLT 			502
#define EVENT_SHDLR_EXPCMPLT 			503
#define EVENT_SHDLR_LOCKAUTO 			504
#define EVENT_SHDLR_SHIMAUTO 			505
#define EVENT_SHDLR_AUTOGAIN 			506
#define EVENT_SHDLR_SETVT 			507
#define EVENT_SHDLR_WAIT4VT 			508
#define EVENT_SHDLR_SETSPIN 			509
#define EVENT_SHDLR_CHECKSPIN 			510
#define EVENT_SHDLR_GETSAMP 			511
#define EVENT_SHDLR_LOADSAMP 			512
#define EVENT_SHDLR_SYNC_PARSER			513
#define EVENT_SHDLR_NOISECMPLT			514

/* Phandler Commands  */
#define EVENT_PHDLR_WDISR 			550
#define EVENT_PHDLR_PANIC 			551
#define EVENT_PHDLR_WARNMSG 			552
#define EVENT_PHDLR_SOFTERROR 			553
#define EVENT_PHDLR_EXPABORTED 			554
#define EVENT_PHDLR_HARDERROR 			555
#define EVENT_PHDLR_EXPHALTED 			556
#define EVENT_PHDLR_STOPCMPLT 			557
#define EVENT_PHDLR_LOSTCONN 			558
#define EVENT_PHDLR_ALLOCERROR 			559
#define EVENT_PHDLR_WATCHDOG 			560



/*   X Parser Commands (Handler Entries)  */
#define EVENT_XPARSER_LOCKHDLR		601
#define EVENT_XPARSER_SHIMHDLR		602
#define EVENT_XPARSER_SPINHDLR		603
#define EVENT_XPARSER_STATHDLR		604
#define EVENT_XPARSER_AUTSHMHDLR	605
#define EVENT_XPARSER_RCVGAINHDLR	606
#define EVENT_XPARSER_FIXACODEHDLR	607
#define EVENT_XPARSER_SETATTNHDLR	608
#define EVENT_XPARSER_TUNEHDLR		609
#define EVENT_XPARSER_LKFREQHDLR	610
#define EVENT_XPARSER_SETVTHDLR		611
#define EVENT_XPARSER_SHIMSETHDLR	612
#define EVENT_XPARSER_NVRAMHDLR		613
#define EVENT_XPARSER_SYNCHDLR		614

/*   A_updt commands    */
#define EVENT_AUPDATE_FIXAPREG		651
#define EVENT_AUPDATE_FIXACODE		652
#define EVENT_AUPDATE_FIXACODES		653
#define EVENT_AUPDATE_FIXRTVARS		654
#define EVENT_AUPDATE_CHGTABLE		655
#define EVENT_AUPDATE_CHGRTVAR		656
#define EVENT_AUPDATE_CHGACODE		657


/* ======================================================================== */
/*
*	MSR Events
*/

#define EVENT_MBOX_GENISR		10
#define EVENT_MBOX_SPINISR		11
#define EVENT_MBOX_VTISR		12
#define EVENT_MBOX_SHIMISR		13
#define EVENT_MBOX_SHIMAP1ISR		14
#define EVENT_MBOX_SHIMAP2ISR		15

#define EVENT_MBOX_GENMSGGET		20
#define EVENT_MBOX_GENMSGACK		21
#define EVENT_MBOX_GENMSGPUT		22

#define EVENT_MBOX_SPINMSGGET		30
#define EVENT_MBOX_SPINMSGACK		31

#define EVENT_MBOX_VTMSGGET		40
#define EVENT_MBOX_VTMSGACK		41

#define EVENT_MBOX_SHIMMSGGET		50
#define EVENT_MBOX_SHIMMSGACK		51
#define EVENT_MBOX_SPINAPMSGGET		52


#define EVENT_SHIMSET_QSPI		80	/* setting QSPI shim DAC */
#define EVENT_SHIMSET_SERIAL		81
#define EVENT_SHIMSET_OMT		82
#define EVENT_SHIMSET_RRI		83
#define EVENT_SHIMSET_CMPLT		89

#define EVENT_MSG_GETLKVAL		100
#define EVENT_MSG_GETSHIMS		101
#define EVENT_MSG_GETSERIALSHIM		102
#define EVENT_MSG_GETSPINVALUE		103
#define EVENT_MSG_EJECT			104
#define EVENT_MSG_INSERT		105
#define EVENT_MSG_SAMPDETECT		106
#define EVENT_MSG_SETSPINRATE		107
#define EVENT_MSG_SETSPINSPD		108
#define EVENT_MSG_BEARINGON		109
#define EVENT_MSG_BEARINGOFF		110
#define EVENT_MSG_SETMASTHRES		111
#define EVENT_MSG_SETSPINREGDELTA	112
#define EVENT_MSG_SETDEBUGLEVEL		113

#define EVENT_MSR_HEARTBEAT		1
#define EVENT_QSPI_MSG_DONE		2

#define EVENT_QSHIM_MUTEX		200
#define EVENT_QSHIM_TRANMIT		201
#define EVENT_QSHIM_CMPLT		202

#endif
