/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
/*
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VNMRFrame */

#ifndef _Included_VNMRFrame
#define _Included_VNMRFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef VNMRFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define VNMRFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef VNMRFrame_FOCUS_TRAVERSABLE_DEFAULT
#define VNMRFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef VNMRFrame_FOCUS_TRAVERSABLE_SET
#define VNMRFrame_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef VNMRFrame_TOP_ALIGNMENT
#define VNMRFrame_TOP_ALIGNMENT 0.0f
#undef VNMRFrame_CENTER_ALIGNMENT
#define VNMRFrame_CENTER_ALIGNMENT 0.5f
#undef VNMRFrame_BOTTOM_ALIGNMENT
#define VNMRFrame_BOTTOM_ALIGNMENT 1.0f
#undef VNMRFrame_LEFT_ALIGNMENT
#define VNMRFrame_LEFT_ALIGNMENT 0.0f
#undef VNMRFrame_RIGHT_ALIGNMENT
#define VNMRFrame_RIGHT_ALIGNMENT 1.0f
#undef VNMRFrame_serialVersionUID
#define VNMRFrame_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef VNMRFrame_serialVersionUID
#define VNMRFrame_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
#undef VNMRFrame_INCLUDE_SELF
#define VNMRFrame_INCLUDE_SELF 1L
#undef VNMRFrame_SEARCH_HEAVYWEIGHTS
#define VNMRFrame_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: systemSyncLWRequests */
#undef VNMRFrame_OPENED
#define VNMRFrame_OPENED 1L
/* Inaccessible static: nameCounter */
#undef VNMRFrame_serialVersionUID
#define VNMRFrame_serialVersionUID 4497834738069338734LL
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Window */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowFocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowStateListener */
#undef VNMRFrame_DEFAULT_CURSOR
#define VNMRFrame_DEFAULT_CURSOR 0L
#undef VNMRFrame_CROSSHAIR_CURSOR
#define VNMRFrame_CROSSHAIR_CURSOR 1L
#undef VNMRFrame_TEXT_CURSOR
#define VNMRFrame_TEXT_CURSOR 2L
#undef VNMRFrame_WAIT_CURSOR
#define VNMRFrame_WAIT_CURSOR 3L
#undef VNMRFrame_SW_RESIZE_CURSOR
#define VNMRFrame_SW_RESIZE_CURSOR 4L
#undef VNMRFrame_SE_RESIZE_CURSOR
#define VNMRFrame_SE_RESIZE_CURSOR 5L
#undef VNMRFrame_NW_RESIZE_CURSOR
#define VNMRFrame_NW_RESIZE_CURSOR 6L
#undef VNMRFrame_NE_RESIZE_CURSOR
#define VNMRFrame_NE_RESIZE_CURSOR 7L
#undef VNMRFrame_N_RESIZE_CURSOR
#define VNMRFrame_N_RESIZE_CURSOR 8L
#undef VNMRFrame_S_RESIZE_CURSOR
#define VNMRFrame_S_RESIZE_CURSOR 9L
#undef VNMRFrame_W_RESIZE_CURSOR
#define VNMRFrame_W_RESIZE_CURSOR 10L
#undef VNMRFrame_E_RESIZE_CURSOR
#define VNMRFrame_E_RESIZE_CURSOR 11L
#undef VNMRFrame_HAND_CURSOR
#define VNMRFrame_HAND_CURSOR 12L
#undef VNMRFrame_MOVE_CURSOR
#define VNMRFrame_MOVE_CURSOR 13L
#undef VNMRFrame_NORMAL
#define VNMRFrame_NORMAL 0L
#undef VNMRFrame_ICONIFIED
#define VNMRFrame_ICONIFIED 1L
#undef VNMRFrame_MAXIMIZED_HORIZ
#define VNMRFrame_MAXIMIZED_HORIZ 2L
#undef VNMRFrame_MAXIMIZED_VERT
#define VNMRFrame_MAXIMIZED_VERT 4L
#undef VNMRFrame_MAXIMIZED_BOTH
#define VNMRFrame_MAXIMIZED_BOTH 6L
/* Inaccessible static: nameCounter */
#undef VNMRFrame_serialVersionUID
#define VNMRFrame_serialVersionUID 2673458971256075116LL
/* Inaccessible static: class_00024java_00024awt_00024Frame */
#undef VNMRFrame_EXIT_ON_CLOSE
#define VNMRFrame_EXIT_ON_CLOSE 3L
/* Inaccessible static: defaultLookAndFeelDecoratedKey */
/* Inaccessible static: updateAttrThread */
/* Inaccessible static: updateThread */
/* Inaccessible static: fillMacrosThread */
/* Inaccessible static: fillWorkspaceThread */
/* Inaccessible static: dbStatus */
/* Inaccessible static: hostAddr */
/* Inaccessible static: vnmrFrame */
/* Inaccessible static: m_title */
/*
 * Class:     VNMRFrame
 * Method:    getXwinId
 * Signature: (Ljavax/swing/JFrame;)I
 */
JNIEXPORT jint JNICALL Java_vnmr_ui_VNMRFrame_getXwinId
  (JNIEnv *, jobject, jobject);

/*
 * Class:     VNMRFrame
 * Method:    syncXwin
 * Signature: (Ljavax/swing/JFrame;)I
 */
JNIEXPORT jint JNICALL Java_vnmr_ui_VNMRFrame_syncXwin
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
