/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
/*
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VnmrXCanvas */

#ifndef _Included_VnmrXCanvas
#define _Included_VnmrXCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef VnmrXCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define VnmrXCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef VnmrXCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define VnmrXCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef VnmrXCanvas_FOCUS_TRAVERSABLE_SET
#define VnmrXCanvas_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef VnmrXCanvas_TOP_ALIGNMENT
#define VnmrXCanvas_TOP_ALIGNMENT 0.0f
#undef VnmrXCanvas_CENTER_ALIGNMENT
#define VnmrXCanvas_CENTER_ALIGNMENT 0.5f
#undef VnmrXCanvas_BOTTOM_ALIGNMENT
#define VnmrXCanvas_BOTTOM_ALIGNMENT 1.0f
#undef VnmrXCanvas_LEFT_ALIGNMENT
#define VnmrXCanvas_LEFT_ALIGNMENT 0.0f
#undef VnmrXCanvas_RIGHT_ALIGNMENT
#define VnmrXCanvas_RIGHT_ALIGNMENT 1.0f
#undef VnmrXCanvas_serialVersionUID
#define VnmrXCanvas_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef VnmrXCanvas_serialVersionUID
#define VnmrXCanvas_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
#undef VnmrXCanvas_INCLUDE_SELF
#define VnmrXCanvas_INCLUDE_SELF 1L
#undef VnmrXCanvas_SEARCH_HEAVYWEIGHTS
#define VnmrXCanvas_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: readObjectCallbacks */
/* Inaccessible static: managingFocusForwardTraversalKeys */
/* Inaccessible static: managingFocusBackwardTraversalKeys */
/* Inaccessible static: suppressDropSupport */
/* Inaccessible static: checkedSuppressDropSupport */
#undef VnmrXCanvas_NOT_OBSCURED
#define VnmrXCanvas_NOT_OBSCURED 0L
#undef VnmrXCanvas_PARTIALLY_OBSCURED
#define VnmrXCanvas_PARTIALLY_OBSCURED 1L
#undef VnmrXCanvas_COMPLETELY_OBSCURED
#define VnmrXCanvas_COMPLETELY_OBSCURED 2L
#undef VnmrXCanvas_WHEN_FOCUSED
#define VnmrXCanvas_WHEN_FOCUSED 0L
#undef VnmrXCanvas_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define VnmrXCanvas_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef VnmrXCanvas_WHEN_IN_FOCUSED_WINDOW
#define VnmrXCanvas_WHEN_IN_FOCUSED_WINDOW 2L
#undef VnmrXCanvas_UNDEFINED_CONDITION
#define VnmrXCanvas_UNDEFINED_CONDITION -1L
#undef VnmrXCanvas_IS_DOUBLE_BUFFERED
#define VnmrXCanvas_IS_DOUBLE_BUFFERED 0L
#undef VnmrXCanvas_ANCESTOR_USING_BUFFER
#define VnmrXCanvas_ANCESTOR_USING_BUFFER 1L
#undef VnmrXCanvas_IS_PAINTING_TILE
#define VnmrXCanvas_IS_PAINTING_TILE 2L
#undef VnmrXCanvas_IS_OPAQUE
#define VnmrXCanvas_IS_OPAQUE 3L
#undef VnmrXCanvas_KEY_EVENTS_ENABLED
#define VnmrXCanvas_KEY_EVENTS_ENABLED 4L
#undef VnmrXCanvas_FOCUS_INPUTMAP_CREATED
#define VnmrXCanvas_FOCUS_INPUTMAP_CREATED 5L
#undef VnmrXCanvas_ANCESTOR_INPUTMAP_CREATED
#define VnmrXCanvas_ANCESTOR_INPUTMAP_CREATED 6L
#undef VnmrXCanvas_WIF_INPUTMAP_CREATED
#define VnmrXCanvas_WIF_INPUTMAP_CREATED 7L
#undef VnmrXCanvas_ACTIONMAP_CREATED
#define VnmrXCanvas_ACTIONMAP_CREATED 8L
#undef VnmrXCanvas_CREATED_DOUBLE_BUFFER
#define VnmrXCanvas_CREATED_DOUBLE_BUFFER 9L
#undef VnmrXCanvas_CREATED_VOLATILE_DOUBLE_BUFFER
#define VnmrXCanvas_CREATED_VOLATILE_DOUBLE_BUFFER 10L
#undef VnmrXCanvas_IS_PRINTING
#define VnmrXCanvas_IS_PRINTING 11L
#undef VnmrXCanvas_IS_PRINTING_ALL
#define VnmrXCanvas_IS_PRINTING_ALL 12L
#undef VnmrXCanvas_IS_REPAINTING
#define VnmrXCanvas_IS_REPAINTING 13L
#undef VnmrXCanvas_WRITE_OBJ_COUNTER_FIRST
#define VnmrXCanvas_WRITE_OBJ_COUNTER_FIRST 14L
#undef VnmrXCanvas_RESERVED_1
#define VnmrXCanvas_RESERVED_1 15L
#undef VnmrXCanvas_RESERVED_2
#define VnmrXCanvas_RESERVED_2 16L
#undef VnmrXCanvas_RESERVED_3
#define VnmrXCanvas_RESERVED_3 17L
#undef VnmrXCanvas_RESERVED_4
#define VnmrXCanvas_RESERVED_4 18L
#undef VnmrXCanvas_RESERVED_5
#define VnmrXCanvas_RESERVED_5 19L
#undef VnmrXCanvas_RESERVED_6
#define VnmrXCanvas_RESERVED_6 20L
#undef VnmrXCanvas_WRITE_OBJ_COUNTER_LAST
#define VnmrXCanvas_WRITE_OBJ_COUNTER_LAST 21L
#undef VnmrXCanvas_REQUEST_FOCUS_DISABLED
#define VnmrXCanvas_REQUEST_FOCUS_DISABLED 22L
/* Inaccessible static: class_00024javax_00024swing_00024JComponent_00024KeyboardState */
/* Inaccessible static: class_00024javax_00024swing_00024event_00024AncestorListener */
/* Inaccessible static: class_00024java_00024beans_00024VetoableChangeListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: syncDrag */
/* Inaccessible static: syncval */
/*
 * Class:     VnmrXCanvas
 * Method:    syncXwin
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_VnmrXCanvas_syncXwin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
