#!

import os
import sys

# get current working directory
cwd = os.getcwd()
execfile(os.path.join(cwd, os.pardir, os.pardir, 'scripts', 'buildoptions.py'))
ovjtools = bo.OVJ_TOOLS

javaBinDir = os.path.join(ovjtools, 'java', 'bin')

# get the envirionment
env = Environment(ENV = {'JAVA_HOME' : javaBinDir,
                         'PATH' : javaBinDir + ':' + os.environ['PATH']})

env.Execute('cd vjunit && make -f makevjunit')
env.Execute('cd VJQA/src && make -f makexmlcheck')

Execute('rm -rf ovj_qa')
path = os.path.join(cwd, 'ovj_qa')
if not os.path.exists(path):
   os.makedirs(path)

Execute('cp -r VJQA ovj_qa/OVJQA')
Execute('rm -rf ovj_qa/OVJQA/src')
Execute('rm -f ovj_qa/OVJQA/bin/lib/vjunit.jar')
Execute('cp vjunit/vjunit.jar ovj_qa/OVJQA/bin/lib/')
Execute('rm -f ovj_qa/OVJQA/java/*')
Execute('cp VJQA/src/XmlTest.jar VJQA/src/*.class ovj_qa/OVJQA/java/')
Execute('cp -r vjtest ovj_qa/ovjtest')
