/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */

/*------------------------------------------------------------------------
|
|	static struct codeWithMsg acqerrMsgeTable[]
|
|	contains the acquisition error messages.
+-----------------------------------------------------------------------*/

struct codeWithMsg {
    int      code;
    char    *errmsg;
};

static struct codeWithMsg acqerrMsgTable[] = {
    { ABORTERROR,          "Acquisition aborted" },
    { WARNINGS+LOWNOISE,   "low noise in acquisition" },
    { WARNINGS+HIGHNOISE,  "high noise - reduce gain" },
    { WARNINGS+ADCOVER,    "ADC overflow" },
    { WARNINGS+RECVOVER,   "Receiver overflow" },
    { WARNINGS+VGRADOVER,  "Gradient real-time calculation out-of-bounds" },
    { WARNINGS+APRTOVER,   "Real-time calculation out-of-bounds" },
    { WARNINGS+FIFOMISSING,"Acquisition Controller Card NOT detected in console" },
    { WARNINGS+STMMISSING, "STM/DTM Card NOT detected in console" },
    { WARNINGS+ADCMISSING, "ADC Card NOT detected in console" },
    { WARNINGS+AUTOMISSING, "Automation Card NOT detected in console" },
    { WARNINGS+AUTO_NOTBOOTED, "Automation Card has NOT Booted in console" },
    { WARNINGS+MEM_ALLOC_ERR, "A Memory Allocation within the console failed." },
    { WARNINGS+APREADFAIL, "User APbus read failed." },
    { WARNINGS+MISSINGCNTLRS, "Warning: Some Pulse Sequence requested controller(s) are absent." },
    { WARNINGS+DATAOVF,    "Max value exceeded in 16 bit averaging" },
    { WARNINGS+GRAD_SLEW_EXCEEDED,  "Gradient Slew Rate Exceeded" },
    
    { SFTERROR+MAXCT,      "Maximum transients accumulated" },
    { SFTERROR+LOCKLOST,   "Lock lost during experiment" },
    { SFTERROR+STOPACQ,    "User stopped acquisition" },
    { SFTERROR+GTABERR,    "Global Table Error" },
    { SFTERROR+GTABNOPTR,  "Global Table Pointer Invalid" },
    { SFTERROR+ATTNADDR,   "SISCO system attenuator error" },
    { SFTERROR+READBIT,    "User read bit out of range" },
    { SPINERROR+BUMPFAIL,  "Sample failing to spin" },
    { SPINERROR+RSPINFAIL, "Spinner did not regulate" },
    { SPINERROR+SPINOUT,
		"Spinner went out of regulation during the experiment" },
    { SPINERROR+SPINUNKNOWN, "Unknown spinner device specified" },
    { SPINERROR+SPINNOPOWER, "Spinner not powered up" },
    { SPINERROR+SPINRS232,   "Spinner not connected to the console" },
    { SPINERROR+SPINTIMEOUT, "Spinner does not acknowledge commands" },
    { VTERROR+VTREGFAIL,     "VT controller did not regulate" },
    { VTERROR+VTOUT,
		"VT went out of regulation during the experiment" },
    { VTERROR+VTMANUAL,     "VT controller on standby or manual control" },
    { VTERROR+VTSSLIMIT,   "VT Controller safety sensor limiting output" },
    { VTERROR+VTNOGAS,   "VT Controller has no gas flow" },
    { VTERROR+VTMSONBOT, "VT controller main sensor on bottom limit" },
    { VTERROR+VTMSONTOP,    "VT controller main sensor on top limit" },
    { VTERROR+VT_SC_SS,    "VT controller s/c safety sensor" },
    { VTERROR+VT_OC_SS,    "VT controller o/c safety sensor" },
    { VTERROR+VTUNKNOWN,     "Unknown VT device specified" },
    { VTERROR+VTNOPOWER,     "VT controller not powered up" },
    { VTERROR+VTRS232,       "VT controller not connected to the console" },
    { VTERROR+VTTIMEOUT,     "VT does not acknowledge commands" },
    { SMPERROR+RTVNOSAMPLE,  "Sample changer failed to retrieve sample and sample detected in magnet" },
    { SMPERROR+RTVARMUPFAIL,
		"Sample changer arm unable to move up during retrieve" },
    { SMPERROR+RTVARMDOWNFAIL,
		"Sample changer arm unable to move down during retrieve" },
    { SMPERROR+RTVARMMIDFAIL, "Sample changer arm failed to move" },
    { SMPERROR+RTVBADNUMBER, "Illegal sample changer location" },
    { SMPERROR+RTVBADTEMP,   "Invalid temperature during retrieve" },
    { SMPERROR+RTVGRIPABORT, "Gripper abort during retrieve" },
    { SMPERROR+RTVRANGERR,   "Sample out of range during automatic retrieve" },
    { SMPERROR+RTVBADCMDCHAR, "Sample changer syntax error" },
    { SMPERROR+RTVHOMEFAIL,  "Robot failed to find home position" },
    { SMPERROR+RTVNOTRAY,    "Sample tray size is not consistent" },
    { SMPERROR+RTVPOWERFAIL, "Sample changer power failure during retrieve" },
    { SMPERROR+RTVBADCOMMAND,"Illegal sample changer command" },
    { SMPERROR+RTVGRIPOPEN,  "Robot gripper failed to open" },
    { SMPERROR+RTVAIRSUPPLY, "Air supply to sample changer failed" },
    { SMPERROR+RTVNOSAMPNODETECT,
     		"Sample changer failed to retrieve sample but sample no longer detected in magnet." },
    { SMPERROR+INSNOSAMPLE,  "Sample changer has no sample to insert" },
    { SMPERROR+INSARMUPFAIL,
		"Sample changer arm unable to move up during insert" },
    { SMPERROR+INSARMDOWNFAIL,
		"Sample changer arm unable to move down during insert" },
    { SMPERROR+INSARMMIDFAIL,
		"Sample changer failed to move during insert" },
    { SMPERROR+INSBADNUMBER, "Illegal sample tray location during insert." },
    { SMPERROR+INSBADTEMP,
		"Invalid temperature during sample changer insert" },
    { SMPERROR+INSGRIPABORT, "Gripper abort during insert" },
    { SMPERROR+INSRANGERR,   "Sample out of range during automatic insert" },
    { SMPERROR+INSBADCMDCHAR,"Illegal command character during insert" },
    { SMPERROR+INSHOMEFAIL,
		"Robot arm failed to find home position during insert" },
    { SMPERROR+INSNOTRAY,    "Sample tray size is not consistent" },
    { SMPERROR+INSPOWERFAIL, "Sample changer power failure during insert" },
    { SMPERROR+INSBADCOMMAND,"Illegal sample changer command during insert" },
    { SMPERROR+INSGRIPOPEN,  "Robot gripper closed unexpectedly" },
    { SMPERROR+INSAIRSUPPLY,
		"Air supply to sample changer failed during insert" },
    { SMPERROR+RACKNSAMPFILEERROR,    "Rack and Sample File is missing or had a format error" },
    { SMPERROR+INVALID_ZONE,    "Sample Zone Out of Range for this Rack" },
    { SMPERROR+INVALID_SAMP,    "Sample Location Out of Range for this Zone" },
    { SMPERROR+TCLINTERPERROR,  "Initialization of TCL Interpreter Failed" },
    { SMPERROR+TCLSCRIPTERROR,  "Error Occurred During Interpreting TCL Script" },
    { SMPERROR+INVALID_RACK,    "Rack Not Present" },
    { SMPERROR+46,    "Upper barrel gripper timeout" },
    { SMPERROR+47,    "Sample changer open access failed" },
    { SMPERROR+48,    "Sample changer close access failed" },
    { SMPERROR+49,    "Waiting for sample in upper barrel timed out" },
    { SMPERROR+50,    "Sample changer logic error" },
    { SMPERROR+51,    "Sample changer user access timeout. Access is open" },
    { SMPERROR+52,    "Sample detected in robot gripper" },
    { SMPERROR+53,    "Sample changer aborted with e-stop" },
    { SMPERROR+54,    "Sample detected in upper barrel" },
    { SMPERROR+55,    "Robot gripper failed to close" },
    { SMPERROR+56,    "Sample lost from robot gripper" },
    { SMPERROR+57,    "Upper barrel gripper failed to close" },
    { SMPERROR+58,    "Upper barrel gripper sample detection failure" },
    { SMPERROR+59,    "Sample still detected in robot gripper after release" },
    { SMPERROR+60,    "No sample in upper barrel" },
    { SMPERROR+61,    "Sample tray position is not available" },
    { SMPERROR+63,    "Upper barrel gripper failed to open" },
    { SMPERROR+64,    "Robot gripper failed to open and release sample" },
    { SMPERROR+65,    "Magnet motion fault" },
    { SMPERROR+66,    "No location assigned to sample in magnet. Assign a location or remove manually" },
    { SMPERROR+67,    "Robot not homed" },
    { SMPERROR+68,    "Sample tube has been broken" },

    { SMPERROR+HRM_MOTORS_HALTED,
                              "Sample changer halted. Servo error or "
                              "swing-out table is ajar." },
    { SMPERROR+HRM_HIGHPOWER, "High power to the sample changer is not "
                              "enabled." },
    { SMPERROR+HRM_RACKTOPCS, "Failure transporting sample from the rack "
                              "to the preconditioner station." },
    { SMPERROR+HRM_PCSTOMAG,  "Failure transporting sample from the "
                              "preconditioner station to the magnet." },
    { SMPERROR+HRM_MAGTORACK, "Failure transporting sample from the magnet "
                              "back to the rack." },
    { SMPERROR+HRM_BARCODE,   "No barcode detected, skipping sample." },
    { SMPERROR+HRM_ROBOTERR,  "Unrecoverable robot error. Manually clear "
                              "the sample changer and restart procs." },
    { SMPERROR+HRM_CALIBRATE, "The sample changer needs to be calibrated." },
    { SMPERROR+HRM_COMMERROR, "Error communicating with sample changer." },
    { SMPERROR+HRM_BARCODE_FATAL,
                              "No barcode detected, halting batch run." },

    { SMPERROR+SMPINFAIL,    "Failed to insert sample into the magnet" },
    { SMPERROR+SMPRMFAIL,    "Failed to remove sample from the magnet" },
    { SMPERROR+SMPSPNFAIL,   "Sample failed to spin after automatic insert" },
    { SMPERROR+SLOWDROPFAIL, "Sample failed to insert properly" },
    { SMPERROR+SMPNOPOWER,   "Sample changer not turned on" },
    { SMPERROR+SMPRS232, "Sample changer not connected to RS-232 interface" },
    { SMPERROR+SMPTIMEOUT,   "Sample changer not responding" },
    { SHIMERROR+SHIMABORT,   "Experiment stopped during shimming" },
    { SHIMERROR+SHIMLKLOST,  "Lock lost during shimming" },
    { SHIMERROR+SHIMLKSAT,   "Lock signal saturated during shimming" },
    { SHIMERROR+SHIMDACLIM,  "A shim coil DAC has reached its limit" },
    { SHIMERROR+SHIMNOMETHOD, "Shim method string is empty" },
    { SHIMERROR+SHIMCOMLOST, "Shim communications lost (unused)" },
    { ALKERROR+ALKABORT,     "Experiment stopped during auto lock" },
    { ALKERROR+ALKRESFAIL,
		"Auto lock failure in finding resonance of sample" },
    { ALKERROR+ALKPOWERFAIL, "Auto lock failure in lock power adjustment" },
    { ALKERROR+ALKPHASFAIL,  "Auto lock failure in lock phase adjustment" },
    { ALKERROR+ALKGAINFAIL,
		"Auto lock failure, lock lost in final gain adjustment" },
    { AGAINERROR+AGAINFAIL,
		"Auto gain failure, gain driven to 0, reduce pulse width" }, 
    { HDWAREERROR+PSGIDERROR, "Wrong PSG Revision for Acquisition" },
    { HDWAREERROR+STMERROR,   "Rcvr %d: Number of points acquired is %d %s" },
    { HDWAREERROR+FIFOERROR,  "FIFO underflow" },
    { HDWAREERROR+NP2BIG,     "Value of np is too large for acquisition" },
    { HDWAREERROR+BUSSTRAP,   "Acquisition Bus Trap error" },
    { HDWAREERROR+HWLOOPZERO,
		"Hardware looping with a count of zero not allowed" },
    { HDWAREERROR+NETBLERROR, "Not enough time between hardware loops" },
    { HDWAREERROR+FORPERROR,  "Fifo emptied too fast for prefifo to keep up" },
    { HDWAREERROR+OB_IDERROR, "Wrong Pulse Controller specified for Acquisition" },
    { HDWAREERROR+FIFOSTRTEMPTY, "Fifo was started while it was empty" },
    { HDWAREERROR+FIFOSTRTHALT, "Fifo was started with haltop as first instruction" },
    { HDWAREERROR+FIFONETBAP, "Not enough time between AP Bus Transactions" },
    { HDWAREERROR+INVALIDACODE, "Invalid Acquisition Instruction" },
    { HDWAREERROR+NOROTORSYNC, "Rotor Sync Hardware Not Present." },
    { HDWAREERROR+NOHSDTMADC, "High Speed DTM/ADC Hardware Not Present." },
    { HDWAREERROR+INVALPARALLELTYPE, "Invalid Type within Parallel Channel." },
    { HDWAREERROR+PARALLELNOSPACE, "No Space to Create Parallel Channel." },
    { HDWAREERROR+TOOFEWRCVRS, "Request for more receivers than present." },
    { HDWAREERROR+INCONSISTENT_STATUS, "Inconsistent DTM Error Interrupt and DTM status." },
    { HDWAREERROR+TAG_INDEX_ERROR, "Hardware error, DTM presented invalid tag value." },
    { HDWAREERROR+FIFO_OVRFLOW, "FIFO Overflow" },
    { HDWAREERROR+MASTER_SPI0_OVRRUN, "Master SPI0 Over Run" },
    { HDWAREERROR+MASTER_SPI1_OVRRUN, "Master SPI1 Over Run" },
    { HDWAREERROR+MASTER_SPI2_OVRRUN, "Master SPI2 Over Run" },
    { HDWAREERROR+PFG_XAMP_OVRRUN, "PFG X Axis Data Over Run" },
    { HDWAREERROR+PFG_YAMP_OVRRUN, "PFG Y Axis Data Over Run" },
    { HDWAREERROR+PFG_ZAMP_OVRRUN, "PFG Z Axis Data Over Run" },
    { HDWAREERROR+GRADIENT_AMP_OVRRUN, "Gradient Amp Data Over Run" },
    { HDWAREERROR+GRADIENT_ECC_OVRRUN, "Gradient ECC Data Over Run" },
    { HDWAREERROR+GRADIENT_SLEW_OVRRUN, "Gradient Slew Rate Data Over Run" },
    { HDWAREERROR+GRADIENT_DUTY_OVRRUN, "Gradient Duty Cycle Data Over Run" },
    { HDWAREERROR+GRADIENT_SPI_OVRRUN, "Gradient SPI Data Over Run" },
    { HDWAREERROR+GRADIENT_AMPL_OUTOFRANGE, "Gradient amplitude DAC value out of +/-32767 range" },

    { HDWAREERROR+DDR_DSP_NOT_INIT, "DSP not initialized" },
    { HDWAREERROR+DDR_DSP_ACQ_ERR, "DSP acquisition error" },
    { HDWAREERROR+DDR_DSP_SCANQ_ERR, "DSP scan queue full" },
    { HDWAREERROR+DDR_DSP_DATAQ_ERR, "DSP data queue failure" },
    { HDWAREERROR+DDR_DSP_NP_ERR, "DSP scan overrun (repetition rate too high)" },
    { HDWAREERROR+DDR_DSP_LOCK_ERR, "DSP locked buffer overwrite" },
    { HDWAREERROR+DDR_DSP_ADC_OVRFLW, "DSP data overrun of filtering" },
    { HDWAREERROR+DDR_DSP_DFIFO_OVRFLW, "DSP ADC DATA FIFO overflow" },
    { HDWAREERROR+DDR_DSP_BAD_MSG, "DSP unintialized message" },
    { HDWAREERROR+DDR_DSP_SCANITR_ERR, "DSP missed scan interrupt" },
    { HDWAREERROR+DDR_DSP_BADID_ERR, "DSP fpga version incompatible with ddros software" },
    { HDWAREERROR+DDR_DSP_MEM_ERR, "DSP out of memory" },
    { HDWAREERROR+DDR_DSP_PROC_ERR, "DSP processing error" },
    { HDWAREERROR+DDR_DSP_SNAPSHOT_ERR, "DSP invalid snapshot request (no ss buffer)" },
    { HDWAREERROR+DDR_DSP_C67Q_OVRFLW, "DSP C67->405 message queue overflow" },
    { HDWAREERROR+DDR_DSP_405Q_OVRFLW, "DSP 405->C67 message queue overflow" },
    { HDWAREERROR+DDR_DSP_FIFO_OVRFLW, "DDR output fifo overflow" },
    { HDWAREERROR+DDR_DSP_FIFO_UNDERFLW, "DDR output fifo underflow" },
    { HDWAREERROR+DDR_DSP_HPI_TIMEOUT, "DSP HPI access timeout" },
    { HDWAREERROR+DDR_DSP_SW_TRAP, "DSP unexpected software behavior" },
    { HDWAREERROR+DDR_DSP_UNKNOWN_ERR, "DSP error unknown id code" },
    { HDWAREERROR+DDR_DSP_FIDQ_ERR, "DSP FID queue overflow" },
    { HDWAREERROR+DDR_DSP_SCANQ_POP_ERR, "DSP scan queue empty imminent (data uplink rate may be too high)" },
    { HDWAREERROR+CNTLR_MISSING_ERR, "Controller(s) are absent or unresponsive, check configuration" },
    { HDWAREERROR+CNTLR_ISYNC_ERR, "Controller(s) are unresponsive in initial synchronization step" },
    { HDWAREERROR+CNTLR_CMPLTSYNC_ERR, "Controller(s) failed the pulse sequence post synchronization step" },
    { HDWAREERROR+DDR_CMPLTFAIL_ERR, "Receiver(s) have failed to complete data upload" },
    { HDWAREERROR+FIFO_INVALID_OPCODE, "FIFO Invalid OPCODE trap" },
    { HDWAREERROR+DATA_UPLINK_ERR, "Data transfer from console to host failed (data uplink rate too high)" },
    { HDWAREERROR+PROG_DEC_PAT_ERR,  "Decoupling pattern error" },
    { HDWAREERROR+PROG_DEC_LOAD_ERR, "Decoupling pattern load error" },

    { SCSIERROR+READWARN,     "Recoverable SCSI read error" },
    { SCSIERROR+WRITEWARN,    "Recoverable SCSI write error" },
    { SCSIERROR+READERROR,    "Unrecoverable SCSI read error" },
    { SCSIERROR+WRITEERROR,   "Unrecoverable SCSI write error" },
    { DISKERROR+OPENERROR,    "Cannot open file for experiment data" },
    { DISKERROR+CLOSEERROR,   "Cannot close file of experiment data" },
    { DISKERROR+READERROR,    "Cannot read from file of experiment data" },
    { DISKERROR+WRITEERROR,   "Cannot write to file of experiment data" },
    { SYSTEMERROR+FIXBUFNOSPACE,   "A memory request of the console Fix Buffers  was too large" },
    { SYSTEMERROR+DYNBUFNOSPACE,   "A memory request of the console Dynamic Buffers  was too large" },
    { SYSTEMERROR+MALLOCNOSPACE,   "A memory request of the console Heap was too large" },
    { SYSTEMERROR+NOACODESET,   "Unable to find Acode Set" },
    { SYSTEMERROR+NOACODERTV,   "Unable to find Realtime Vars for Acode Set" },
    { SYSTEMERROR+NOACODETBL,   "Unable to find or allocate Table for Acode Set" },
    { SYSTEMERROR+INVALIDPCMD,   "Invalid Acode Parser Command." },
    { SYSTEMERROR+NOISECMPLTWDOG,   "Console W-Dog Timeout on Noise Complete." },
    { SYSTEMERROR+MSGQ_LOST_ERR, "Console msgQ message lost." },
    { SYSTEMERROR+DWNLD_CRC_ERR, "Acode transfer error, CRC match failed." },
    { SYSTEMERROR+IDATA_CRC_ERR,  "Internal Data transfer error, CRC match failed." },
    { SYSTEMERROR+DATA_CRC_ERR,  "Data transfer error, CRC match failed." },
    { SYSTEMERROR+DWNLD_CMPLT_ERR,  "Code transfer completion sync failed." },
    { SYSTEMERROR+FIFO_WRDS_LOST,  "Instruction FIFO words lost, detected." },
    { SYSTEMERROR+NOACODEPAT,   "Unable to find requested waveform." },
    { SYSTEMERROR+NVLOOP_ERR,   "Console loop nesting error" },
    { SYSTEMERROR+IFZERO_ERR,   "Console ifzero nesting error"  },    
    { SYSTEMERROR+GRD_ROTATION_LIST_ERR, "Console error in gradient rotation list or list index" },
    
    { SAFETYERROR+SIB_NO_ERROR,
      "An Error Monitor trip occurred but the error status is OK." },
    { SAFETYERROR+SIB_RESVD_A,	"Reserved RF monitor trip A occurred." },
    { SAFETYERROR+SIB_RESVD_B,	"Reserved RF monitor trip B occurred." },
    { SAFETYERROR+SIB_RESVD_C,	"Reserved RF monitor trip C occurred." },
    { SAFETYERROR+SIB_QUAD_REFL_PWR,
      "Excessive reflected power at quad hybrid." },
    { SAFETYERROR+SIB_OPR_PANIC, "STOP button pressed at operator station." },
    { SAFETYERROR+SIB_PS_FAIL,	"Power for RF Monitor board (RFM) failed." },
    { SAFETYERROR+SIB_ATTN_READBACK, "Attenuator control or readback failed." },
    { SAFETYERROR+SIB_MALLOC_FAIL,
      "Error Monitor event; console out of memory to report type." },
    { SAFETYERROR+SIB_COMM_FAIL,
      "No communication with Error Monitor system." },
    { SAFETYERROR+SIB_QUAD_REFL_PWR_BP,
      "Quad reflected power monitor bypassed." },
    { SAFETYERROR+SIB_PS_FAIL_BP,
      "Power supply monitor for RF Monitor board (RFM) bypassed." },

    { SAFETYERROR+OBSERROR+SIB_RESVD_A,
      "Reserved RF monitor trip A1 occurred on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RESVD_B,
      "Reserved RF monitor trip B1 occurred on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RESVD_C,
      "Reserved RF monitor trip C1 occurred on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_PALI_MISSING,
      "RF Monitor board (PALI/TUSUPI) missing on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_REFL_PWR,
      "Excessive reflected power on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_AMP_GATE_DISCONN,
      "RF amplifier gating disconnected on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_PALI_TRIP,
      "Excessive power detected by PALI on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_W_DOG,
      "RF Monitor system (TUSUPI) heartbeat stopped on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_PWR_SUPPLY,
      "Power supply for PALI/TUSUPI failed on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_REQ_ERROR,
      "PALI asserted REQ_ERROR on observe channel (should never occur)." },
    { SAFETYERROR+OBSERROR+SIB_TUSUPI_TRIP,
      "Excessive power detected by TUSUPI on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RF_OVERDRIVE,
      "RF power amp: overdrive on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RF_PULSE_WIDTH,
      "RF power amp: excessive pulse width on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RF_DUTY_CYCLE,
      "RF power amp: maximum duty cycle exceeded on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RF_OVER_TEMP,
      "RF power amp: overheated on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RF_PWR_SUPPLY,
      "RF power amp: power supply failed on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_PALI_BP,
      "RF power monitoring disabled on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_REFL_PWR_BP,
      "Reflected power monitoring disabled on observe channel." },
    { SAFETYERROR+OBSERROR+SIB_RF_AMP_BP,
      "RF power amp monitoring disabled on observe channel." },

    { SAFETYERROR+DECERROR+SIB_RESVD_A,
      "Reserved RF monitor trip A2 occurred on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RESVD_B,
      "Reserved RF monitor trip B2 occurred on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RESVD_C,
      "Reserved RF monitor trip C2 occurred on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_PALI_MISSING,
      "RF Monitor board (PALI/TUSUPI) missing on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_REFL_PWR,
      "Excessive reflected power on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_AMP_GATE_DISCONN,
      "RF amplifier gating disconnected on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_PALI_TRIP,
      "Excessive power detected by PALI on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_W_DOG,
      "RF Monitor system (TUSUPI) heartbeat stopped on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_PWR_SUPPLY,
      "Power supply for PALI/TUSUPI failed on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_REQ_ERROR,
      "PALI asserted REQ_ERROR on decouple channel (should never occur)." },
    { SAFETYERROR+DECERROR+SIB_TUSUPI_TRIP,
      "Excessive power detected by TUSUPI on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RF_OVERDRIVE,
      "RF power amp: overdrive on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RF_PULSE_WIDTH,
      "RF power amp: excessive pulse width on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RF_DUTY_CYCLE,
      "RF power amp: maximum duty cycle exceeded on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RF_OVER_TEMP,
      "RF power amp: overheated on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RF_PWR_SUPPLY,
      "RF power amp: power supply failed on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_PALI_BP,
      "RF power monitoring disabled on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_REFL_PWR_BP,
      "Reflected power monitoring disabled on decouple channel." },
    { SAFETYERROR+DECERROR+SIB_RF_AMP_BP,
      "RF power amp monitoring disabled on decouple channel." },

    { ILIERROR+ILI_QUAD_REFL_PWR, "Quad reflected power too high" },
    { ILIERROR+ILI_RFMON_MISSING, "RF Power Monitor board not responding"},
    { ILIERROR+ILI_OPR_PANIC, "STOP button pressed on operator's station"},
    { ILIERROR+ILI_OPR_CABLE, "Cable to Operator's Station disconnected"},
    /* NB: GRAD_TEMP is no longer used */
    { ILIERROR+ILI_GRAD_TEMP, "ILI Spare #4 trip"},
    { ILIERROR+ILI_GRAD_WATER, "Gradient coil water is off"},
    /* NB: Both body and head coil temp. errors now trip same line */
    { ILIERROR+ILI_HEAD_TEMP, "Gradient coil overheating"},
    { ILIERROR+ILI_ATTN_READBACK, "RF limit readback error"},
    { ILIERROR+ILI_RFMON_WDOG, "RF Power Monitor Board watchdog error"},
    { ILIERROR+ILI_RFMON_SELFTEST, "RF Power Monitor Board selftest failed"},
    { ILIERROR+ILI_RFMON_PS, "RF Power Monitor Board power supply failed"},
    { ILIERROR+ILI_SPARE_3, "ILI Spare #3 trip"},
    { ILIERROR+ILI_PS, "ILI Board power failed"},
    { ILIERROR+ILI_SDAC_DUTY_CYCLE, "SDAC duty cycle too high"},
    { ILIERROR+ILI_SPARE_1, "Crossover plate safety cover open"},
    { ILIERROR+ILI_SPARE_2, "ILI Spare #2 trip"},
    { ILIERROR+ILI_QUAD_BP, "Quad hybrid reflected power monitor BYPASSED"},
    { ILIERROR+ILI_SDAC_BP, "SDAC duty cycle limit BYPASSED"},
    { ILIERROR+ILI_HEAD_GRAD_BP, "ILI #1: Spare #4 BYPASSED"},
    { ILIERROR+ILI_GRAD_BP, "Main Gradient Coil errors BYPASSED"},

    { ILIERROR+ILI_SPARE_BP_1, "ILI #2 spare group 1 BYPASSED"},
    { ILIERROR+ILI_SPARE_BP_2, "ILI #2 spare group 2 BYPASSED"},
    { ILIERROR+ILI_SPARE_BP_3, "ILI #2 spare group 3 BYPASSED"},
    { ILIERROR+ILI_SPARE_BP_4, "ILI #2 spare group 4 BYPASSED"},

    { ILIERROR+OBSERROR+ILI_10S_SAR,
      "Channel 1 RF power exceeds 10s SAR limit"},
    { ILIERROR+OBSERROR+ILI_5MIN_SAR,
      "Channel 1 RF power exceeds 5min SAR limit"},
    { ILIERROR+OBSERROR+ILI_PEAK_PWR,
      "Channel 1 peak RF power exceeds limit"},
    { ILIERROR+OBSERROR+ILI_RF_AMP_CABLE,
      "Channel 1 RF Amp control cable error"},
    { ILIERROR+OBSERROR+ILI_RF_REFL_PWR,
      "Channel 1 RF Amp reflected power too high"},
    { ILIERROR+OBSERROR+ILI_RF_DUTY_CYCLE,
      "Channel 1 RF Amp duty cycle limit exceeded"},
    { ILIERROR+OBSERROR+ILI_RF_OVER_TEMP,
      "Channel 1 RF Amp temperature limit exceeded"},
    { ILIERROR+OBSERROR+ILI_RF_PULSE_WIDTH,
      "Channel 1 RF Amp pulse width limit exceeded"},
    { ILIERROR+OBSERROR+ILI_RFMON_BP,
      "Channel 1 RF Power Monitoring BYPASSED"},
    { ILIERROR+OBSERROR+ILI_RF_AMP_BP,
      "Channel 1 RF Amp errors BYPASSED"},

    { ILIERROR+DECERROR+ILI_10S_SAR,
      "Channel 2 RF power exceeds 10s SAR limit"},
    { ILIERROR+DECERROR+ILI_5MIN_SAR,
      "Channel 2 RF power exceeds 5min SAR limit"},
    { ILIERROR+DECERROR+ILI_PEAK_PWR,
      "Channel 2 peak RF power exceeds limit"},
    { ILIERROR+DECERROR+ILI_RF_AMP_CABLE,
      "Channel 2 RF Amp control cable error"},
    { ILIERROR+DECERROR+ILI_RF_REFL_PWR,
      "Channel 2 RF Amp reflected power too high"},
    { ILIERROR+DECERROR+ILI_RF_DUTY_CYCLE,
      "Channel 2 RF Amp duty cycle limit exceeded"},
    { ILIERROR+DECERROR+ILI_RF_OVER_TEMP,
      "Channel 2 RF Amp temperature limit exceeded"},
    { ILIERROR+DECERROR+ILI_RF_PULSE_WIDTH,
      "Channel 2 RF Amp pulse width limit exceeded"},
    { ILIERROR+DECERROR+ILI_RFMON_BP,
      "Channel 2 RF Power Monitoring BYPASSED"},
    { ILIERROR+DECERROR+ILI_RF_AMP_BP,
      "Channel 2 RF Amp errors BYPASSED"},

    { ILIERROR+CH3ERROR+ILI_10S_SAR,
      "Channel 3 RF power exceeds 10s SAR limit"},
    { ILIERROR+CH3ERROR+ILI_5MIN_SAR,
      "Channel 3 RF power exceeds 5min SAR limit"},
    { ILIERROR+CH3ERROR+ILI_PEAK_PWR,
      "Channel 3 peak RF power exceeds limit"},
    { ILIERROR+CH3ERROR+ILI_RF_AMP_CABLE,
      "Channel 3 RF Amp control cable error"},
    { ILIERROR+CH3ERROR+ILI_RF_REFL_PWR,
      "Channel 3 RF Amp reflected power too high"},
    { ILIERROR+CH3ERROR+ILI_RF_DUTY_CYCLE,
      "Channel 3 RF Amp duty cycle limit exceeded"},
    { ILIERROR+CH3ERROR+ILI_RF_OVER_TEMP,
      "Channel 3 RF Amp temperature limit exceeded"},
    { ILIERROR+CH3ERROR+ILI_RF_PULSE_WIDTH,
      "Channel 3 RF Amp pulse width limit exceeded"},
    { ILIERROR+CH3ERROR+ILI_RFMON_BP,
      "Channel 3 RF Power Monitoring BYPASSED"},
    { ILIERROR+CH3ERROR+ILI_RF_AMP_BP,
      "Channel 3 RF Amp errors BYPASSED"},

    { ILIERROR+CH4ERROR+ILI_10S_SAR,
      "Channel 4 RF power exceeds 10s SAR limit"},
    { ILIERROR+CH4ERROR+ILI_5MIN_SAR,
      "Channel 4 RF power exceeds 5min SAR limit"},
    { ILIERROR+CH4ERROR+ILI_PEAK_PWR,
      "Channel 4 peak RF power exceeds limit"},
    { ILIERROR+CH4ERROR+ILI_RF_AMP_CABLE,
      "Channel 4 RF Amp control cable error"},
    { ILIERROR+CH4ERROR+ILI_RF_REFL_PWR,
      "Channel 4 RF Amp reflected power too high"},
    { ILIERROR+CH4ERROR+ILI_RF_DUTY_CYCLE,
      "Channel 4 RF Amp duty cycle limit exceeded"},
    { ILIERROR+CH4ERROR+ILI_RF_OVER_TEMP,
      "Channel 4 RF Amp temperature limit exceeded"},
    { ILIERROR+CH4ERROR+ILI_RF_PULSE_WIDTH,
      "Channel 4 RF Amp pulse width limit exceeded"},
    { ILIERROR+CH4ERROR+ILI_RFMON_BP,
      "Channel 4 RF Power Monitoring BYPASSED"},
    { ILIERROR+CH4ERROR+ILI_RF_AMP_BP,
      "Channel 4 RF Amp errors BYPASSED"},

    { ILIERROR+ILI2_SPARE_0, "ILI #2, spare #0"},
    { ILIERROR+ILI2_SPARE_1, "ILI #2, spare #1"},
    { ILIERROR+ILI2_SPARE_2, "ILI #2, spare #2"},
    { ILIERROR+ILI2_SPARE_3, "ILI #2, spare #3"},
    { ILIERROR+ILI2_SPARE_4, "ILI #2, spare #4"},
    { ILIERROR+ILI2_SPARE_5, "ILI #2, spare #5"},
    { ILIERROR+ILI2_SPARE_6, "ILI #2, spare #6"},
    { ILIERROR+ILI2_SPARE_7, "ILI #2, spare #7"},
    { ILIERROR+ILI2_SPARE_8, "ILI #2, spare #8"},
    { ILIERROR+ILI2_SPARE_9, "ILI #2, spare #9"},
    { ILIERROR+ILI2_SPARE_10, "ILI #2, spare #10"},
    { ILIERROR+ILI2_SPARE_11, "ILI #2, spare #11"},
    { ILIERROR+ILI2_SPARE_12, "ILI #2, spare #12"},
    { ILIERROR+ILI2_SPARE_13, "ILI #2, spare #13"},
    { ILIERROR+ILI2_SPARE_14, "ILI #2, spare #14"},
    { ILIERROR+ILI2_SPARE_15, "ILI #2, spare #15"},

    { ISIERROR+ISI_XGRAD_FAULT, "X Gradient Fault"},
    { ISIERROR+ISI_YGRAD_FAULT, "Y Gradient Fault"},
    { ISIERROR+ISI_ZGRAD_FAULT, "Z Gradient Fault"},
    { ISIERROR+ISI_GRAD_AMP_ERR, " ...Amplifier Problem"},
    { ISIERROR+ISI_DUTY_CYCLE_ERR, " ...Duty Cycle Too Large"},
    { ISIERROR+ISI_OVERTEMP, "Gradient Coil Overtemp"},
    { ISIERROR+ISI_NO_COOLANT, "Gradient Coil Lost Coolant"},
    { ISIERROR+ISI_SPARE_3, "ISI, spare #3"},
    { ISIERROR+ISI_SPARE_4, "ISI, spare #4"},
    { ISIERROR+ISI_SPARE_1, "ISI, spare #1"},
    { ISIERROR+ISI_SPARE_2, "ISI, spare #2"},
    { ISIERROR+ISI_SYS_FAULT, " ...Reset ISI to Enable Gradients"},
    { ISIERROR+ISI_BYPASS, "ISI Gradient Protection Is Bypassed"},
    { SNS_ERROR+MAGNETLEG, "Magnet leg sensor error detected" },
    { SNS_ERROR+AIRPRESSURE, "Air pressure failure detected" },

    { PNEU_ERROR + PS,		"Pneumatic's power supply fault" },
    { PNEU_ERROR + VTTHRESH,    "VT airflow threshold exceeded" },
    { PNEU_ERROR + NB_STACK,	"Narrow bore stack fault" },
    { PNEU_ERROR + PRESSURE,    "Pneumatics pressure fault (<20 psi)" },

    { ICAT_ERROR + IMAGE_COPY,	"Failure in iCAT RF update." },   /* FPGA image copy to icAT ISFlash failed */
    { ICAT_ERROR + IMAGE_LOAD,   "iCAT RF did not initialize properly" },  /* iCAT FPGA image did not load */
    { ICAT_ERROR + REG_CONFIG,	"iCAT RF configuration failed" },  /* the FORTH confiuration of iCAT failed */
    { ICAT_ERROR + MIXED_RFS,	   "Mixed RFs Detected" },  /* Both VNMRS and iCAT RF were detected. */

    { 0,                       NULL }
};
