/*
 * Copyright (C) 2015  University of Oregon
 *
 * You may distribute under the terms of either the GNU General Public
 * License or the Apache License, as specified in the LICENSE file.
 *
 * For more information, see the LICENSE file.
 */
/*
 * This file was automatically generated with "ProbeIdCrypto -boot AES"
 *
 *	 DO NOT EDIT THIS FILE!
 */
package vnmr.probeid;

class ProbeIdWrapper {
	public static String algorithm = "AES";
	public static byte[] key = {
	 (byte) 82, (byte) -90, (byte) -128, (byte) -78, (byte) -68,
	 (byte) 21, (byte) -62, (byte) -95, (byte) -26, (byte) 10,
	 (byte) -21, (byte) -126, (byte) -110, (byte) -71, (byte) -98,
	 (byte) -48,
	};
}
